#!/usr/bin/env python3
"""Generate build.ninja. Run under WSL/Linux from the repo root.

    python3 configure.py            # extract, generate splat configs, split (each if needed), write build.ninja
    python3 configure.py --split    # regenerate the splat configs and re-split everything
    ninja                           # build every target and verify it against the original
    ninja objdiff                   # also the objects objdiff.json needs (see write_objdiff_json)
    ninja report                    # build/report.json, the progress report decomp.dev reads

Targets: `main` and each overlay on the disc (config/<target>.yaml, generated by tools/gen_splat.py).
"""
import argparse
import json
import platform
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PY = sys.executable
BINUTILS = f"tools/binutils/{platform.system().lower()}/mips-ps2-decompals-"  # linux or darwin
WIBO = "tools/wibo"
MWCC = "tools/mwcc/mwcps2-2.4-001213/mwccps2.exe"

# Zero padding an original overlay has after its code, beyond the 0x80 alignment of its data
# (bytes). Cause unknown: gx_aee's code ends at 0x1F0267C, but its data starts at 0x1F02700.
OVERLAY_TEXT_PAD = {"gx_aee": 0x80}

# The original linker's symbols, defined relative to the sections they describe (main.ld).
LINKER_SYMBOLS = """
/* The original linker's symbols, relative to what they describe (configure.py). */
_fbss = main_BSS_START;
D_003C7D80 = main_BSS_START;            /* crt0's spimdisasm label for _fbss */
_gp = main_SDATA_START + 0x7F20;
_ovl_start_addr = main_BSS_END;          /* overlays load right after main's .bss */
_ovl_align_addr = _ovl_start_addr + 0x7000;
_ovl_align_addr0 = _ovl_align_addr;
_end = _ovl_start_addr + 0x9E200;        /* end of the overlay area */
_stack = _end + 0x10000;
"""

ASFLAGS ="-EL -march=r5900 -mabi=eabi -G0 -no-pad-sections -I include"
CFLAGS = "-O2,p -sdatathreshold 0 -str readonly -enum min"
FILE_FLAGS = ROOT / "config/file_flags.txt"


def file_flags():
    """{unit: [extra MWCC flags]} from config/file_flags.txt: a setting the original used for a
    whole file (STYLE.md "Pragmas"), one line per unit, `<unit> <flags...>  # evidence`."""
    out = {}
    if FILE_FLAGS.exists():
        for line in FILE_FLAGS.read_text(encoding="utf-8").splitlines():
            parts = line.split("#")[0].split()
            if parts:
                out[parts[0]] = parts[1:]
    return out


def unit_cflags(unit):
    """The MWCC flags the build compiles a unit with (`Lens/lens_flare`, or `<target>:<unit>`):
    CFLAGS plus the unit's config/file_flags.txt entry. Every tool that compiles a unit uses this,
    so it compiles the unit exactly as the build does."""
    return CFLAGS.split() + file_flags().get(unit.split(":")[-1], [])


def asm_text(target):
    """All of a target's split asm, concatenated."""
    return "\n".join(p.read_text(encoding="utf-8", errors="replace")
                     for p in sorted((ROOT / "asm" / target).rglob("*.s")))


def ninja_escape(path):
    return str(path).replace("$", "$$").replace(" ", "$ ").replace(":", "$:")


THIRD_PARTY = ("lib/", "crt0", "mwcc_runtime/", "sd0712/")  # as in tools/progress.py
# The splitter's suffix on names that occur more than once (static functions and data in several
# units): the address or the overlay (as in tools/diff_unit.py's plain_name).
SPLIT_SUFFIX = re.compile(r"_(?:[0-9A-F]{8}|g[xyz]_\w+)$")


def fallback_units():
    """Units with functions linked from the original code (config/asm_functions.txt)."""
    units = set()
    for line in (ROOT / "config/asm_functions.txt").read_text(encoding="utf-8").splitlines():
        parts = line.split("#")[0].split()
        if len(parts) == 2:
            units.add(parts[0].rpartition(":")[2])
    return units


def c_units():
    """{unit: target} of the units built from C (config/c_units.txt)."""
    listed = {}
    path = ROOT / "config/c_units.txt"
    if path.exists():
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.split("#")[0].split()
            if len(line) == 2:
                listed[line[1]] = line[0]
    return listed


def write_objdiff_json(targets, listed, fallback):
    """objdiff.json, for objdiff and its progress reports.

    The target of every unit is its split original; the base is its C object. A unit with
    functions linked from the original code uses the C compiled without that fallback
    (build/objdiff/, `ninja objdiff`), so those functions don't show as matching, and doesn't count
    as complete. Neither does a unit containing a fake match (a FAKEMATCH note, or a function that
    needs a stand-in where the original had no code): that set is tools/progress.py's
    fake_units(), the definition PROGRESS.md's complete units use too. Categories: the game's
    code; libraries (not decompiled); and binary data that isn't compiled code (VU1 microcode,
    overlay headers, data without a source file)."""
    import progress
    fake = progress.fake_units()
    units = []
    for t in targets:
        for s in sorted((ROOT / "asm" / t).rglob("*.s")):
            unit = s.relative_to(ROOT / "asm" / t).with_suffix("").as_posix()
            entry = {"name": f"{t}/{unit}", "target_path": f"build/asm/{t}/{unit}.s.o"}
            is_c = listed.get(unit) == t
            if is_c:
                base = "build/objdiff" if unit in fallback else "build"
                entry["base_path"] = f"{base}/src/{unit}.c.o"
                labels = re.findall(r"^\s*[gd]label (\S+)", s.read_text(encoding="utf-8", errors="replace"), re.M)
                mappings = {name: SPLIT_SUFFIX.sub("", name) for name in labels if SPLIT_SUFFIX.search(name)}
                if mappings:
                    entry["symbol_mappings"] = mappings
            category = ("libraries" if unit.startswith(THIRD_PARTY) else
                        "data" if unit.startswith("data/") else "game")
            complete = is_c and unit not in fallback and unit not in fake
            entry["metadata"] = {"complete": complete, "progress_categories": [category]}
            if is_c:
                entry["metadata"]["source_path"] = f"src/{unit}.c"
            units.append(entry)
    config = {
        "$schema": "https://raw.githubusercontent.com/encounter/objdiff/main/config.schema.json",
        "custom_make": "ninja",
        "build_target": False,
        "build_base": True,
        "watch_patterns": ["*.c", "*.h"],
        "progress_categories": [
            {"id": "game", "name": "Game"},
            {"id": "libraries", "name": "Libraries (Sony SDK, C library (newlib), Metrowerks runtime, sound driver)"},
            {"id": "data", "name": "Not compiled code (VU1 microcode, overlay headers, data)"},
        ],
        "units": units,
    }
    (ROOT / "objdiff.json").write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8", newline="\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--split", action="store_true", help="regenerate splat configs and re-split")
    ap.add_argument("--objdiff-json", action="store_true",
                    help="only rewrite objdiff.json (ninja does, when the fake matches may have changed)")
    args = ap.parse_args()

    sys.path.insert(0, str(ROOT / "tools"))
    if args.objdiff_json:
        targets = sorted(p.stem for p in (ROOT / "config").glob("*.yaml"))
        targets.remove("main")
        write_objdiff_json(["main"] + targets, c_units(), fallback_units())
        return
    import extract
    if not (ROOT / "build/orig/main.bin").exists() or not extract.assets_present():
        subprocess.run([PY, "tools/extract.py"], cwd=ROOT, check=True)
    c_list = ROOT / "config/c_units.txt"
    stale = c_list.exists() and (ROOT / "config/main.yaml").exists() and \
        c_list.stat().st_mtime > (ROOT / "config/main.yaml").stat().st_mtime
    if stale:
        args.split = True  # the C unit list changed: regenerate configs and re-split
    if args.split or not (ROOT / "config/main.yaml").exists():
        subprocess.run([PY, "tools/gen_splat.py"], cwd=ROOT, check=True)
    targets = sorted(p.stem for p in (ROOT / "config").glob("*.yaml"))
    targets.remove("main")
    targets.insert(0, "main")
    for t in targets:
        if args.split or not (ROOT / "asm" / t).exists():
            shutil.rmtree(ROOT / "asm" / t, ignore_errors=True)
            subprocess.run([PY, "-m", "splat", "split", f"config/{t}.yaml"], cwd=ROOT, check=True,
                           stdout=subprocess.DEVNULL)
            # Symbols spimdisasm guessed where the original has no relocation become numbers.
            subprocess.run([PY, "tools/unsymbolize.py", t], cwd=ROOT, check=True)
            # Original symbols inside asm data and blobs become labels there (they move with it).
            subprocess.run([PY, "tools/label_symbols.py", t], cwd=ROOT, check=True)
            # Relocations the original has but spimdisasm wrote as plain words get them back.
            subprocess.run([PY, "tools/resymbolize.py", t], cwd=ROOT, check=True)

    # The Metrowerks overlay linker starts and ends every overlay section on a 0x80 boundary
    # (every GX/*.BIN is a multiple of 0x80). The asm objects carry that padding already; C
    # objects don't, so say it in the linker script.
    for t in targets:
        if t == "main":
            continue
        ld = ROOT / f"build/{t}.ld"
        text = ld.read_text(encoding="utf-8")
        for sym in (f"{t}_DATA_START = .;", f"{t}_DATA_END = .;", f"{t}_RODATA_END = .;",
                    f"{t}_BSS_START = .;"):
            pad = OVERLAY_TEXT_PAD.get(t, 0) if sym.startswith(f"{t}_DATA_START") else 0
            aligned = f"        . = ALIGN(., 0x80);{f' . += 0x{pad:X};' if pad else ''}\n        {sym}"
            if aligned not in text:
                text = text.replace(f"        {sym}", aligned)
        ld.write_text(text, encoding="utf-8", newline="\n")

    # main: symbols the original's linker defined, relative to the sections they describe, so
    # they follow the code if it moves. The C library's (newlib's) common variables (errno, getopt's state) were
    # allocated after every object's .bss.
    ld = ROOT / "build/main.ld"
    text = ld.read_text(encoding="utf-8")
    commons = ("        /* Common symbols, allocated after every object like the Metrowerks linker did. */\n"
               + "".join(f"        {name} = .; . += 4;\n" for name in ("optreset", "optopt", "optarg", "errno")))
    end_bss = "        . = ALIGN(., 16);\n        main_BSS_END = .;"
    if commons not in text:
        assert end_bss in text, "main.ld: no main_BSS_END"
        text = text.replace(end_bss, commons + end_bss)
    if LINKER_SYMBOLS not in text:
        text += LINKER_SYMBOLS
    ld.write_text(text, encoding="utf-8", newline="\n")

    # Only units listed in config/c_units.txt are built; other C files are work in progress,
    # compiled on their own by tools/diff_unit.py.
    listed = c_units()
    c_files = sorted(p.relative_to(ROOT) for p in (ROOT / "src").rglob("*.c")
                     if p.relative_to(ROOT / "src").with_suffix("").as_posix() in listed)
    c_objs = [Path("build") / c.with_suffix(".c.o") for c in c_files]
    for unit in file_flags():
        if not (ROOT / "src" / f"{unit}.c").exists():
            sys.exit(f"config/file_flags.txt: no src/{unit}.c")

    lines = [
        "# Generated by configure.py -- do not edit.",
        f"asflags = {ASFLAGS}",
        f"cflags = {CFLAGS}",
        "",
        "rule as",
        f"  command = {BINUTILS}as $asflags -o $out $in && {BINUTILS}objcopy $alignflags $out",
        "  description = AS $in",
        "",
        "rule cc",
        f"  command = {WIBO} {MWCC} -c $cflags -nostdinc -Iinclude -stderr $in -o $out"
        f" && {PY} tools/mwcc_fixup.py $out && {PY} tools/asm_fallback.py $out $unit"
        f" && {PY} tools/cdeps.py $in $out",
        "  depfile = $out.d",
        "  deps = gcc",
        "  description = CC $in",
        "",
        "rule cc_own",  # for objdiff: the C alone, without the original-code fallback
        f"  command = {WIBO} {MWCC} -c $cflags -nostdinc -Iinclude -stderr $in -o $out"
        f" && {PY} tools/mwcc_fixup.py $out && {PY} tools/cdeps.py $in $out",
        "  depfile = $out.d",
        "  deps = gcc",
        "  description = CC $in (objdiff)",
        "",
        "rule ld",
        f"  command = {BINUTILS}ld -EL -T build/$target.ld -T build/$target.undefined_syms_auto.txt"
        " -T build/$target.undefined_funcs_auto.txt -T build/$target.provide.ld $extra"
        " -Map build/$target.map --no-check-sections -o $out",
        "  description = LD $out",
        "",
        "rule exportsyms",
        f"  command = {PY} tools/export_syms.py $in $out",
        "  description = SYMS $out",
        "",
        "rule objcopy",
        f"  command = {BINUTILS}objcopy -O binary $in $out",
        "  description = OBJCOPY $out",
        "",
        "rule check",
        f"  command = {PY} tools/check.py $in build/orig/$target.bin $vram && touch $out",
        "  description = CHECK $in",
        "",
        "rule configure",
        f"  command = {PY} configure.py",
        "  generator = 1",
        "",
    ]
    fallback = fallback_units()
    for c, o in zip(c_files, c_objs):
        unit = c.relative_to("src").with_suffix("").as_posix()
        # asm_fallback.py reads the original's object for units with functions linked from it.
        orig_obj = f" build/asm/{listed[unit]}/{ninja_escape(unit)}.s.o" if unit in fallback else ""
        lines.append(f"build {ninja_escape(o)}: cc {ninja_escape(c)} | tools/mwcc_fixup.py config/stripped_functions.txt"
                     f" tools/asm_fallback.py config/asm_functions.txt{orig_obj}")
        lines.append(f"  unit = {listed[unit]}:{unit}")
        if unit_cflags(unit) != CFLAGS.split():
            lines.append(f"  cflags = {' '.join(unit_cflags(unit))}")
    own_objs = []
    for c in c_files:
        unit = c.relative_to("src").with_suffix("").as_posix()
        if unit in fallback:
            o = Path("build/objdiff") / c.with_suffix(".c.o")
            own_objs.append(o)
            lines.append(f"build {ninja_escape(o)}: cc_own {ninja_escape(c)} | tools/mwcc_fixup.py"
                         " config/stripped_functions.txt")
            if unit_cflags(unit) != CFLAGS.split():
                lines.append(f"  cflags = {' '.join(unit_cflags(unit))}")
    lines += [f"build objdiff: phony {' '.join(ninja_escape(o) for o in own_objs)}", ""]
    write_objdiff_json(targets, listed, fallback)
    # Absolute symbols the link may still need, which don't move with main's code:
    # - main: the overlays' entry tables (stage_*) and segment bounds, which live at the fixed
    #   overlay address, and sizes (__data_size). Everything else in main is defined by an object
    #   or by main.ld (see above), so a missing definition is a link error, not a silent absolute.
    # - overlays: their own symbols as a fallback; main's come from build/main_syms.ld, exported
    #   from this build's main.elf.
    for t in targets:
        provide, seen = [], set()
        sources = ["config/symbols_extern.txt"] + ([f"config/symbols_{t}.txt"] if t != "main" else [])
        for src in sources:
            for line in (ROOT / src).read_text(encoding="utf-8").splitlines():
                m = line.split(" = ")
                if len(m) != 2 or m[0] in seen:
                    continue
                value = int(m[1].split(";")[0], 16)
                if t == "main" and 0x100000 <= value < 0x1F01E00 and m[0] != "__data_size":
                    continue  # defined by main's own objects and linker script
                seen.add(m[0])
                provide.append(f"PROVIDE({m[0]} = 0x{value:08X});")
        (ROOT / "build").mkdir(exist_ok=True)
        (ROOT / f"build/{t}.provide.ld").write_text("\n".join(provide) + "\n", encoding="utf-8", newline="\n")

    oks = []
    for t in targets:
        vram = "0x100000" if t == "main" else "0x1F01E00"
        # Section alignments for the asm objects: gen_splat.py's address-derived ones, overridden
        # by config/min_align_<t>.txt (tools/min_align.py), the smallest that reproduce the layout,
        # so objects don't snap to large boundaries if code moves.
        values = {}
        for name in (f"config/align_{t}.txt", f"config/min_align_{t}.txt"):
            if (ROOT / name).exists():
                for line in (ROOT / name).read_text(encoding="utf-8").splitlines():
                    path, sect, value = line.split()
                    values[(path, sect)] = int(value, 16)
        align = {}
        for (path, sect), value in values.items():
            align.setdefault(path, []).append(f"--set-section-alignment {sect}={value}")
        objs = []
        for s in sorted((ROOT / "asm" / t).rglob("*.s")):
            s = s.relative_to(ROOT)
            o = Path("build") / s.with_suffix(".s.o")
            objs.append(o)
            lines.append(f"build {ninja_escape(o)}: as {ninja_escape(s)}")
            lines.append(f"  alignflags = {' '.join(align.get(s.as_posix(), []))}")
        deps = " ".join(ninja_escape(o) for o in objs + c_objs)
        lines += [
            f"build build/{t}.elf: ld | build/{t}.ld {deps}" + (" build/main_syms.ld" if t != "main" else ""),
            f"  target = {t}",
            f"  extra = {'-T build/main_syms.ld' if t != 'main' else ''}",
            f"build build/{t}.bin: objcopy build/{t}.elf",
            f"build build/{t}.ok: check build/{t}.bin",
            f"  target = {t}",
            f"  vram = {vram}",
            "",
        ]
        oks.append(f"build/{t}.ok")
    lines += [
        "build build/main_syms.ld: exportsyms build/main.elf | tools/export_syms.py",
        "build build.ninja: configure | configure.py tools/gen_splat.py config/c_units.txt"
        " config/asm_functions.txt config/file_flags.txt",
        "",
        f"build check: phony {' '.join(oks)}",
        "default check",
        "",
        # decomp.dev's progress report (objdiff-cli from tools/download_tools.py --objdiff);
        # docs/decomp-dev.md explains how it is published.
        # objdiff.json's complete flags depend on the fake matches (tools/progress.py fake_units()):
        # FAKEMATCH notes in any C file, stand-in dependents and positions.
        "rule objdiff_json",
        f"  command = {PY} configure.py --objdiff-json",
        "  description = OBJDIFF objdiff.json",
        "build objdiff.json: objdiff_json | configure.py tools/progress.py tools/standins.py"
        " tools/standin_deps.py config/standin_deps.txt config/asm_functions.txt config/c_units.txt "
        + " ".join(ninja_escape(p.relative_to(ROOT).as_posix()) for p in sorted((ROOT / "src").rglob("*.c"))),
        "",
        "rule objdiff_report",
        "  command = tools/objdiff-cli report generate -o $out",
        "  description = REPORT $out",
        "build build/report.json: objdiff_report | check objdiff objdiff.json",
        "build report: phony build/report.json",
        "",
    ]
    (ROOT / "build.ninja").write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"build.ninja: {len(targets)} targets, {len(c_files)} C files")


if __name__ == "__main__":
    main()
