/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Chacter_Draw/vifot/, by unit, in the order of their code. */
#ifndef SH2_API_CHACTER_DRAW_VIFOT_H
#define SH2_API_CHACTER_DRAW_VIFOT_H

#include "sh2/types.h"

/* Chacter_Draw/vifot/sh_kt_pkbuf.c */
void ktPkBufInit(struct ktPkBuf *p, void *buf0, void *buf1, int size);
void *ktPkBufNext(struct ktPkBuf *p);
void *ktPkBufCurrent(struct ktPkBuf *p);

/* Chacter_Draw/vifot/sh_kt_vif0.c */
void ktVif0Init(void);
void ktVif0Wait(void);
void ktVif0Wait2(void);
void ktVif0Send(void *p, int tte);

/* Chacter_Draw/vifot/sh_kt_vif0pkbuf.c */
void ktVif0PkBufInit(void *buf0, void *buf1, int size);
void sh2_ktVif0PkBufInit(void);
void *ktVif0PkBufNext(void);
void *ktVif0PkBufCurrent(void);

/* Chacter_Draw/vifot/sh_kt_vif1.c */
void ktVif1Init(void);

/* Chacter_Draw/vifot/sh_kt_vif1ot2.c */
void ktVif1Ot2Init(struct ktVif1Ot2 *ot, unsigned int n_bits_1, struct _sceDmaTag *top_1, unsigned int n_bits_2, struct _sceDmaTag *top_2);
void ktVif1Ot2Reset(struct ktVif1Ot2 *ot);
void ktVif1Ot2Append(struct ktVif1Ot2 *ot, unsigned int depth, u_long128 *packet_);
void ktVif1Ot2AppendFake(struct ktVif1Ot2 *ot, unsigned int depth, u_long128 *packet_, void *entity_);
void ktVif1Ot2KickPre(struct ktVif1Ot2 *ot);

/* Chacter_Draw/vifot/sh_kt_vif1pkbuf.c */
void ktVif1PkBufInit(void *buf0, void *buf1, int size);
void sh2_ktVif1kBufInit(void);
void *ktVif1PkBufNext(void);

#endif
