/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Event/stage/, by unit, in the order of their code. */
#ifndef SH2_API_EVENT_STAGE_H
#define SH2_API_EVENT_STAGE_H

#include "sh2/types.h"

/* Event/stage/stg_toilet.c */
int Kari_hisyakai(int KeyAlpha);

#endif
