/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/GFW/gfw_test/, by unit, in the order of their code. */
#ifndef SH2_API_GFW_GFW_TEST_H
#define SH2_API_GFW_GFW_TEST_H

#include "sh2/types.h"

/* GFW/gfw_test/camera.c */
void SetVu0ViewScreenClipMatrix(float (*view_screen)[4], float (*view_clip)[4], float (*clip_screen)[4], float *clip_vol, float scrz, float ax, float ay, float cx, float cy, float zmin, float zmax, float nearz, float farz);

/* GFW/gfw_test/kari_probe_draw.c */
void DBG_data_loadGS(void);
void sh2gfw_Vu0NormalLightPhongMatrix(float (*m)[4], float *l0, float *l1, float *l2, float *eyedir);
void kari_DBG_print_junbi(unsigned long *res, unsigned long *res2);

/* GFW/gfw_test/sh2_dmachain_regist.c */
void sh2gfw_registDrawTag(union Q_WORDDATA **ppqwd, unsigned int addr, unsigned int tagtail, unsigned int itnum);
void sh2gfw_setEND_chain(union Q_WORDDATA **ppqwd);
void kari_sh2gfw_VUMICRO_registchain(union Q_WORDDATA **ppcurr);
void sh2gfw_VUMATIRICES_registchain(struct sh2gfw_VU_PARMS *VU1_PARMS, union Q_WORDDATA **ppcurr);
void sh2gfw_VUGSREGS_registchain(struct sh2gfw_VU_PARMS *VU1_PARMS, union Q_WORDDATA **ppcurr);
void sh2gfw_regist_BLOCKMATRICES(struct sh2gfw_BLOCK_MAN *pB_man, union Q_WORDDATA **ppqwd);
void sh2gfw_regist_BLOCKLIGHTS(struct sh2gfw_BLOCK_MAN *pB_man, union Q_WORDDATA **ppqwd);

/* GFW/gfw_test/sh2gfw_OV_PreDraw.h */
void ru21_ru24_LightFlame(void);

/* GFW/gfw_test/sh2gfw_shcamtest.c */
void sh2gfw_set_ViewScreenM(void);
void sh2gfw_init_shcamera(void);
void sh2gfw_test_shcamera_main(void);

/* GFW/gfw_test/sh2gfw_util.c */
int sceVu0ViewVolumeClip(float *clip, float (*local_clip)[4], float *vertex);
void CopyNode(struct ScissorNode *nod0, struct ScissorNode *nod1);
void InitNodeArraySet(struct ScissorNodeArraySet *scissorflip);
void ResetNodeArraySet(struct ScissorNodeArraySet *scissorflip);
void FlipNodeArray(struct ScissorNodeArraySet *scissorflip);
void PushTriangleNodeArray(struct ScissorNodeArraySet *scissorflip, struct ScissorNode *nod, int mode);
void InitScissorPlane(struct ScissorPlaneSet *sp);
int ClipCheck(struct ScissorNode *a, struct ScissorNode *b);
void InterpNode(struct ScissorNode *inter, struct ScissorNode *inside, struct ScissorNode *outside, float sgn, int xyzflag);
void ScissorTriangle(struct ScissorNodeArraySet *scissorflip, struct ScissorPlaneSet *planeset);
void MakeScissorPolygon(struct ScissorNodeArraySet *scissorflip, int Prim, int flag, union Q_WORDDATA **ppqwd);
void MakeScissorPacket(void *DataBuf, void **OutputBuf, void **SciBuf, int flag, int Prim, int VertexNum);
void sh2gfw_util_zeroq(union Q_WORDDATA *qwd, int qsize);

#endif
