/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Chacter/, by unit, in the order of their code. */
#ifndef SH2_API_CHACTER_H
#define SH2_API_CHACTER_H

#include "sh2/types.h"

/* Chacter/anime.c */
void shCharacterStayModelExecItem(struct shSkelton *stp, float *rot);
void shCharacterStayModelExecNthParts(struct shSkelton *stp, float *pos, float *rot);
void shCharacterAnimePartsControl(struct shAnime3d *ap, struct shSkelton *stp, struct FVEC *rot);
void shCharacterAnimeSetSkelton(struct shAnime3d *ap, struct shSkelton *stp);
int shCharacterDramaAnimeExecMain(struct shAnime3d *ap);
int shCharacterPlayingAnimeExecMain(struct shAnime3d *ap, int type);
void shCharacterStayModelScale(struct shAnime3d *ap);

/* Chacter/bg_chara.c */
int BgCharaGetBlockSize(union fsFileIndex *id);
void BgCharaRelocateSet(int glb_crd, float x, float z, int chara_id);
int BgCharaIsId(int chara_id);
void *BgCharaIsLoad(int chara_id);
void BgCharaManInit(void);
void BgCharaMan(int cnt);
void BgCharaDelSlot(int slot);
int BgCharaGetSlotId(int slot);

/* Chacter/bg_obj_stay.c */
void shCharacterSetStayObjectLow(struct SubCharacter *scp);

/* Chacter/chara_bound.c */
float CharaGetBoundR(int chara_id);

/* Chacter/chara_saveinfo.c */
void shCharacterSetSaveData(struct _Character_Info *chara);
void shCharacterExtGameData(struct _Character_Info *chara);

/* Chacter/charaboundtbl.c */
int CharaBoundTblNum(void);

/* Chacter/item_screen_obj.c */
void shCharacterWorldScreenObjectSetNew(struct SubCharacter *this, float scale);
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetItemScreenItemLow
void shCharacterSetItemScreenItemLow(struct SubCharacter *scp);
#endif
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetWorldScreenItemLow
void shCharacterSetWorldScreenItemLow(struct SubCharacter *scp);
#endif

/* Chacter/lake_wave.c */
void mizTestLakeWaveInit(void);
struct _shLakeWaveInfo *mizTestLakeWaveMain(struct SubCharacter *scp);

/* Chacter/m3_angela.c */
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetHumanAGLLow
void shCharacterSetHumanAGLLow(struct SubCharacter *scp);
#endif
int shCharacterHumanAGLAnimeSet(struct SubCharacter *scp, int anime_id);
int shCharacterHumanAGLAnimeSetP(struct SubCharacter *scp, int anime_id);
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetHumanRAGLLow
void shCharacterSetHumanRAGLLow(struct SubCharacter *scp);
#endif

/* Chacter/m3_anime_subfunc.c */
void sh_PJMS_SetUntouchUpper(struct shSkelton *stp);
void sh_PJMS_SetUntouchUnder(struct shSkelton *stp);
void sh_PJMS_ResetUntouchUpper(struct shSkelton *stp);
void sh_PJMS_ResetUntouchUnder(struct shSkelton *stp);
void mizSetUntouchWithoutKnee(struct shSkelton *stp);
void mizResetUntouchWithoutKnee(struct shSkelton *stp);
void MariaSetUntouchWithoutNeck(struct shSkelton *stp);
void MariaResetUntouchWithoutNeck(struct shSkelton *stp);

/* Chacter/m3_arm.c */
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetEnemyARMLow
void shCharacterSetEnemyARMLow(struct SubCharacter *scp);
#endif
int shCharacterEnemyARMAnimeSetP(struct SubCharacter *scp, int anime_id, int comp);
void shGetEnemyARMAttackPos(struct SubCharacter *scp, float *s_pos, float *s_vec, unsigned short atk);

/* Chacter/m3_bgobj.c */
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetObjectLow
void shCharacterSetObjectLow(struct SubCharacter *scp);
#endif
int shCharacterObjectAnimeSet(struct SubCharacter *scp, int anime_id);
int shCharacterObjectAnimeSetP(struct SubCharacter *scp, int anime_id);
void shCharacterSetRObjectLow(struct SubCharacter *scp);

/* Chacter/m3_boat.c */
void bot_flg_on(unsigned int *type, unsigned int status);
void bot_flg_off(unsigned int *type, unsigned int status);
int bot_anime_flg_on(unsigned int status);
void bot_st_set(int status, struct shBoatWork *w);
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetHumanBOTLow
void shCharacterSetHumanBOTLow(struct SubCharacter *scp);
#endif
void shCharacterBoatWorkInit(void);
int shCharacterHumanBOTAnimeSet(struct SubCharacter *scp, int anime_id);
void shUpdateBoatJamesPosAfterAnime(void);

/* Chacter/m3_boat_jms.c */
void BoatPlayerCheckControl(void);

/* Chacter/m3_bos.c */
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetEnemyBOSLow
void shCharacterSetEnemyBOSLow(struct SubCharacter *scp);
#endif
int shCharacterEnemyBOSAnimeSet(struct SubCharacter *scp, int anime_id);
int shCharacterEnemyBOSAnimeSetP(struct SubCharacter *scp, int anime_id, int comp);
void shGetEnemyBOSAttackPos(struct SubCharacter *scp, float *s_pos, float *s_vec, unsigned short atk);

/* Chacter/m3_djames.c */
void DemoPlayerSetHeight(struct SubCharacter *this);
void shCharacterSetHumanDJMSLow(struct SubCharacter *scp);
int shCharacterHumanDJAMESAnimeSet(struct SubCharacter *scp, int anime_id);
void shCharacterSetHumanRDJMSLow(struct SubCharacter *scp);

/* Chacter/m3_dmaria.c */
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetHumanDMARLow
void shCharacterSetHumanDMARLow(struct SubCharacter *scp);
#endif
int shCharacterHumanDMARAnimeSet(struct SubCharacter *scp, int anime_id);
int shCharacterHumanDMARAnimeSetP(struct SubCharacter *scp, int anime_id);

/* Chacter/m3_edb.c */
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetEnemyEDBLow
void shCharacterSetEnemyEDBLow(struct SubCharacter *scp);
#endif
int shCharacterEnemyEDBAnimeSet(struct SubCharacter *scp, int anime_id);
int shCharacterEnemyEDBAnimeSetP(struct SubCharacter *scp, int anime_id, int comp);
void shGetEnemyEDBAttackPos(struct SubCharacter *scp, float *s_pos, float *s_vec, unsigned short atk);

/* Chacter/m3_eddie.c */
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetHumanEDILow
void shCharacterSetHumanEDILow(struct SubCharacter *scp);
#endif
int shCharacterHumanEDIAnimeSet(struct SubCharacter *scp, int anime_id);
int shCharacterHumanEDIAnimeSetP(struct SubCharacter *scp, int anime_id);

/* Chacter/m3_ike.c */
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetEnemyIKELow
void shCharacterSetEnemyIKELow(struct SubCharacter *scp);
#endif
int shCharacterEnemyIKEAnimeSet(struct SubCharacter *scp, int anime_id);
int shCharacterEnemyIKEAnimeSetP(struct SubCharacter *scp, int anime_id, int comp);
void shGetEnemyIKEAttackPos(struct SubCharacter *scp, float *s_pos, float *s_vec, unsigned short atk);

/* Chacter/m3_inu.c */
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetHumanINULow
void shCharacterSetHumanINULow(struct SubCharacter *scp);
#endif
int shCharacterHumanINUAnimeSet(struct SubCharacter *scp, int anime_id);
int shCharacterHumanINUAnimeSetP(struct SubCharacter *scp, int anime_id, int comp);

/* Chacter/m3_laura.c */
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetHumanLAULow
void shCharacterSetHumanLAULow(struct SubCharacter *scp);
#endif
int shCharacterHumanLAUAnimeSet(struct SubCharacter *scp, int anime_id);
int shCharacterHumanLAUAnimeSetP(struct SubCharacter *scp, int anime_id);

/* Chacter/m3_maria.c */
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetHumanMARLow
void shCharacterSetHumanMARLow(struct SubCharacter *scp);
#endif
int shCharacterHumanMARAnimeSet(struct SubCharacter *scp, int anime_id);
void shCharacterMariaWorkInit(void);
void shCharacterMariaWorkInitAtGameStart(void);

/* Chacter/m3_maria_sub.c */
void mar_flg_on(unsigned int *type, unsigned int status);
void mar_flg_off(unsigned int *type, unsigned int status);
int mar_sub_flg_on(unsigned int status);
int mar_anime_flg_on(unsigned int status);
void mar_main_st_set(int status, struct shMariaWork *w);
void mar_sub_st_set(int status, struct shMariaWork *w);
void mar_sub_flg_set(int status, struct shMariaWork *w);
void MariaSetHeightDummy(void);
void MariaSetHeight(struct SubCharacter *this);
void GetMariaPartsWorldMatrix(float (*mat)[4], unsigned int parts_name);
void MariaCheckDamage(struct SubCharacter *this);
void MariaCheckSetParameterPhase1(struct SubCharacter *this);
void MariaCheckSetParameterPhase2(struct SubCharacter *this);
void MariaCheckControl(struct SubCharacter *this);
void MariaCheckAnime(struct SubCharacter *scp);
void MariaUpdatePosition(struct SubCharacter *this);
void MariaCheckSound(void);
void MariaInitOnConnect(void);
void MariaSetHeightConnectWait(void);
void MariaStatusClear(void);

/* Chacter/m3_mary.c */
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetHumanMRYLow
void shCharacterSetHumanMRYLow(struct SubCharacter *scp);
#endif
int shCharacterHumanMRYAnimeSet(struct SubCharacter *scp, int anime_id);
int shCharacterHumanMRYAnimeSetP(struct SubCharacter *scp, int anime_id);

/* Chacter/m3_mkn.c */
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetEnemyMKNLow
void shCharacterSetEnemyMKNLow(struct SubCharacter *scp);
#endif
int shCharacterEnemyMKNAnimeSet(struct SubCharacter *scp, int anime_id);
int shCharacterEnemyMKNAnimeSetP(struct SubCharacter *scp, int anime_id, int comp);
void shGetEnemyMKNAttackPos(struct SubCharacter *scp, float *s_pos, float *s_vec, unsigned short atk);
void shEnemyMKN_EffectFoot(struct SubCharacter *scp, int type);

/* Chacter/m3_mxx.c */
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetHumanMXXLow
void shCharacterSetHumanMXXLow(struct SubCharacter *scp);
#endif

/* Chacter/m3_nik.c */
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetObjectNIKLow
void shCharacterSetObjectNIKLow(struct SubCharacter *scp);
#endif

/* Chacter/m3_nse.c */
void shCharacterSetEnemyNSELow(struct SubCharacter *scp);
int shCharacterEnemyNSEAnimeSetP(struct SubCharacter *scp, int anime_id, int comp);
void shGetEnemyNSEAttackPos(struct SubCharacter *scp, float *s_pos, float *s_vec, unsigned short atk);

/* Chacter/m3_oni.c */
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetEnemyONILow
void shCharacterSetEnemyONILow(struct SubCharacter *scp);
#endif
int shCharacterEnemyONIAnimeSet(struct SubCharacter *scp, int anime_id);
int shCharacterEnemyONIAnimeSetP(struct SubCharacter *scp, int anime_id, int comp);
void shGetEnemyONIAttackPos(struct SubCharacter *scp, float *s_pos, float *s_vec, unsigned short atk);

/* Chacter/m3_pap.c */
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetEnemyPAPLow
void shCharacterSetEnemyPAPLow(struct SubCharacter *scp);
#endif
int shCharacterEnemyPAPAnimeSet(struct SubCharacter *scp, int anime_id);
int shCharacterEnemyPAPAnimeSetP(struct SubCharacter *scp, int anime_id, int comp);
void shGetEnemyPAPAttackPos(struct SubCharacter *scp, float *s_pos, float *s_vec, unsigned short atk);

/* Chacter/m3_play.c */
void player_flg_on(unsigned int *type, unsigned int status);
void player_flg_off(unsigned int *type, unsigned int status);
int upper_flg_on(unsigned int status);
int lower_flg_on(unsigned int status);
int u_anime_flg_on(unsigned int status);
int l_anime_flg_on(unsigned int status);
int actwithwep_flg_on(unsigned int status);
void lower_st_set(int status, struct shPlayerWork *w);
void upper_st_set(int status, struct shPlayerWork *w);
void lower_flg_set(int status, struct shPlayerWork *w);
void upper_flg_set(int status, struct shPlayerWork *w);
void actwithwep_flg_set(unsigned char status, struct shPlayerWork *w);
void PlayerCheckInit(struct SubCharacter *this);
void PlayerSetHeightDummy(void);
void PlayerSetHeight(struct SubCharacter *this);
void PlayerSetHeightConnectWait(void);
void PlayerCheckBothArmsAngle(struct SubCharacter *this);
void BoatPlayerCheckAnime(void);
void shGetJamesLightPos(float *pos, float *vec);
void shGetJamesLightPosOriginal(float *pos, float *vec);
void shGetJamesLightPos_Calc(void);
void GetPlayerPartsMatrixForCameraCtrl(float (*mat)[4], unsigned int parts_name);
void GetPlayerPartsWorldMatrix(float (*mat)[4], unsigned int parts_name);
void GetPlayerPartsLocalMatrix(struct FMAT *dest, int parts_name);
struct shCharaInfo *GetPlayerInfoForCameraCtrl(void);
void shCharacterPlayerWorkInitAtPowerOn(void);
void shCharacterPlayerWorkInitAtGameStart(void);
void shCharacterSetPlayerLow(struct SubCharacter *scp);
void PlayerGetTargetInfo(void);
void PlayerGetTarget(void);
void PlayerChangeTarget(int key);
void PlayerCheckHuggingAttack(void);
int PlayerChectGuardSuccess(void);
void PlayerRequestAttack(struct shPlayerWork *w, int num);
void PlayerRequestAttackFinish(struct shPlayerWork *w);
void PlayerCheckStraightLine(struct SubCharacter *this, float spd_roty);
void shGetJamesKickStartPos(float *pos, float *vec);
void shGetJamesTrampStartPos(float *pos, float *vec);
int PlayerNowItemName(unsigned char wep);
int PlayerSearchVIewButtonCheck(void);
float PlayerGetNeckAngleX(void);
float PlayerGetNeckAngleY(void);
void PlayerInitOnConnect(void);
void PlayerStatusClear(void);
void close_to_angle_target(float *now, float tgt, float min, float max, float spd);
/* Chacter/m3_boat.c has a static close_to_value of its own. */
#ifndef SH2_LOCAL_close_to_value
void close_to_value(float *now, float tgt, float mov);
#endif
int PlayerReverseLightCalcIsOn(void);
int PlayerWaterRoadIsOn(void);

/* Chacter/m3_play_2d.c */
void PlayerUpdatePosition2D(struct SubCharacter *this);
void PlayerCheckControl2D(struct SubCharacter *this);

/* Chacter/m3_play_3d.c */
void PlayerUpdatePosition3D(struct SubCharacter *this);
void PlayerCheckControl3D(struct SubCharacter *this);

/* Chacter/m3_play_common.c */
void PlayerSetDT(void);
void PlayerUpdateStatus(struct SubCharacter *this);
void PlayerCheckHuggingButton(void);
void PlayerSpeedDownToStand(struct SubCharacter *p);
void PlayerSetAttackWithWalkIsOk(void);
void PlayerSetAttackWithRunIsOk(void);
void PlayerCheckAimingToEnemy(struct SubCharacter *p, struct SubCharacter *target);
void PlayerCheckAttack(struct SubCharacter *this);
void lower_stand(struct SubCharacter *p);
void upper_stand(struct SubCharacter *p);
void lower_relax(struct SubCharacter *p);
void upper_relax(struct SubCharacter *p);
void lower_alert(struct SubCharacter *p);
void upper_alert(struct SubCharacter *p);
void lower_tired(struct SubCharacter *p);
void upper_tired(struct SubCharacter *p);
void lower_ready(struct SubCharacter *p);
void upper_ready(struct SubCharacter *p);
void lower_readyoff(struct SubCharacter *p);
void upper_readyoff(struct SubCharacter *p);
void upper_run1(struct SubCharacter *p);
void upper_run2(struct SubCharacter *p);
void upper_run3(struct SubCharacter *p);
void lower_hold(struct SubCharacter *p);
void upper_hold(struct SubCharacter *p);
void lower_release(struct SubCharacter *p);
void upper_release(struct SubCharacter *p);
void lower_attack(struct SubCharacter *p);
void upper_attack(struct SubCharacter *p);
void lower_kick(struct SubCharacter *p);
void upper_kick(struct SubCharacter *p);
void lower_fall(struct SubCharacter *p);
void upper_fall(struct SubCharacter *p);
void lower_damage(struct SubCharacter *p);
void upper_damage(struct SubCharacter *p);
void lower_to_stand(struct SubCharacter *p);
void upper_to_stand(struct SubCharacter *p);
void upper_wall_f(struct SubCharacter *p);
void lower_event(struct SubCharacter *p);
void upper_event(struct SubCharacter *p);

/* Chacter/m3_play_efect.c */
void PlayerCheckEffect(void);
void PlayerCheckSound(void);
void PlayerCheckDualShock(void);
int PlayerJamesIsInSquare(float *pos0, float *pos1);

/* Chacter/m3_play_event.c */
int PlayerNowDemoEventMode(void);
int PlayerEventButtonCheck(int button);
int PlayerEventDeadAnimeFinish(void);
int PlayerEventJamesDeadly(void);
int PlayerEventMariaDeadly(void);
int PlayerEventAnimeSuccessFrame(void);
void PlayerEventAnimeSet(int anime);
void PlayerEventAnimeSetDirect(int anime);
float PlayerEventMove(float *target);
int PlayerEventMoveIsEnd(void);
int PlayerEventMoveCancel(void);
int shCharacterHumanPJAMESAnimeSet(struct SubCharacter *scp, int anime_id);
void JamesWeaponSet(int wep);
int PlayerGetJamesWeapon(void);

/* Chacter/m3_red.c */
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetEnemyREDLow
void shCharacterSetEnemyREDLow(struct SubCharacter *scp);
#endif
void shCharacterSetWeaponRED(struct SubCharacter *scp, int on_off);
int shCharacterEnemyREDAnimeSet(struct SubCharacter *scp, int anime_id);
int shCharacterEnemyREDAnimeSetP(struct SubCharacter *scp, int anime_id, int comp);
void shGetEnemyREDAttackPos(struct SubCharacter *scp, float *s_pos, float *s_vec, unsigned short atk);

/* Chacter/m3_rpjames.c */
void shCharacterSetHumanRPJMSLow(struct SubCharacter *scp);
void shGetJamesLightPos_Calc_Reverse(void);
void shGetJamesLightPosOriginal_Reverse(float *pos, float *vec);
void PlayerSetReverseMode(void);

/* Chacter/m3_rwep.c */
void shCharacterSetWeaponRLow(struct SubCharacter *scp);

/* Chacter/m3_sc.c */
void SCAddPos(struct SubCharacter *scp, struct FVEC *pos);
void SCSetRot(struct SubCharacter *scp, struct FVEC *rot);
void SCAddRot(struct SubCharacter *scp, struct FVEC *rot);
void shCharacterClusterAnimeSet(struct SubCharacter *scp, int anime);
void SCSetModel(struct SubCharacter *scp, int model, int anime);
void *shCharacterGetAnimeAdrForDrama(struct SubCharacter *scp, int anime_index);
void *shCharacterGetAnimeAdrForPlay(struct SubCharacter *scp);
void *shCharacterGetClusterAnimeAdr(struct SubCharacter *scp);
void shCharacterSetPlayer(struct SubCharacter *scp);
short shCharacterGetModelID(struct SubCharacter *scp);
struct SubCharacter *shCharacterGetSubCharacter(unsigned short kind, short id);
int shCharacterGetSkeltonNum(short kind);
int shCharacterAnimeOneFrameSize(unsigned short id);
void shCharacterInitSubCharacter(void);
struct SubCharacter *shCharacterCreate(unsigned int id, int model, int anime, int clani, int chr_id);
void shCharacterDelete(struct SubCharacter *scp);
void shCharacterPlayingExecAnimeOne(struct SubCharacter *scp);
void shCharacterDramaExecAnimeOne(struct SubCharacter *scp);
void shCharacterAnimeCopyForReverseModel(struct SubCharacter *scp);
void SCNowDemoEventSwitch(struct SubCharacter *scp, int flag);
void SCNowPlayableEventSwitch(struct SubCharacter *scp, int flag);
void SCStayModelSwitch(struct SubCharacter *scp, int flag);
void SCAnimeTypeSwitch(struct SubCharacter *scp, int flag);
void SCRotZYXSwitch(struct SubCharacter *scp, int flag);
void SCFreefallSwitch(struct SubCharacter *scp, int sw);
void SCLightOnNowSwitch(struct SubCharacter *scp, int sw);
void shCharacterExecAnimeAll(void);
void shCharacterUpdateAll(void);
void shCharacterSetFunction(struct SubCharacter *scp, void (*func)(struct SubCharacter *));
void shCharacterExecFunctionAll(void);
void shCharacterAnimeSet(struct SubCharacter *scp, int ctrl_type, int inter_type, struct _AnimeInfo *anim_info, int anime);
void shCharacterStayObjectScaleSet(struct SubCharacter *scp, float scale);
void shCharacterItemScreenObjectSet(struct SubCharacter *scp, struct shItemScreenObjectSettingData *data);
void shCharacterStayObjectNthPartsGet1st(struct SubCharacter *scp, int n, float *pos, float *rot);
void shCharacterStayObjectNthPartsSet(struct SubCharacter *scp, int n, float *pos, float *rot);
short shCharacterAnimeSpeedGet_(struct SubCharacter *scp, unsigned int type);
void shCharacterAnimeSpeedAdd(struct SubCharacter *scp, short add);
void shCharacterAnimeSpeedAdd_(struct SubCharacter *scp, unsigned int type, short add);
void shCharacterAnimeSpeedAddY(struct SubCharacter *scp, short add);
void shCharacterAnimeSpeedAddY_(struct SubCharacter *scp, unsigned int type, short add);
void shCharacterAnimePause(struct SubCharacter *scp);
void shCharacterAnimePause_(struct SubCharacter *scp, unsigned int type);
void shCharacterAnimeRestart(struct SubCharacter *scp);
void shCharacterAnimeRestart_(struct SubCharacter *scp, unsigned int type);
int shCharacterAnimeIsEnd(struct SubCharacter *scp);
int shCharacterAnimeIsEnd_(struct SubCharacter *scp, unsigned int type);
short shCharacterAnimeFrameGet(struct SubCharacter *scp);
short shCharacterAnimeFrameGet_(struct SubCharacter *scp, unsigned int type);
void shCharacterAnimeFrameSet(struct SubCharacter *scp, unsigned short frame);
void shCharacterAnimeFrameSet_(struct SubCharacter *scp, unsigned int type, unsigned short frame);
int shCharacterAnimeCounterGet(struct SubCharacter *scp);
int shCharacterAnimeCounterGet_(struct SubCharacter *scp, unsigned int type);
void shCharacterAnimeCounterSet_(struct SubCharacter *scp, unsigned int type, int counter);
struct _AnimeInfo *shCharacterAnimeGetInfo(struct SubCharacter *scp);
struct _AnimeInfo *shCharacterAnimeGetInfo_(struct SubCharacter *scp, int ctrl_type);
void shCharacterPlayerModelToDrama(void);
void shCharacterPlayerModelToPlayable(void);
void shCharacterMariaModelToDrama(void);
void shCharacterMariaModelToPlayable(void);
void shCharacterSetPosAfterDemo(struct SubCharacter *scp, float *pos, float roty);
void shCharacterGetPartsMatrixForShadow(float (*mat)[4], unsigned short kind, unsigned short id, unsigned int parts_name);
void shCharacterGetGroundInfoForShadow(float *pos, float *normal, float *height, unsigned short kind, unsigned short id);

/* Chacter/m3_scu.c */
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetEnemySCULow
void shCharacterSetEnemySCULow(struct SubCharacter *scp);
#endif
int shCharacterEnemySCUAnimeSet(struct SubCharacter *scp, int anime_id);
int shCharacterEnemySCUAnimeSetP(struct SubCharacter *scp, int anime_id, int comp);
void shGetEnemySCUAttackPos(struct SubCharacter *scp, float *s_pos, float *s_vec, unsigned short atk);
void shEnemySCU_EffectFoot(struct SubCharacter *scp, int type);

/* Chacter/m3_ty23.c */
void shCharacterSetEnemyTY23Low(struct SubCharacter *scp);

/* Chacter/m3_tyu.c */
/* Chacter/m3_sc.c declares it itself: called without a prototype. */
#ifndef SH2_LOCAL_shCharacterSetEnemyTYULow
void shCharacterSetEnemyTYULow(struct SubCharacter *scp);
#endif
int shCharacterEnemyTYUAnimeSetP(struct SubCharacter *scp, int anime_id, int comp);
void shGetEnemyTYUAttackPos(struct SubCharacter *scp, float *s_pos, float *s_vec, unsigned short atk);

/* Chacter/m3_wep.c */
void shUpdateWeaponMatrixAfterAnime(struct SubCharacter *this, short kind);
void shGetJamesWeaponStartPos(float *pos, float *vec);
void shGetJamesWeaponEndPos(float *pos, float *vec);
void shCharacterSetWeaponLow(struct SubCharacter *scp);

/* Chacter/player_result.c */
void GameTimerCountUp(void);
void GameMoveDistanceCountUp(struct SubCharacter *scp, int status);
void GameKillEnemyCountUp(unsigned short atk);
void GameBoatTimerCountUp(void);
void GameBoatMaxSpeedCheck(float spd);
void GameItemGetCountUp(void);
void GameJamesDamagedCountUp(float damage);
/* Chacter/m3_maria_sub.c declares it itself: called without a prototype (the float damage goes as a double). */
#ifndef SH2_LOCAL_GameMariaDamagedCountUp
void GameMariaDamagedCountUp(unsigned short atk, float damage);
#endif
unsigned int GameCalcRankSaveCount(void);
unsigned int GameCalcRankEndingKind(void);
unsigned int GameCalcRankBattleLevel(void);
unsigned int GameCalcRankRiddleLevel(void);
unsigned int GameCalcRankItemGet(void);
unsigned int GameCalcRankHiddenItemGet(void);
unsigned int GameCalcRankKillByShot(void);
unsigned int GameCalcRankKillByFight(void);
unsigned int GameCalcRankClearTime(void);
unsigned int GameCalcRankBoatClearTime(void);
unsigned int GameCalcRankJamesDamage(void);
unsigned int GameCalcRankTotal(void);
void GameSavePreviousTotalRank(void);
void GameSaveSprayPower(void);

/* Chacter/sh2_character_manage.c */
int shCharacter_Manage_Init(void);
int shCharacter_Manage_Create(short kind, short id, float *pos, float *rot, unsigned int status);
int shCharacter_Manage_Delete(struct SubCharacter *scp, short kind, short id);
struct SubCharacter *shCharacter_Manage_GetCharacterList(void);
int shCharacter_Manage_SetDataAdresss(struct SubCharacter *scp);
void shCharacter_Manage_SetJamesAnimeAdresss(struct SubCharacter *scp, unsigned int address);
int shCharacter_Manage_Create_After_MC_Load(struct _Character_Info *chara);

/* Chacter/sh_character_battle.c */
void shGetHumanAttackSprayPos(int i, float *s_pos, float *s_vec, float *result);
void shBattleAttackHitCheckInit(struct SubCharacter *scp);
void shBattleAttackHitCheckToEnemy(struct SubCharacter *scp, unsigned char wep_no, unsigned short atk_no);
void shBattleAttackHitCheckToHuman(struct SubCharacter *scp, unsigned short atk_no);
int shBattleRequestNextAttackIsOk(unsigned short atk, unsigned short frame);
void shBattleGetResult(struct SubCharacter *scp);
void shBattleInitAttackQueue(void);
void shBattleExecAttackQueue(void);
float shBattleGetJamesHP(void);
float shBattleGetJamesHP_Rate(void);
void shBattleSetJamesDamage(unsigned short id, float damage, float *vec);
float shBattleEventWallHitCheck(void);
int shBattleCheckAttackByEnemy(void);

/* Chacter/sh_character_status.c */
void shBattleCheckTargetMyArea(struct shInArea *in_area, struct SubCharacter *scp, struct SubCharacter *tgt, float *look, float *feel);
int shBattleAroundTargetEnemy(void);
int shBattleCheckTargetChara(struct SubCharacter *scp);
struct SubCharacter *shBattleGetTargetEnemy(struct SubCharacter *scp);
struct SubCharacter *shBattleChangeTargetEnemy(struct SubCharacter *scp, int key);
unsigned int shBattleGetTargetChara(struct SubCharacter *scp, int kind);
struct SubCharacter *shCameraGetNearTarget(int i, int type);
struct SubCharacter *shBattleGetNearDeadlyTargetEnemy(struct SubCharacter *scp);
struct SubCharacter *shBattleGetTargetHuman(struct SubCharacter *scp, unsigned int type);
int shBattleListenHumanSound(struct SubCharacter *scp, struct SubCharacter *tgt);
int shBattleSeeHumanLight(struct SubCharacter *scp);
int shBattleAimedByHuman(struct SubCharacter *scp);
int shBattleFinishedByHuman(struct SubCharacter *scp);
int shBattleNoDamageHuman(void);
int shBattleNoDamageHumanJames(void);
int shBattleNoDamageHumanMaria(void);
int shBattleHuggedHuman(void);
void shBattleSetLookArea(struct SubCharacter *scp, float center, float radius);
void shBattleSetFeelArea(struct SubCharacter *scp, float center, float radius);
void shBattleInitEnemyCheckWork(void);
void shBattleInit(void);
void shBattleExec(void);

/* Chacter/skelton.c */
void shCharacterInitSkeltons(void);
void shCharacterFreeSkeltons(struct shSkelton *top);
struct shSkelton *shCharacterGetSkeletons(int n, unsigned char *hrc);

#endif
