/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Chacter_Draw/, by unit, in the order of their code. */
#ifndef SH2_API_CHACTER_DRAW_H
#define SH2_API_CHACTER_DRAW_H

#include "sh2/types.h"

/* Chacter_Draw/clani.c */
void shCharacterInitCluster(void);
struct shClusterAnime *ClusterAnimeNew(int n_clusters, int index);
void ClusterAnimeDelete(struct shClusterAnime *cap, int index);
void ClusterAnimeSet(struct shClusterAnime *cap, void *data);
/* Chacter/m3_sc.c declares it itself: called without a prototype, with an extra argument. */
#ifndef SH2_LOCAL_ClusterAnimeExec
void ClusterAnimeExec(struct shClusterAnime *cap, struct shAnime3d *ap);
#endif
float *ClusterAnimeGetWeights(struct shClusterAnime *cap, float *weights);

/* Chacter_Draw/light_n.c */
float ktClampFloat(float x, float l, float h);
struct Light *LightPointer(int n);
void LightDelete(int n);
void LightDeleteAll(void);
void LightSetParallel(int n, float *dir, float *color);
void LightSetPoint(int n, float *pos, float *color, float f_start, float f_end);
void LightSetFakePoint(int n, float *pos, float *color, float f_start, float f_end);
void LightSetFakeSpot(int n, float *pos, float *dir, float *color, float f_start, float f_end, float s_start, float s_end);
void sh_Set_DrawEnvLightData(int n, void *ded);
void sh_Kari_LightSetSpot(int n, float *pos, float *dir, float *color, float *sv);
void LightSetReflection(int n, float *dir, float *color);
void LightSetPos(int n, float *pos);
void LightSetDir(int n, float *dir);
void LightSetColor(int n, float *color);
void LightSetFalloff(int n, float f_start, float f_end);
void LightSetSpread(int n, float s_start, float s_end);
void UpdateViewParams(void);
void UpdateParallels(void);
void UpdateReflections(void);
void LightUpdateInfoByScene(void);
void LightUpdateInfoByPos(float *center, float radius);
int LightNValidParallelMatrices(void);
void LightGetNthViewNLM(float (*nlm)[4], int n);
void LightGetNthLCM(float (*lcm)[4], int n);
float LightReflectionBrightness(void);
void LightGetReflectionColor(float *color);
float *LightReflectionColor(void);
void LightGetNthViewNHM(float (*nhm)[4], int n);
int LightNValidExtras(void);
struct Light *LightNthValidExtra(int n);

/* Chacter_Draw/model3_cluster_n.c */
void Model3UpdateClusters(struct Model *model, struct ModelWork *work);

/* Chacter_Draw/model3_equip_n.c */
int Model3WorkEquipmentFlag(void *work_, int id);
void Model3WorkSetEquipmentFlagMulti(void *work_, u_long128 mask, u_long128 flag);
int sh2gfw_Set_JMSequip(void *scp, int lhand, int rhand, int spotlight);

/* Chacter_Draw/model3_n.c */
int Model3NSkeletons(void *model_);
signed char *Model3SkeletonStructure(void *model_);
int Model3NClusters(void *model_);
void Model3DrawPre(void);
void sh2_Model_MakeMatrixParams(void);
void Model3Draw_n(void *scp_d_, void *model_, void *work_, float (*mwm)[4], float (*ws_mat)[4], int flag);
int Model3WorkSize(void *model_);
void Model3InitWork(void *model_, void *work_);
float (*Model3WorkMatrices(void *work_))[4][4];
float *Model3WorkClusterWeights(void *work_);

/* Chacter_Draw/model3_sub_n.c */
void Model3Init(void);
void sh2_Model3UpdateTextures(struct sh_Model *model);
void Model3UpdateMatrices(struct Model *model, struct ModelWork *work, float (*mwm)[4], int model_type);
void Model3UpdateEnvelopeMatrices(struct Model *model);
void Model3UpdateLightEnv(void);
void Model3UpdateGlobalAmbient(void);

/* Chacter_Draw/model3_vu0_n.c */
void Model3DrawVu0Parts(struct Model *model, struct ModelWork *work);

/* Chacter_Draw/model3_vu1_n.c */
void Model3LoadMpg1(void);
void Model3DrawVu1Parts(struct Model *model, struct ModelWork *work);

/* Chacter_Draw/model_common.c */
void ModelCommonWorkInit(void);
void ModelCommonWorkFlip(void);

/* Chacter_Draw/model_n.c */
void ModelInit(void);
void ModelDrawPost(void);

/* Chacter_Draw/sh2_JmsSpot_Man.c */
void sh2gfw_ALLInit_SpotMan(void);
void sh2gfw_Propagate_JmsGunLight(void);
void sh2gfw_Set_JmsGunLight(void);
float sh2gfw_Get_JmsGunLight(void);
float sh2gfw_Get_GunLight(void);
void sh2gfw_Clear_MicroChange(void);
void sh2gfw_Set_MicroChange(void);
void sh2gfw_Change_MicroFLGS(void);
int sh2gfw_Check_MicroCode(void);
void sh2gfw_Set_MicroCode(int xx);
float sh2gfw_Get_DarkTrimFactor(void);
int sh2gfw_Check_JmsSpotOnOff(void);
void sh2gfw_On_JmsSPOT(void);
void sh2gfw_Off_JmsSPOT(void);
void sh2gfw_ForceOff_JmsSPOT(void);
void sh2gfw_ForceOn_JmsSPOT(void);
void Programed_Light_Set(void);

/* Chacter_Draw/sh2gfw_CharacterOT.c */
void sh2gfw_AllInit_CharacterOT(void);
void sh2gfw_Init_CharacterOT(void);
struct ktVif1Ot2 *CharacterOt_KtVif1Ot2(void);
u_long128 *CharacterOt_RequestPacket(int qwc);
void CharacterOt_Append(unsigned int depth, u_long128 *packet);
int CharacterOt_IsEmpty(void);
void CharacterOt_ExecPre(void);
int CharacterOt_ExecPost(void);

/* Chacter_Draw/sh2gfw_Draw_Character.c */
void sh2gfw_set_d1cid(void);
void sh2gfw_sync_d1cid(void);
void sh2gfw_Exec_AnimeAndCollision(void);
void sh2gfw_Exec_Character_Draw(float (*wld_scr)[4], int comm);
void sh2gfw_Exec_Character_Draw_ShadowOnly(void);
int sh2_Model_SyncOT(void *pktop);
int sh2_Model_DummySyncOT(void);
int sh2gfw_get_ModelChangeTB(int texno);
int sh2gfw_get_ModelIndexTB(int texno);
void sh2gfw_Thr_Chracter_d1d2SyncKick(void *pktop, int index);
int sh2gfw_get_Charaid(void);
int sh2gfw_get_TBChangeVU1num(void);
void sh2gfw_set_CharaD1CID(int cid);
void sh2gfw_SetNoise_CharaTexture(int charaid);
void sh2gfw_RemoveNoise_CharaTexture(int charaid);

/* Chacter_Draw/sh2gfw_md_spclmapping.c */
unsigned long sh2_SpecularMappingTEX0(void);
void mdl_SpecularMappingMakeTexture(int *texbuf);
void mdl_SpecularMappingLoadTexture(void);

/* Chacter_Draw/sh2gfw_model_light.c */
int sh2gfw_Check_CharaDarkOrBright(void *SubChara);
void sh2gfw_Store_ShadowParallelLight(void *pald, int pnum);
void sh2gfw_Store_ShadowLight(void *pl);
int sh2gfw_Get_ShadowLight(int mode, float *pos, float *dir, float *svt, void *pScp);
int sh2gfw_Get_ShadowLightKind(void);
void *sh2gfw_Get_ShadowLightPointer(void);
void Draw_Jms_Shadow(int mode, void *pm, struct SubCharacter *scp);
void sh2gfw_clear_LightChr(void);
int sh2gfw_check_LightChr(int cid);
int sh2gfw_change_lights(void *pmh);
void sh2gfw_set_CommonCharacterLight(void);

/* Chacter_Draw/sh_kt_vu0.c */
void ktVu0ApplyMatrixXYZ1(float *v0, float (*m0)[4], float *v1);
void ktVu0ApplyMatrixXYZ0(float *v0, float (*m0)[4], float *v1);
void ktVu0FTOI4VectorXYZ(int *v0, float *v1);

#endif
