/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Collision/, by unit, in the order of their code. */
#ifndef SH2_API_COLLISION_H
#define SH2_API_COLLISION_H

#include "sh2/types.h"

/* Collision/cl_calc.c */
void clCalcPlaneEquation(struct _CL_HITPOLY_PLANE *pl, float *pparam);

/* Collision/cl_calc2.c */
int clCheckSubLineToPlane(struct _CL_HITRESULT *result, float (*line0)[4], float (*line1)[4], float (*plane0)[4], float (*plane1)[4], float (*plane2)[4], float (*plane3)[4]);
int clCheckSubLineToPlane3(struct _CL_HITRESULT *result, float (*line0)[4], float (*line1)[4], float (*plane0)[4], float (*plane1)[4], float (*plane2)[4]);
int clCheckSubLineToColumnPlus(struct _CL_HITRESULT *result, float (*line0)[4], float (*line1)[4], float (*column)[4]);
int clCheckSubWallToColumn(struct _CL_HITRESULT *result, float (*wall0)[4], float (*wall1)[4], float (*column)[4]);
int clCheckSubColumnToColumn(struct _CL_HITRESULT *result, float (*clm0)[4], float (*clm1)[4]);

/* Collision/cl_main.c */
void clAllInitCollisionData(void);
void clFrameInitCollisionData(void);
void clCollectCharaPosition(void);
void clSetCharaHitColumn(struct _CL_HITPOLY_COLUMN *col, struct _CL_HITPOLY_COLUMN *wcol, struct SubCharacter *sc, void (*func)());
void clAddDynamicWall(struct _CL_HITPOLY_PLANE *pl);
void clAddDynamicFloor(struct _CL_HITPOLY_PLANE *pl);
void clBattleAddQue(struct _CL_BATTLE_QUE *que);
struct _CL_BATTLE_RESULT *clBattleGetResult(unsigned int id, struct _CL_BATTLE_RESULT *before);
void clBattleCheckExec(void);
struct _CL_SELECT_MAP *clGetHitSectListVECHIT(float *st, float *ed);
int clCheckCrossLine2BoxXZ(float (*box)[4], float *st, float *ed);
int clCheckCrossLine2LineXZ(float *va0, float *va1, float *vb0, float *vb1);
struct _CL_SELECT_MAP *clGetHitSectListMOVE(float *bpos);
void clCheckHitEyes(struct _CL_VHIT_RESULT *res, unsigned int id, float *st, float *ed, int thru);
void clCheckHitEyesOnlyFloor(struct _CL_VHIT_RESULT *res, struct SubCharacter *scp, float *sp, float *ep);
void clCheckHitEyesOnlyFloorThru(struct _CL_VHIT_RESULT *res, struct SubCharacter *scp, float *sp, float *ep);
void clCheckHitEyesOnlyWall(struct _CL_VHIT_RESULT *res, float *sp, float *ep);
void clCheckHitEyesOnlyFloorCeil(struct _CL_VHIT_RESULT *res, float *sp, float *ep);
int clPermitColumnExpansion(void);

/* Collision/kari_atari_allinit.c */
void kari_init_colidata(void);

#endif
