/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/DBG/, by unit, in the order of their code. */
#ifndef SH2_API_DBG_H
#define SH2_API_DBG_H

#include "sh2/types.h"

/* DBG/dbalocate.c */
void *dbAllocatePrintf(int require_size);

/* DBG/dbflag.c */
int dbFlagReserve(unsigned int flag, char *explain_message);
unsigned int dbFlag(unsigned int flag);
void dbFlagSet(unsigned int flag);

/* DBG/dbflow.c */
void ___dbFlowSetCheckPoint(char *check_point);
int dbFlowCheck(void);
void dbFlowStartCheck(int enable);
void dbFlowCheckSleepTime(int flow_ok);

/* DBG/dbfntprint.c */
void dbfntlocate(int x, int y);
void dbfntlocateR(int x, int y);
void dbfntprint(char *buf);
void dbfntprintR(char *buf);
int dbfntprintf(char *fmt, ...);
int dbfntprintfR(char *fmt, ...);

/* DBG/dbfreeze.c */
void dbFreeze(void);

/* DBG/dbkernel.c */
void dbScrPrintThreAll(void);

/* DBG/dbsw_all.c */
void dbSwitchAllInit(int enable);
int dbSwitchIsVisible(void);
void dbSwitchAllPrint(void);

/* DBG/dbsw_map.c */
char *dbSwitchMapHelp(int Y);
void dbSwitchMapPrint(void);
void dbSwitchMapInit(void);

/* DBG/dbsw_sys.c */
char *dbSwitchSysHelp(int Y);
void dbSwitchSysPrint(void);
int dbSwitchSysPrintHelp(void);
int dbSwitchSysPadPort(void);
int dbSwitchSysPrintAllPages(void);
int dbSwitchSysPrintNotOnlyPort1(void);
void dbSwitchSysInit(void);

/* DBG/dbswitch.c */
void dbSwitchDispIndicator(int enable, int o, int x, int dx, int dy);
int dbSwitchDispEnable(int enable);
int dbSwitchInit(enum DBSW_ID _X, unsigned long bit_pattern);
int dbSwitchSet(enum DBSW_ID _X, int Y, int set);
int dbSwitch(enum DBSW_ID _X, int Y);
int dbSwitchGetPos(int *Xp, int *Yp);

/* DBG/sh2gfw_SyncDBG.c */
void sh2gfw_Init_AllVertCounter(void);
void sh2gfw_Incliment_VertNumIndices(void);
void sh2gfw_Add_SemiTransVertNum(int num);
void sh2gfw_Add_VertexNum(int num);
void sh2gfw_init_Perf(void);
int sh2gfw_Store_Perf2(int count, int md);

/* DBG/shDBG_fontHandle.c */
void shDBG_font_init(void);
void shDBG_InitFontEnv(void);
void _shDBG_print_string(char *st, int ix, int iy);
void shDBG_print_string(char *st, int ix, int iy);

/* DBG/verbose.c */
int verbose(int level, char *format, ...);

#endif
