/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/DS_Pad/, by unit, in the order of their code. */
#ifndef SH2_API_DS_PAD_H
#define SH2_API_DS_PAD_H

#include "sh2/types.h"

/* DS_Pad/ds_sequencer.c */
unsigned int DSR_Entry0(void *pAddress, unsigned int ControllerID, float Ratio);
void DSR_Sequencer_Initialize(void);
void DSR_Sequencer(void);
void DSR_Sequence_Different_Time_Set(float Different_Time);

/* DS_Pad/dss_wrapper.c */
float DSS_Wrapper_AllVibrationRatio_Get(void);
int DSS_Wrapper_ActuaterData_Send(unsigned int ControllerID, unsigned int ActuaterType, unsigned int ActuaterLV);
int DSS_Wrapper_AllActuaterData_RealSend_to_Peripheral(void);
void DSS_Wrapper_DualShock2_Sequencer(void);
unsigned int DSS_Wrapper_DualShock2_Send_ActuaterLV_Get(unsigned int ControllerID, unsigned int ActuaterType);
void DSS_Wrapper_DualShock2_Send_ActuaterLV_Claer(unsigned int ControllerID, unsigned int ActuaterType);

#endif
