/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Effect/, by unit, in the order of their code. */
#ifndef SH2_API_EFFECT_H
#define SH2_API_EFFECT_H

#include "sh2/types.h"

/* Effect/ef_broken_glass.c */
int InitEffectObjectBrokenGlass(struct EFCTObject *pObj, int nIndex, float *parent_pos, float *parent_direction, float (*chara_info)[4]);
void DrawBrokenGlass(void *task);
void InitBrokenGlassTexEnv(struct EFCTTexEnvInfo *pTexInfo);
int GetBrokenGlassEffectLayerNum(void);

/* Effect/ef_cartridge.c */
void EFCTSetDischargeCartridge(int kind);
void EFCTSetDischargeCartridgeEddie(float *pos);
void EFCTCartridgeDischarge(struct _shTskTASK *ptr);

/* Effect/ef_common.c */
void EFCTInit(void);
void EFCTDoTask(void);
void EFCTKickPacket(void);
void EFCTSetGunFire(float *Pos, float *vec);
void EFCTSetGunFireEddie(float *Pos, float *vec);
void EFCTSetGunSmoke(float *Pos);
void EFCTSetDramaDemoAngelaPapa(void);
void EFCTSetBrokenGlass(float *parent_pos, float *parent_direction, float (*chara_pos)[4]);
void EFCTSetSmoke(float *pos, unsigned char kind);
void EFCTCutEffectTask(struct EFCTTask *ptr);
int InitEffectAnimData(unsigned short TotalFrame, float DrawFrameWait, short StartFrame, struct EFCTAnimationData **pAnim);
unsigned int InitEffectVertexSprite(float *Pos, float width, float height, unsigned short PlaneKind, struct EFCTVertexData **pVertex, float *rot, unsigned char *rgba);
void SetEffectVertexSpriteXY(float width, float height, struct EFCTVertexData *VertexData);
void SetEffectVertexSpriteXZ(float width, float height, struct EFCTVertexData *VertexData);
void SpriteLocalRot(struct EFCTVertexData *pVertex, int num, float *rot);
int EFCTNextFrame(struct EFCTObject *pObj, int DoLoop);
void EFCTThreeDWork(struct EFCTObject *pObj);
void EFCTTinyThreeDWork(struct EFCTObject *pObj);
void DrawPrimitive(struct EFCTObject *pObj);
void EFCTDeleteTask(short Kind);
float GetSpriteRotAngle(float around_rot, unsigned int plane_num, unsigned int index, int rand_rot_range);
void ClipEffectObject(struct EFCTObject *pObj);
void ClipEffectObject2(struct EFCTObject *pObj);
int EFCTClipVertex(int *vec);
void EFCTResetRGBA(int *rgba, struct EFCTVertexData *pVertex);
void EFCTSetPassingTimePerFrame(float time);
float EFCTGetPassingTimePerFrame(void);
void CalibrationZValue(unsigned int vertex_num, int z, struct EFCTVertexData *pVertex);

/* Effect/ef_flame.c */
void DrawFlame(void *task);
void InitFlameTexEnv(struct EFCTTexEnvInfo *pTexInfo);
unsigned short GetFlameEffectLayerNum(void);
void EFCTFlameChangeCamera(void);

/* Effect/ef_malloc.c */
void *EfctInitHeap(void *buf, unsigned int size);
void *EfctMalloc(unsigned int n);
void EfctFree(void *p);

/* Effect/ef_packet.c */
struct sceVif1Packet *shEfctPkInit(void *packet);
struct sceVif1Packet *shEfctPkReset(void);
struct sceVif1Packet *shEfctPkTaskHead(void);
struct sceVif1Packet *shEfctPkTaskTail(void);
void *shEfctPkGetKickAddrByd1cSend(void);

/* Effect/ef_rain.c */
int EFCTSetRainDrop(int lev);
void EFCTDelRainDrop(void);
void EFCTRainDropMain(struct _shTskTASK *ptr);

/* Effect/ef_smoke.c */
int InitEffectObjectSmoke(struct EFCTObject *pObj, int nIndex, float *pos, unsigned char kind);
void InitSmokeTexEnv(struct EFCTTexEnvInfo *pTexInfo);
void DrawSmoke(void *task);
void SetFlameSmokeValid(int index, int valid);

/* Effect/ef_sparks.c */
void DrawSparks(struct EFCTSparksObject *sparks);

/* Effect/ef_stage.c */
int InitEffectObjectGunFire(struct EFCTObject *pObj, int nIndex, float *Pos, float *vec, int wep_kind, unsigned char light_status);
int InitEffectObjectGunSmoke(struct EFCTObject *pObj, int nIndex, float *Pos, int wep_kind, unsigned char light_status);
void DrawBloodSpray(void *task);
void DrawBloodDrop(void *task);
void DrawBloodPool(void *task);
void DrawGunFire(void *task);
void DrawGunSmoke(void *task);
unsigned short GetStageEffectLayerNum(short EffectKind);
void InitBloodTexEnv(struct EFCTTexEnvInfo *pTexInfo);
void InitGunFireTexEnv(struct EFCTTexEnvInfo *pTexInfo);
void InitGunSmokeTexEnv(struct EFCTTexEnvInfo *pTexInfo);

/* Effect/screen_effect.c */
void ScreenEffectInit(void);
void ScreenEffectManager(void);
void ScreenEffectFadeStart(int type, float time);
int ScreenEffectFadeCheck(void);
void ScreenEffectFadeStop(void);

#endif
