/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Effect2/, by unit, in the order of their code. */
#ifndef SH2_API_EFFECT2_H
#define SH2_API_EFFECT2_H

#include "sh2/types.h"

/* Effect2/hh_class_blood_00.c */
unsigned int HH_Class_Prefix_Blood_00(void);
unsigned int HH_Class_Suffix_Blood_00(void);
unsigned int HH_Class_Blood_00(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_blood_01.c */
unsigned int HH_Class_Prefix_Blood_01(void);
unsigned int HH_Class_Suffix_Blood_01(void);
unsigned int HH_Class_Blood_01(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_blood_02.c */
unsigned int HH_Class_Prefix_Blood_02(void);
unsigned int HH_Class_Suffix_Blood_02(void);
unsigned int HH_Class_Blood_02(void *pBlock, struct ImpactQueue_Element *pElement);
unsigned int HH_Class_Blood_02_DesignateLocation_CollisionCheck(void *pBlock, struct ImpactQueue_Element *pElement, float *Target_Location);

/* Effect2/hh_class_blood_03.c */
unsigned int HH_Class_Prefix_Blood_03(void);
unsigned int HH_Class_Suffix_Blood_03(void);
unsigned int HH_Class_Blood_03(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_blood_04.c */
unsigned int HH_Class_Prefix_Blood_04(void);
unsigned int HH_Class_Suffix_Blood_04(void);
unsigned int HH_Class_Blood_04(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_blood_05.c */
unsigned int HH_Class_Prefix_Blood_05(void);
unsigned int HH_Class_Suffix_Blood_05(void);
unsigned int HH_Class_Blood_05(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_blood_footmark_00.c */
unsigned int HH_Class_Prefix_Blood_FootMark_00(void);
unsigned int HH_Class_Suffix_Blood_FootMark_00(void);
unsigned int HH_Class_Blood_FootMark_00(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_blood_pool_phenomenon_00.c */
unsigned int HH_Class_Blood_Pool_Phenomenon_00(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_blood_pool_phenomenon_01.c */
unsigned int HH_Class_Blood_Pool_Phenomenon_01(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_blood_splash_phenomenon_00.c */
unsigned int HH_Class_Blood_Splash_Phenomenon_00(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_blood_splash_phenomenon_01.c */
unsigned int HH_Class_Blood_Splash_Phenomenon_01(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_blood_splash_phenomenon_02.c */
unsigned int HH_Class_Blood_Splash_Phenomenon_02(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_blood_stick_00.c */
unsigned int HH_Class_Blood_Stick_00(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_boatmask.c */
unsigned int HH_Class_Prefix_Boat_Mask(void);
unsigned int HH_Class_Suffix_Boat_Mask(void);
unsigned int HH_Class_Boat_Mask(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_dust_00.c */
unsigned int HH_Class_Prefix_Dust_00(void);
unsigned int HH_Class_Suffix_Dust_00(void);
unsigned int HH_Class_Dust_00(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_fire_phenomenon_00.c */
unsigned int HH_Class_Fire_Phenomenon_00(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_flame_00.c */
unsigned int HH_Class_Prefix_Flame_00(void);
unsigned int HH_Class_Suffix_Flame_00(void);
unsigned int HH_Class_Flame_00(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_flame_01.c */
unsigned int HH_Class_Prefix_Flame_01(void);
unsigned int HH_Class_Suffix_Flame_01(void);
unsigned int HH_Class_Flame_01(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_flame_02.c */
unsigned int HH_Class_Prefix_Flame_02(void);
unsigned int HH_Class_Suffix_Flame_02(void);
unsigned int HH_Class_Flame_02(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_flame_03.c */
unsigned int HH_Class_Prefix_Flame_03(void);
unsigned int HH_Class_Suffix_Flame_03(void);
unsigned int HH_Class_Flame_03(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_glass_break_phenomenon_00.c */
unsigned int HH_Class_Glass_Break_Phenomenon_00(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_glass_piece_00.c */
unsigned int HH_Class_Prefix_GlassPiece_00(void);
unsigned int HH_Class_Suffix_GlassPiece_00(void);
unsigned int HH_Class_GlassPiece_00(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_manager.c */
unsigned int ImpactDescriptor_Post(struct Object_Group_Infomeation *pInfo, struct ImpactQueue_Element *pDescriptor);
unsigned int Object_Group_Manager(struct Object_Group_Infomeation *pInfo);
unsigned int Object_Group_Infomeation_Set(struct Object_Group_Infomeation *pInfo);
unsigned int Object_Group_QueueInfomeation_Set(struct Object_Group_Infomeation *pInfo, struct ImpactQueue_Element *pElement_Base, unsigned int Length_Max);
unsigned int Object_Group_ClassAssociationInfomeation_Set(struct Object_Group_Infomeation *pInfo, struct Object_Class *pClass_List, struct Object_DataPool_Infomeation *pPool_Info_Base, unsigned int *pClass_Priority_List, unsigned int Class_Max);
unsigned int Object_Group_InstanceTableInfomeation_Set(struct Object_Group_Infomeation *pInfo, struct Object_Instance *pInstance_Base, struct Object_Instance **pInstance_HierarchyTable, unsigned int Instance_Max);
unsigned int Object_Group_All_Initialize(struct Object_Group_Infomeation *pInfo);
unsigned int Object_Group_InstanceTable_DesignateClassDescriptorAttach_Initialize(struct Object_Group_Infomeation *pInfo, unsigned int Class_Descriptor);
unsigned int Object_Group_InstanceTable_DesignateInstanceHandleAttach_Initialize(struct Object_Group_Infomeation *pInfo, unsigned int hInstance);
unsigned int ObjectInstance_DesignateClassDescriptorAttach_Count(struct Object_Group_Infomeation *pInfo, unsigned int Class_Descriptor);
unsigned int ObjectInstanceHandle_Get_from_ClassDescriptor_and_AttachCount(struct Object_Group_Infomeation *pInfo, unsigned int Class_Descriptor, unsigned int CountIndex);
struct ImpactQueue_Element *ObjectInstance_Element_Get(struct Object_Group_Infomeation *pInfo, unsigned int hInstance);
void *ObjectInstance_DataBlock_Get(struct Object_Group_Infomeation *pInfo, unsigned int hInstance);

/* Effect2/hh_class_object_execute.c */
void HH_Class_Object_Initialize(void);
void HH_Class_Object_Execute(void);
void HH_Class_Object_Packet_Kick(void);
void HH_Effect_Object_Blood_Pool_Impact_Post(float *Location, int kind);
void HH_Effect_Object_Blood_Splash_Impact_Post(float *Location, float *Direction, unsigned int Scp_Address, unsigned int Impact_Kind);
void HH_Effect_Object_Ground_Impact_Post(float *Toe, float *Heel, unsigned int Foot_Kind, unsigned int Character_ID);
void HH_Effect_Object_Ground_Impact_Post_forEnemy(float *Foot_Location, unsigned int Foot_Kind);
void HH_Effect_Object_WaterSplash_Impact_Post(float *Location, int kind);

/* Effect2/hh_class_plural_phenomenon_00.c */
unsigned int HH_Class_Plural_Phenomenon_00(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_plural_phenomenon_01.c */
unsigned int HH_Class_Plural_Phenomenon_01(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_raise_dust_phenomenon_00.c */
unsigned int HH_Class_Raise_Dust_Phenomenon_00(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_smoke_00.c */
unsigned int HH_Class_Prefix_Smoke_00(void);
unsigned int HH_Class_Suffix_Smoke_00(void);
unsigned int HH_Class_Smoke_00(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_water_00.c */
unsigned int HH_Class_Prefix_Water_00(void);
unsigned int HH_Class_Suffix_Water_00(void);
unsigned int HH_Class_Water_00(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_water_01.c */
unsigned int HH_Class_Prefix_Water_01(void);
unsigned int HH_Class_Suffix_Water_01(void);
unsigned int HH_Class_Water_01(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_water_02.c */
unsigned int HH_Class_Prefix_Water_02(void);
unsigned int HH_Class_Suffix_Water_02(void);
unsigned int HH_Class_Water_02(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_water_03.c */
unsigned int HH_Class_Prefix_Water_03(void);
unsigned int HH_Class_Suffix_Water_03(void);
unsigned int HH_Class_Water_03(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_water_04.c */
unsigned int HH_Class_Prefix_Water_04(void);
unsigned int HH_Class_Suffix_Water_04(void);
unsigned int HH_Class_Water_04(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_water_06.c */
unsigned int HH_Class_Prefix_Water_06(void);
unsigned int HH_Class_Suffix_Water_06(void);
unsigned int HH_Class_Water_06(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_water_07.c */
unsigned int HH_Class_Prefix_Water_07(void);
unsigned int HH_Class_Suffix_Water_07(void);
unsigned int HH_Class_Water_07(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_water_08.c */
unsigned int HH_Class_Prefix_Water_08(void);
unsigned int HH_Class_Suffix_Water_08(void);
unsigned int HH_Class_Water_08(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_water_09.c */
unsigned int HH_Class_Prefix_Water_09(void);
unsigned int HH_Class_Suffix_Water_09(void);
unsigned int HH_Class_Water_09(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_water_10.c */
unsigned int HH_Class_Prefix_Water_10(void);
unsigned int HH_Class_Suffix_Water_10(void);
unsigned int HH_Class_Water_10(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_water_11.c */
unsigned int HH_Class_Prefix_Water_11(void);
unsigned int HH_Class_Suffix_Water_11(void);
unsigned int HH_Class_Water_11(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_water_12.c */
unsigned int HH_Class_Prefix_Water_12(void);
unsigned int HH_Class_Suffix_Water_12(void);
unsigned int HH_Class_Water_12(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_water_13.c */
unsigned int HH_Class_Prefix_Water_13(void);
unsigned int HH_Class_Suffix_Water_13(void);
unsigned int HH_Class_Water_13(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_water_14.c */
unsigned int HH_Class_Prefix_Water_14(void);
unsigned int HH_Class_Suffix_Water_14(void);
unsigned int HH_Class_Water_14(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_water_15.c */
unsigned int HH_Class_Prefix_Water_15(void);
unsigned int HH_Class_Suffix_Water_15(void);
unsigned int HH_Class_Water_15(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_water_20.c */
unsigned int HH_Class_Prefix_Water_20(void);
unsigned int HH_Class_Suffix_Water_20(void);
unsigned int HH_Class_Water_20(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_water_30.c */
unsigned int HH_Class_Prefix_Water_30(void);
unsigned int HH_Class_Suffix_Water_30(void);
unsigned int HH_Class_Water_30(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_water_80.c */
unsigned int HH_Class_Prefix_Water_80(void);
unsigned int HH_Class_Suffix_Water_80(void);
unsigned int HH_Class_Water_80(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_water_90.c */
unsigned int HH_Class_Prefix_Water_90(void);
unsigned int HH_Class_Suffix_Water_90(void);
unsigned int HH_Class_Water_90(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_water_common.c */
unsigned int HH_Class_WaterCommon_WaveArea_Calculator(struct WaveArea_Infomeation *pInfo, struct Wave_Element *pElement_Table, unsigned int Element_Max, unsigned int Area_Index);
unsigned int HH_Class_WaterCommon_WaveArea_GridLink_Y_Value_Calculator(struct WaveArea_GridLink_Infomeation *pInfo);
int HH_Class_WaterCommon_WaveArea_CurrentArea_Search(float *Position, struct WaveArea_Infomeation *pInfo_Table, unsigned int Table_Max);
unsigned int HH_Class_WaterCommon_WaveElement_Addition(struct Wave_Element *pElement_Table, unsigned int Element_Max, struct Wave_Element *pAdd_Element);
void HH_Class_WaterCommon_WaveElement_Time_Count(struct Wave_Element *pElement_Table, unsigned int Element_Max);
void HH_Class_WaterCommon_Area_Enable_Table_Clear(unsigned int *pArea_Enable_Table, unsigned int Table_Max);
void HH_Class_WaterCommon_Area_Enable_Manager(unsigned int *pArea_Enable_Table, struct WaveArea_Infomeation *pInfo_Table, unsigned int Table_Max, int Current_Area);

/* Effect2/hh_class_water_pool_00.c */
unsigned int HH_Class_Prefix_Water_Pool_00(void);
unsigned int HH_Class_Suffix_Water_Pool_00(void);
unsigned int HH_Class_Water_Pool_00(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_water_splash_phenomenon_00.c */
unsigned int HH_Class_Water_Splash_Phenomenon_00(void *pBlock, struct ImpactQueue_Element *pElement);

/* Effect2/hh_class_wrapper.c */
unsigned int HH_ClassWrapper_RotTrans_PerspectiveProjection_Clip(int *Dst_iVector, float *pReverse_W, float (*LocalScreen_Matrix)[4], float (*LocalScreen_ClipMatrix)[4], float *Src_fVector);
void HH_ClassWrapper_Transform_PerspectiveProjection_Clip_forTriangleStrip(int *Dst_iVector, float *STQ_fVector, float (*LocalScreen_Matrix)[4], float (*LocalScreen_ClipMatrix)[4], float *Src_fVector);
void HH_ClassWrapper_Transform_PerspectiveProjection_Clip_N(int *Dst_iVector, float *STQ_fVector, float (*LocalScreen_Matrix)[4], float (*LocalScreen_ClipMatrix)[4], float *Src_fVector, unsigned int Clip_Mask);
unsigned int HH_ClassWrapper_Point_Clip_Judge(float (*LocalScreen_ClipMatrix)[4], float (*pSrc_fVector_Array)[4], unsigned int Array_Max);
void HH_ClassWrapper_Matrix_Group_Update(void);
void HH_ClassWrapper_ViewFrustum_Primitive_ClipMatrix_Get(float (*ViewFrustum_Primitive_ClipMatrix)[4]);
void HH_ClassWrapper_ViewFrustum_ClipMatrix_Get(float (*ViewFrustum_Primitive_ClipMatrix)[4]);
void HH_ClassWrapper_AlwaysFront_WorldView_Matrix_Get(float (*AlwaysFront_WorldView_Matrix)[4]);
void HH_ClassWrapper_WorldViewMatrix_Get(float (*WorldView_Matrix)[4]);
void HH_ClassWrapper_ViewScreenMatrix_Get(float (*ViewScreen_Matrix)[4]);
void HH_ClassWrapper_WorldScreenMatrix_Get(float (*WorldScreen_Matrix)[4]);
void HH_ClassWrapper_ViewDirection_Get(float *View_Direction);
void HH_ClassWrapper_LightDirection_Get(float *Light_Direction);
float HH_ClassWrapper_ViewingFrustumParamerter_NearZ_Get(void);
float HH_ClassWrapper_ViewingFrustumParamerter_FarZ_Get(void);
float HH_ClassWrapper_FogParameter_A_Get(void);
float HH_ClassWrapper_FogParameter_B_Get(void);
float HH_ClassWrapper_Float_Clamp(float Src_Value, float Min, float Max);
void HH_ClassWrapper_AmbientColor_Get(float *Ambient_Color);
unsigned int HH_ClassWrapper_SpotLight_Enable_Check(void);
void HH_ClassWrapper_SpotLight_EnvironmentParameter_Get(float *Light_Position, float *Light_Direction, float *Light_Color, float *Parameter);
float HH_ClassWrapper_SpotLight_ColorRatio_Calculator(float *Light_Position, float *Light_Direction, float *Vertex, float Cos_Value, float Far_Z);
float HH_ClassWrapper_SpecularRatio0_Calculator(float *View_Direction, float *Light_Direction, float *Normal_Vector, float Cos_Value);
void HH_ClassWrapper_SpecularRGBA_Add_BaseRGBA(int *iRGBA, float *RGBA_Base, float *Specular_RGBA_Base, float Specular_Ratio);
unsigned int HH_ClassWrapper_MemoryCopy128Align_DesignateCycle(void *pDestination_Address, void *pSource_Address, unsigned int Cycle_Max, unsigned int LoadStore_Size, unsigned int Next_Offset);
u_long128 *HH_ClassWrapper_GS_EnvironmentRegister_Frame_AlphaMask_Get(void);
u_long128 *HH_ClassWrapper_GS_EnvironmentRegister_Frame_NoMask_Get(void);
void HH_ClassWrapper_Packet_ADC_Flag_OnceMore_Set(unsigned int *pPacket_End, unsigned int Mesh_Width, unsigned int Mesh_Height);
unsigned int HH_ClassWrapper_JMS_WorldPosition_Get(float *Position);

/* Effect2/hh_dbg_wrapper.c */
unsigned int HH_DBG_Wrapper_Controller_KeyAssign_Check(unsigned int ControllerID, unsigned int Mode, unsigned int Check_Assign);
void HH_DBG_Wrapper_Printf(unsigned int x, unsigned int y, unsigned char *str);
void HH_DBG_Wrapper_T0_COUNT_Get(void);
void HH_DBG_Wrapper_T0_COUNT_Delta(void);

/* Effect2/hh_effect_object_def.c */
void HH_Effect_Object_Impact_Post(struct ImpactQueue_Element *pElement);
void HH_Effect_Object_DesignateClassInstance_Clear(unsigned int Class_Descriptor);
void HH_Effect_Object_DesignateHandleInstance_Clear(unsigned int hInstance);
struct Object_Group_Infomeation *HH_Effect_Object_Infomeation_Get(void);
void HH_Effect_Object_Manager(void);
unsigned int HH_Effect_Object_MemoryBlock_Allocate(void);
void HH_Effect_Object_AutoPost(void);

/* Effect2/hh_effect_object_texture.c */
void HH_Effect_Object_Texture_TransportPriority_Initialize(void);
void HH_Effect_Object_SPK_Texture_Post(void);
void HH_Effect_Object_Texture_Send(void);
void HH_Effect_Object_Texture_Sync(void);
void HH_Effect_Object_Texture_Finish(void);
unsigned long HH_Effect_Object_Texture_GS_Register_Tex0_Get(unsigned int Texture_ID, unsigned int Clut_ID);
unsigned int HH_Effect_Object_Texture_DesignateEntryLevel_Initialize(unsigned int Entry_Level);
unsigned int HH_Effect_Object_Texture_DesignateEntryLevel_Discard(unsigned int Entry_Level);
unsigned int HH_Effect_Object_Texture_AlwaysTexture_Initialize(void);

/* Effect2/hh_math_wrapper.c */
float HH_MathWrapper_Sqrtf(float Value);
float HH_MathWrapper_Sinf(float x);
float HH_MathWrapper_Cosf(float x);

/* Effect2/hh_memory_manage.c */
unsigned int HH_MemoryManager_AllocateMemoryBlock_Check(unsigned int MemoryBlock_Type);
void *HH_MemoryManager_AllocateMemoryBlock_Get(unsigned int MemoryBlock_Type);
void *HH_MemoryManager_DesignateSize_Alignment16Address_Calculator(void *pAddress, unsigned int Size, unsigned int Number);
void *HH_MemoryManager_DesignateSize_Alignment64Address_Calculator(void *pAddress, unsigned int Size, unsigned int Number);
unsigned int HH_MemoryManager_MemoryBlock_All_Allocate(void);
unsigned int HH_MemoryManager_MemoryBlock_Allocate_Packet_and_ObjectWork(void);
unsigned int HH_MemoryManager_MemoryBlock_Allocate_TextureBuffer(void);
unsigned int HH_MemoryManager_MemoryBlock_All_Discard(void);

/* Effect2/hh_packet.c */
unsigned int HH_Vif1PacketBuffer_Memory_Allocate_Check(void);
struct sceVif1Packet *HH_Vif1Packet_Current_Get(void);
void HH_Vif1PacketBuffer_Initialize(void);
void HH_Vif1PacketBuffer_Prefix_GifTag_Open(void);
void HH_Vif1PacketBuffer_Suffix_GifTag_Open(void);
void HH_Vif1PacketBuffer_GifTag_Open(void);
void HH_Vif1PacketBuffer_GifTag_Close(void);
void HH_Vif1Packet_Send(void);
int HH_Vif1Packet_FreePacketSize_Get(void);
void HH_Vif1Packet_GeneralGifTag_GS_AD_Open(void);
void HH_Vif1Packet_GeneralGifTag_Sprite_Open(void);
void HH_Vif1Packet_GeneralGifTag_TriangleStrip_Open(void);
void HH_Vif1Packet_GeneralGifTag_TriangleFan_Open(void);

#endif
