/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Enemy/, by unit, in the order of their code. */
#ifndef SH2_API_ENEMY_H
#define SH2_API_ENEMY_H

#include "sh2/types.h"

/* Enemy/en_arm.c */
void enARMInitData(struct EnLOCAL_DATA *dp);
void enARMCtrlMain(struct EnLOCAL_DATA *dp);
void enARMGetHandPos(float *vec, struct EnLOCAL_DATA *dp, int d);

/* Enemy/en_bos.c */
void enBOSInitData(struct EnLOCAL_DATA *dp);
void enBOSCtrlMain(struct EnLOCAL_DATA *dp);

/* Enemy/en_common.c */
void enInitEnemy(void);
void enExecTask(void);
struct EnLOCAL_DATA *enEntryEnemy(int kind);
void enInitData(struct EnLOCAL_DATA *dp, struct SubCharacter *scp);
void enDeleteEnemy(struct EnLOCAL_DATA *dp);
void enDummyCtrl(struct EnLOCAL_DATA *dp);
int enTransID(int id);
int enGetWorldCondition(void);
int enGetPlace(void);
int enGetStage(void);
int enGetMode(void);
int enCheckDarkOrBright(struct SubCharacter *scp);
int enCheckDarkOrBrightPlayer(void);
int enCheckWater(struct EnLOCAL_DATA *dp);
void enSetBattleTarget(struct EnLOCAL_DATA *dp, unsigned int type);
void enSetHP(struct EnLOCAL_DATA *dp, float hp, float endurance);
float enReduceHP(struct EnLOCAL_DATA *dp);
float enAddHP(struct EnLOCAL_DATA *dp, float n);
float enAddEnduranceDT(struct EnLOCAL_DATA *dp, float n);
int enCheckDamage(struct EnLOCAL_DATA *dp);
int enCheckSpray(struct EnLOCAL_DATA *dp);
void enResetDamage(struct EnLOCAL_DATA *dp);
int enCheckDeath(struct EnLOCAL_DATA *dp);
void enSetHitBack(struct EnLOCAL_DATA *dp);
int enCheckInstantDeath(struct EnLOCAL_DATA *dp);
void enSetSize(struct EnLOCAL_DATA *dp, float size, float tall, float center, float eye);
void enSetNewSize(struct EnLOCAL_DATA *dp, float size, float tall, float center, float eye);
void enSetSeeLightStatus(struct EnLOCAL_DATA *dp, float center, float radius);
int enCheckSeeLight(struct EnLOCAL_DATA *dp);
int enCheckAimedByHuman(struct EnLOCAL_DATA *dp);
int enCheckFinishedByHuman(struct EnLOCAL_DATA *dp);
int enCheckNoDamageHuman(struct EnLOCAL_DATA *dp);
void enAttackStart(struct EnLOCAL_DATA *dp);
int enAttackCheck(struct EnLOCAL_DATA *dp, int ID);
int enAttackCheckHug(struct EnLOCAL_DATA *dp, int ID);
int enCheckHuggedPlayer(void);
int enCheckSleepIn(struct EnLOCAL_DATA *dp);
int enCheckSleepOut(struct EnLOCAL_DATA *dp);
void enSleepIn(struct EnLOCAL_DATA *dp);
void enSleepOut(struct EnLOCAL_DATA *dp);
void enKillCountUp(struct EnLOCAL_DATA *dp);
float *enGetPlayerPos(struct EnLOCAL_DATA *dp);
float enGetPlayerDistance(struct EnLOCAL_DATA *dp);
float enGetPlayerDirection(struct EnLOCAL_DATA *dp);
int enGetPlayerWeapon(void);
int enCheckPlayerWeapon(void);
float enGetPlayerAngle(struct EnLOCAL_DATA *dp);
float enGetPlayerSize(void);
int enCheckPlayerSound(struct EnLOCAL_DATA *dp);
int enCheckPlayerCondition(struct EnLOCAL_DATA *dp);
int enCheckPlayerLight(void);
int enCheckPlayerSprayNow(void);
int enGetSprayPower(void);
int enCheckPlayerBulletEmpty(void);
int enCheckDeadPlayer(void);
void enSetGameOver(void);
void enFlagSetMoved(struct EnLOCAL_DATA *dp);
void enFlagResetMoved(struct EnLOCAL_DATA *dp);
void enFlagSetLieDown(struct EnLOCAL_DATA *dp);
void enFlagResetLieDown(struct EnLOCAL_DATA *dp);
void enFlagSetCritical(struct EnLOCAL_DATA *dp);
void enFlagResetCritical(struct EnLOCAL_DATA *dp);
int enCheckCritical(struct EnLOCAL_DATA *dp);
void enFlagSetNoDamage(struct EnLOCAL_DATA *dp);
void enFlagResetNoDamage(struct EnLOCAL_DATA *dp);
void enFlagSetDead(struct EnLOCAL_DATA *dp);
void enFlagResetDead(struct EnLOCAL_DATA *dp);
void enFlagSetRotFloor(struct EnLOCAL_DATA *dp);
void enFlagResetRotFloor(struct EnLOCAL_DATA *dp);
void enFlagResetRotFloorJust(struct EnLOCAL_DATA *dp);
void enFlagSetDisplay(struct EnLOCAL_DATA *dp);
void enFlagResetDisplay(struct EnLOCAL_DATA *dp);
float enCalcDirection(float *pa, float *pb);
float enCalcAngleDifference(float angle1, float angle2);
float enCalcSpeedRate(float angle, float *mpos, float *tpos);
void enMakeRotVector(float *vec, float *rot, float range);
int enCheckIntoScreen(struct EnLOCAL_DATA *dp);
struct SubCharacter *enGetNearCharacter(struct EnLOCAL_DATA *dp);
int enCalcTimer(int t);
void enSetTimer(struct EnLOCAL_DATA *dp, int t);
int enReduceTimer(struct EnLOCAL_DATA *dp);
struct EnLOCAL_DATA *enGetNearOtherEnemy(struct EnLOCAL_DATA *dp);
void enCheckNearPlayer(struct EnLOCAL_DATA *dp, int *count, float *dist, float limit);
void enSetRadioVolume(struct EnLOCAL_DATA *dp);
void enMoveAngle(struct EnPATH_DATA *p, float delta);
void enMoveAngleToPlayer(struct EnLOCAL_DATA *dp, float delta);
void enMoveExec(struct EnLOCAL_DATA *dp);
void enSetRotFloor(struct EnLOCAL_DATA *dp);
void enSetHitColumn(struct EnLOCAL_DATA *dp);
void enIKETrans(struct EnLOCAL_DATA *dp);
void enARMTrans(struct EnLOCAL_DATA *dp);
void enDyingExec(struct EnLOCAL_DATA *dp);
void enWaitRegenerate(struct EnLOCAL_DATA *dp);
void enFlyingFunc(struct SubCharacter *scp);
void enDeleteCharacter(struct EnLOCAL_DATA *dp);
void enInitPath(struct EnPATH_DATA *p, float angle);
int enSetPath(struct EnLOCAL_DATA *dp, float *target, float *pos);
float enCheckPath(struct EnLOCAL_DATA *dp, float *tpos, float *mpos);
float enCheckPath2(struct EnLOCAL_DATA *dp, float *tpos, float *mpos);
float enCheckForward(struct EnLOCAL_DATA *dp, float *pos, float *rot, float range);
float enCheckHitEyes(struct EnLOCAL_DATA *dp, float *sp, float *ep);
float enCheckHitEyes2(struct EnLOCAL_DATA *dp, float *sp, float *ep);
float enCheckPlayerHitEyes(struct EnLOCAL_DATA *dp, float *ep);
int enCheckFloor(float *pos);
void enGetSkeletonVector(float *vec, struct EnLOCAL_DATA *dp, int n);
void enGetSkeletonMatrix(float (*mat)[4], struct EnLOCAL_DATA *dp, int n);
int enGetDamageMotion(struct EnLOCAL_DATA *dp);
int enGetDownMotion(struct EnLOCAL_DATA *dp);
int enGetLieDirection(int dm);
void enAnimeSet(struct EnLOCAL_DATA *dp, int anim, int id);
void enAnimeSetDirectFrame(struct EnLOCAL_DATA *dp, int anim, int id, int frame);
void enAnimeExec(struct EnLOCAL_DATA *dp, struct EnANIME_DATA *pa, short anm_none);
void enSetTrans(struct EnLOCAL_DATA *dp);
void enSetTransN(struct EnLOCAL_DATA *dp, int n);
void enSetTransWalk(struct EnLOCAL_DATA *dp);
void enSetTransForward(struct EnLOCAL_DATA *dp, float s);
void enAnimePause(struct EnLOCAL_DATA *dp);
void enAnimeRestart(struct EnLOCAL_DATA *dp);
void enAnimeFrameSet(struct EnLOCAL_DATA *dp, unsigned short frame);
void enAnimeReverse(struct EnLOCAL_DATA *dp);
void enSetAnimeCount(struct EnLOCAL_DATA *dp, int count);
void enEfctBloodPool(struct EnLOCAL_DATA *dp);
void enEfctPoisonFog(float *pos, float *vec);
void enSetBlur(void);
void enSetFadeOut(void);
void enResetFilter(void);
void enSoundCall(int num, float vol, float *pos);
void enSoundCall3D(int num, float vol, float *pos);
void enSoundStop(int num);
void enSoundSetQueue(struct SubCharacter *scp, int num, float vol, float time);
struct EnCOMMUNICATION *enSetCommunication(int kind, int type, float *pos, float dist, int time);
struct EnCOMMUNICATION *enCommunicateTribe(int kind, float *pos);
void enResetForbiddenArea(void);
void enSetForbiddenArea(float x0, float z0, float x1, float z1);
void enRoomForbiddenArea(void);
int enCheckForbiddenArea(float *sp, float *ep, float size);
int enCheckForbiddenAreaSub(struct EnFORBIDDENAREA *fa, float *sp, float *ep, float size);
void enEventDriven(int event, int id);

/* Enemy/en_draw.c */
void enDrawRadar(void);

/* Enemy/en_edb.c */
void enEDBInitData(struct EnLOCAL_DATA *dp);
void enEDBCtrlMain(struct EnLOCAL_DATA *dp);
void enEDBSetGunFire(struct EnLOCAL_DATA *dp);
void enNIKInitData(struct EnLOCAL_DATA *dp);
void enNIKCtrlMain(struct EnLOCAL_DATA *dp);

/* Enemy/en_effect.c */
void enEfctInit(void);
void enEfctTexInit(void);
void enEfctClear(void);
void enEfctDraw(void);
void enEfctSetPoisonFog(float *pos, float *vec);
void enEfctMovePoisonFog(struct EnEFCT_TASK *pt);
void enEfctDrawPoisonFog(struct EnEFCT_TASK *pt);
void enEfctSetPoisonTex(void);
void enEfctDrawInsect(void *p);
void enEfctSetInsectTex(void);
void enEfctSetSpray(float *pos, float *vec, unsigned int color, int timer);
void enEfctMoveSpray(struct EnEFCT_TASK *pt);
void enEfctDrawSpray(struct EnEFCT_TASK *pt);
void enEfctSetSprayTex(void);
void enEfctSetTYU2D(float *pos, float *rot);
void enEfctMoveTYU2D(struct EnEFCT_TASK *pt);
void enEfctDrawTYU2D(struct EnEFCT_TASK *pt);
void enEfctSetTYU2DTex(void);

/* Enemy/en_fly.c */
void flyInit(float *pos);
void flyMove(void);
void flyGetPos(float *pos);

/* Enemy/en_ike.c */
void enIKEInitData(struct EnLOCAL_DATA *dp);
void enIKECtrlMain(struct EnLOCAL_DATA *dp);

/* Enemy/en_insect.c */
void enINSInitData(struct EnLOCAL_DATA *dp);
void enSetInsect(float *pos, int num);
void enKillAllInsect(void);
void enWaitAllInsect(void);
struct SubCharacter *enINSGetSubCharacter(struct EnLOCAL_DATA *dp);
void enINSCtrlMain(struct EnLOCAL_DATA *dp);

/* Enemy/en_mkn.c */
void enMKNInitData(struct EnLOCAL_DATA *dp);
void enMKNCtrlMain(struct EnLOCAL_DATA *dp);

/* Enemy/en_nse.c */
void enNSEInitData(struct EnLOCAL_DATA *dp);
void enNSECtrlMain(struct EnLOCAL_DATA *dp);

/* Enemy/en_oni.c */
void enONIInitData(struct EnLOCAL_DATA *dp);
void enONICtrlMain(struct EnLOCAL_DATA *dp);

/* Enemy/en_pap.c */
void enPAPInitData(struct EnLOCAL_DATA *dp);
void enPAPCtrlMain(struct EnLOCAL_DATA *dp);

/* Enemy/en_red.c */
void enREDInitData(struct EnLOCAL_DATA *dp);
void enREDCtrlMain(struct EnLOCAL_DATA *dp);

/* Enemy/en_scu.c */
void enSCUInitData(struct EnLOCAL_DATA *dp);
void enSCUCtrlMain(struct EnLOCAL_DATA *dp);

/* Enemy/en_tyu.c */
void enTYUInitData(struct EnLOCAL_DATA *dp);
void enTYUCtrlMain(struct EnLOCAL_DATA *dp);
void enTY2InitData(struct EnLOCAL_DATA *dp);
void enTY2CtrlMain(struct EnLOCAL_DATA *dp);
void enTY3InitData(struct EnLOCAL_DATA *dp);
void enTY3CtrlMain(struct EnLOCAL_DATA *dp);

#endif
