/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Event/, by unit, in the order of their code. */
#ifndef SH2_API_EVENT_H
#define SH2_API_EVENT_H

#include "sh2/types.h"

/* Event/chara_admin.c */
void ConnectCharaWorkJamesSet(void);
void ConnectCharaWorkWeapon(void);
void ConnectCharaWorkReset(void);
void ConnectCharaWorkAdminOut(int load_check);
void ConnectCharaWorkAdminIn(void);
void ConnectCharaWorkAdminClear(void);
struct SubCharacter *CharaWorkCreate(short kind, short id, float *pos, float *rot, unsigned int status);
int CharaAdminEnemyEntryCheck(struct Enemy_List *ep, int room);
void CharaAdminPlayableDisplay(int xxx);
struct SubCharacter *CharaAdminReCreate(int kind, int new_id, int old_id, float *pos, float *rot, int status);
void CharaAdminBackLoadEnemy(struct CharaData_DemoList *list);

/* Event/chara_data_load.c */
void CharaDataLoadInit(void);
void CharaDataLoadItem(void);
void CharaDataLoadWeapon(void);
void CharaDataLoadEnemy(int kind);
void CharaDataLoadStage(void);
void CharaDataLoadRoom(int room);
void CharaDataLoadDemo(struct CharaData_DemoList *dlp, int status);
void CharaDataLoadCancel(struct CharaData_DemoList *dlp);
void CharaDataWeaponTranslation(int kind, union fsFileIndex *file_anm, void *adr_anm, union fsFileIndex *file_mdl, void *adr_mdl);
u_long128 *CharaDataExtraTranslation(union fsFileIndex *file, void *adress);
u_long128 *CharaDataAnimSetExtra(int kind, union fsFileIndex *file, u_long128 *adress, int free);
u_long128 *CharaDataAnimAdressExchange(struct SubCharacter *scp, u_long128 *adr);
u_long128 *CharaDataLoadExtra(union fsFileIndex *file, int status);
void CharaDataDeleteAll(void);
void CharaDataDeleteOne(int kind);
void CharaDataDeleteExtra(void);
int CharaDataFileSearch(union fsFileIndex **file, int kind);
void CharaDataBackLoadInit(void);
void CharaDataBackInit(struct CharaData_DemoList *dlp);

/* Event/chizu.c */
void ChizuMain(void);

/* Event/demoview.c */
int DramaDemoMain(struct DramaDemo_PlayInfo *info);
void DramaDemoSkipLast(struct DramaDemo_PlayInfo *info);
void DramaDemoFade(void);
int DramaDemoNumber(void);
void SubtitlesExec(struct DramaDemo_MessageTime *msg_time, int msg_no, int str_no, float timer);
void SubtitlesManager(void);

/* Event/event.c */
void FlagInit(void);
void EventProgInit(void);
void EventMain(void);
int EventCheck(int act_on, int use_item, int check_only);
float CharToFloat2(char *cp);
float CharToFloat4(char *cp);
void EventCancel(void);
int LightSpotOnOffCheck(void);
void LightSpotOnOffSet(void);
int EventProgressCheck(void);
int EventItemConditionCheck(int level, int flag);
void RadioNoise(void);

/* Event/event_sub.c */
int EvSubMessage(int msg);
int EvSubQuestion(int msg);
int EvSubItemUse0(int kind, int message, int se, int stereo, float *pos, int xxx);
int EvSubItemGet(int kind, int message);
int EvSubItemGetAndAnim(int kind, int message);
int EvSubFileLoadAndFadeOut(int mode, union fsFileIndex *file_0, union fsFileIndex *file_1);
int EvSubPictureDisplayAndFadeIn(float fade);
int EvSubPictureDisplayOnly(void);
int EvSubPictureDisplayAndFadeOut(float fade);
int EvSubPictureDisplay(union fsFileIndex *file, int msg);
int EvSubMapGet(union fsFileIndex *file, int msg);
void EvSubPictureLayer(int x0, int y0, int x1, int y1, int alpha);
void EvSubPictureFilter(void);
void EvSubPictureInit(void);
void EvSubPictureStart(void);
void EvSubPictureEnd(void);
void EvSubPictureCursor(int color);
void EvDispControlModelEntry(int *list, int room, int no);
void EvDispControlModelExec(int *list);
void EvSubMovieReady(union fsFileIndex *file, struct DramaDemo_MessageTime *msg_time, int msg_no);
int EvSubMovieStart(int demo);
void EvSubMovieEnd(void);

/* Event/item.c */
void ItemDataInit(void);
void ItemGet(int kind);
int ItemUse(int kind);
int ItemWeaponShoot(int kind, int use);
int ItemWeaponReload(int kind, int use);
int ItemMedicineUse(int kind);
float ItemAmpolueEfficacy(void);
int ItemEventCheck(int kind_0, int kind_1, int kind_2);
int ItemCombinationUseCheck(int kind_0, int kind_1, int kind_2);
void ItemPutForShelf(void);

/* Event/memo.c */
void MemoMain(void);
int MemoCommandCheck(void);

/* Event/picture.c */
void PictureDraw(struct PicDraw_Data *pic);
void PictureLoadImage(struct sh2gfw_AREA_HEAD *ap, int otp, int tex_adr, int clut_adr);

/* Event/stg_name.c */
int RoomNameJms(void);
int RoomName(int glb_crd, float pos_x, float pos_z);
int BlockNumber(int *ret, int glb_crd, float pos_x, float pos_z);
int BgIsOut(int glb_crd);

/* Event/stg_overlay.c */
void StgOverlay(void);

/* Event/title.c */
int TitleMain(void);
void titleSetDataStartPoint(void);
int GameendMain(void);
int GameoverMain(void);

/* Event/vu0_func.c */
float shOuterXZ(float x, float z, float x0, float z0, float x1, float z1);

#endif
