/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/FilesList/, by unit, in the order of their code. */
#ifndef SH2_API_FILESLIST_H
#define SH2_API_FILESLIST_H

#include "sh2/types.h"

/* FilesList/fileslist_bg.c */
struct FilesBgBlock *FilesGetBgBlock(enum STAGE_ID stg_id, int blk_id);

#endif
