/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Fog/, by unit, in the order of their code. */
#ifndef SH2_API_FOG_H
#define SH2_API_FOG_H

#include "sh2/types.h"

/* Fog/fog.c */
void fogInit(void);
void fog_set_defpacket(void);
void fogSetEnvironment(struct FOG_ENV_DATA *edata);
void fogInitScreen(void);
void fogInitWind(void);
void fogChangeWind(int wind);
void fogInitParticle(void);
void fog_init_part_sub(struct FOG_PART_DATA *pd);
void fog_part_newpos();
void fogResetWall(void);
void fogSetWall(void *Vector);
void fogResetObj(void);
void fogSetObj(unsigned long ID, void *Center, float Size);
void fogMoveObj(unsigned long ID, void *Center);
void fogSetObj2(unsigned long ID, void *Center, float Size);
void fogEraseObj(unsigned long ID);
void fogSetObjSize(unsigned long ID, float Size);
struct FOG_OBJ_DATA *fogGetObj(unsigned long ID);
void fogMoveParticle(void);
void fog_load_objdata(void);
void fog_set_stay(void);
void fog_part_wall(void);
void fog_part_grid(void);
void fog_part_obj(void);
void fog_part_obj2(void);
void fog_part_alp(void);
void fog_part_clamp(void);
void fogMakePacket(void);
void fog_view_screen_fog(void);
void fogSetColor(unsigned char r, unsigned char g, unsigned char b, unsigned char a);
void fogSetPartNum(int PartNum);
void fogSetProjection(float Projection);
void fogSetFloorY(float FloorY);
void fogSetWorldScreenM(void *WorldScreenM);
void fogSetWorldViewM(void *WorldViewM);
void fogSetWorldPosV(void *WorldPosV);
void fogSetStayPos(void *WorldPosV);
void fogResetStayPos(void);
void fogSetStayPoint(void *StayPoint);
void fogResetStayPoint(void);
void fogSetCameraPosV(void *CameraPosV);
void fogSetLocalPosV(void);
void fogSetSpeedLevel(float SpeedLevel);
unsigned long *fogTex0Adr(void);

/* Fog/fog_blow.c */
void fogInitParticle2(void);
void fogSetBlowPoint(int room);
void fogBlow(struct FOG_BLOW_POINT *blow);
void fogMoveParticle2(void);
void fog_part_blow(void);
void fog_part_clamp2(void);
void fogMakePacket2(u_long128 *ppos);

/* Fog/fogdata.c */
void fogSetCollision(void);
void fogSetCollisionMain(void);
void fogSetCollisionMain2(void);
void fogSetAreaEnvironment(void);

/* Fog/sh2gfw_fogtest_main.c */
void sh2gfw_fogtest_calcmain(void);
void sh2gfw_init_fogTexture(void);
void sh2gfw_send_fogtex(void);

/* Fog/spack.c */
struct SPACK_DATA *spkInit(void);
void spkResetOT(void);
void spkResetOT2(void);
void spkOpenGiftag(void *giftag, unsigned int w, unsigned short envid);
void spkOpenDGiftag(unsigned long giftag1, unsigned long giftag2, unsigned int w, unsigned short envid);
void spkCloseGiftag(void);
void spkCloseOpenDGiftag(unsigned long giftag1, unsigned long giftag2);
void spkStartPacketS(u_long128 *adr);
void spkOpenGiftagS(void *giftag);
void spkOpenDGiftagS(unsigned long giftag1, unsigned long giftag2);
void spkCloseGiftagS(void);
u_long128 *spkEndPacketS(void);
void spkSetEnvPacket(u_long128 *adr, unsigned short envid);
void spkStartEnvLoadImage(unsigned short envid);
void spkSetEnvLoadImage(void *image, short bp, short bw, short psm, short x, short y, short w, short h);
void spkEndEnvLoadImage(void);
void spkSetOTPacketS(u_long128 *adr, unsigned int w, unsigned char envid);
void spkSetOTPacketS_asm(void);
void spkSetOT(void);
void *spkDmaKick(void);
void spkDmaWaittoSPR(int timeout);
void spkDmaWaitfromSPR(int timeout);
void spkDmatoSPR(unsigned int qwc, unsigned int sadr, void *madr);
void spkDmafromSPR(unsigned int qwc, unsigned int sadr, void *madr);
void spkDebugPrint(void);

/* Fog/spkTexMan.c */
void sh2gfw_Init_spkTexManage(void);
void sh2gfw_EnQue_spkTexture(void *pTM, int *cid, int *sid);
void sh2gfw_ThrSyncKick_spkDmaKick(void);

#endif
