/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Font/, by unit, in the order of their code. */
#ifndef SH2_API_FONT_H
#define SH2_API_FONT_H

#include "sh2/types.h"

/* Font/dic.c */
unsigned short *dicSetStr(void *str);
unsigned short dicTransCode(unsigned short code);

/* Font/fj_man.c */
void fjInitAll(void);
void fjInitFontTexture(void);
void fjMoveEffect(void);
void fjDrawExec(void);
void fjFontDrawExec(void);
void fjFontDrawExecVif1(void);
int fjAssert_(char *file, int line, char *str);

/* Font/font.c */
struct FONT_DATA *fontInit(void);
void fontClear(void);
void fontSetStreamMax(unsigned short s_max, unsigned short ws_max, unsigned short ms_max);
int fontLoad(unsigned short code);
void fontSet(unsigned short code, unsigned short x, unsigned short y);
void fontSetWide(unsigned short code, unsigned short x, unsigned short y, unsigned short w, unsigned short h);
void fontSetBlankBox(int x0, int x1, int y);
void fontSetLine(int x, int w, int y);
void fontPrintStr(unsigned short *str, int x, int y);
void fontPrintStrNum(unsigned short *str, unsigned short num, int x, int y);
unsigned short fontPrintStrMain(unsigned short **pstr, int flag);
void fontPrintDec(int num, int x, int y, int len, int flag);
void fontSetYesNo(int y);
int fontPrintWord(unsigned short *str, int x, int y, int align, int align2);
void fontPrintStrWide(unsigned short *str, int pos_x, int pos_y, int sx, int sy);
int fontGetMesWidth(int *buf, unsigned short *str);
void fontSetColor(int num);
void fontSetColorDirect(unsigned char r, unsigned char g, unsigned char b, unsigned char alp);
void fontSetAlpha(unsigned char alp);
u_long128 *fontFlush(void);
u_long128 *fontFlushNoSPR(void);
void fontPut(struct WFONT_STREAM_DATA *pstr, int z);
void fontPutSelectBar(void);
void fontPutYesNoSelectBar(void);
void *fontTexLoad(int texadr, int clutadr);
void *fontAfterEnv(void);
void fontEachTurn(void);
void fontPreload(void);
void fontSetMes(int num, unsigned short *str);
void fontCopyMessage(unsigned short *pto, unsigned short *pfrom);
void fontPushButton(void);
void fontPushButton2(void);
void fontSelectUp(void);
void fontSelectDown(void);
unsigned short *fontGetMesAdr(unsigned short *str, unsigned short num);
void fontMessageNum(unsigned short *str, unsigned short num);
void fontMessage(unsigned short *str);
void fontNextMessage(void);
int fontGetStatus(void);
void fontWide(unsigned short w, unsigned short h);
void fontAllCenterOn(void);
void fontAllCenterOff(void);
void fontAllCenter2On(void);
void fontAllCenter2Off(void);
void fontShadowOff(void);
void fontCrushOn(void);
void fontCrushOff(void);
void mfontClear(void);
u_long128 *mfontFlush(void);

#endif
