/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/GFW/, by unit, in the order of their code. */
#ifndef SH2_API_GFW_H
#define SH2_API_GFW_H

#include "sh2/types.h"

/* GFW/sh2_DrawEnvData.c */
void *Get_NowDrawEnvData(void);
int Get_NowParallelNum(void);
int Get_NowFakePointNum(void);
int Get_NowFakeSpotNum(void);
int Check_NowSpotFakeOrJms(void);
int Get_NowRoomShadowDense(void);
int Get_NowRoomShadowColor(void);
void *Get_NowRoomShadowForceLight(int *ltype);
int Check_IgnoreJmsSpot_for_Shadow(void);
int *Get_NowMapId(void);
void Get_NowPallarelCol(float *pdir, int nn);
void Set_DrawEnvData(int mapid, int NightOrDay);
void SetupDrawEnvData(void);

/* GFW/sh2_get_drawenv.c */
void sh2gfw_Set_EyeDir(void);
void sh2gde_Get_EyeDir(float *svt);
float sh2gde_Get_InnerVectorJmsCam(void);
void kari_sh2gde_getspotParams(float *spotpos, float *spotdir, float *decayparms);
void sh2gde_getspotParams_for_Shadow(float *spotpos, float *spotdir, float *decayparms);
void sh2gde_getspotKTParams(float *spotpos, float *spotdir, float *spotcol, float *decayparms, int getmode);
void sh2gde_getCameraDir(float *cameradir);
void sh2gde_get_spotposdir(float *pos, float *dir);
int sh2gde_CheckSpot_JmsOrBG(void);
float (*sh2gde_Get_BGSpotPos(void))[4];
float (*sh2gde_Get_BGSpotDir(void))[4];

/* GFW/sh2_set_drawenv.c */
void sh2gfw_Set_Brightness(int pow);
void kari_sh2setGS_fogcolor(unsigned int fr, unsigned int fg, unsigned int fb);
void kari_sh2setGS_clearcolor(unsigned int cr, unsigned int cg, unsigned int cb, unsigned int ca);
void kari_sh2gfw_vu_change(struct sh2gfw_BLOCK_MAN *bm, unsigned int light_mode);
int sh2gfw_Rotate_CD11(void);
int sh2gfw_Jump_BlockPos(int mapidno, float *jv);
int sh2gfw_Reset_BlockPos(int mapidno);
void sh2gfw_Set_Fogfar(float fogfar);
void sh2gfw_Set_FogNear(float fogNear);
void sh2gfw_Set_FogMax(float fogMax);
void sh2gfw_Set_FogMin(float fogMin);
void sh2gfw_Set_DepthFog(float fogfar, float fognear, float fmax, float fmin);
void sh2gfw_Set_DepthFogFAFB(void);
void sh2gde_SetSpot_JmsOrBG(int bg);
void sh2gde_ResetSpot_Jms(void);

/* GFW/sh2_shadow_filters.c */
void sh2gfw_Set_FilterData(int NoD, int arg1, union Q_WORDDATA *col);
void *Get_ShadowColor(void);
void sh2gfw_Set_ShadowColorScaleFactor(float fc);
union Q_WORDDATA *shdw_Composite_Shadow(union Q_WORDDATA *pbuf);
union Q_WORDDATA *shdw_fill_Work(union Q_WORDDATA *col, unsigned int prim, union Q_WORDDATA *pbuf);
union Q_WORDDATA *shdw_clear(union Q_WORDDATA *pbuf);
union Q_WORDDATA *shdw_StencilBuf2Work(unsigned int tbp, unsigned int prim, union Q_WORDDATA *pbuf);
union Q_WORDDATA *shdw_Work2Work(unsigned int tbp, union Q_WORDDATA *pbuf);
void shdw_shadow_filter_main(int arg0);

/* GFW/sh2_shadow_main.c */
void sh2gfw_ShadowControl_Main(void);
void shadow_main(unsigned int paddata, struct sh2gfw_CAMERA *cam, float (*local_world)[4]);
void drop_shadow_main(unsigned int paddata, struct sh2gfw_CAMERA *cam, int arg2, int arg3);

/* GFW/sh2gfw_2d_filters.c */
void sh2gfw_Filter_JustCopy2(union Q_WORDDATA **ppqwd);
void sh2gfw_Filter_Blur(union Q_WORDDATA **ppqwd, unsigned int bl_ratio);
void sh2gfw_Filter_Dark_Blur(union Q_WORDDATA **ppqwd, unsigned int bl_ratio, unsigned int aref);
void sh2gfw_Filter_Glow_Blur(union Q_WORDDATA **ppqwd, unsigned int aref, unsigned int bl_ratio, unsigned int pam);
void sh2gfw_test_MakeNoise(void);
void sh2gfw_Black_Clear(void);
void sh2gfw_SendDraw_Noise(union Q_WORDDATA **ppqwd, unsigned int ratio, unsigned int pam, unsigned int mode, int loop);
void sh2gfw_Swap_Soft(union Q_WORDDATA **ppqwd, int mode, int arg2, int CompoIt, int aref, int testval, int testmode);
void sh2gfw_Swap_GlowSoft(union Q_WORDDATA **ppqwd, int mode, int parm, int aref, int Shift);
void sh2gfw_FadeOut_Retain(union Q_WORDDATA **ppqwd, int BorW);
void sh2gfw_Filter_Retain(union Q_WORDDATA **ppqwd);
int sh2gfw_Fade2(union Q_WORDDATA **ppqwd, int mode, int color, int flg);
int sh2gfw_Fade3(union Q_WORDDATA **ppqwd, int mode, int *color);
void sh2gfw_Set_FadeOutRetain_Black(float ra);
void sh2gfw_Set_FadeOut_Black(float ra);
void sh2gfw_Set_FadeOutRetain_White(float ra);
void sh2gfw_Set_FadeOutRetain_Red(float ra);
void sh2gfw_Set_FadeOut_White(float ra);
void sh2gfw_Set_FadeIn_Black(float ra);
void sh2gfw_Set_FadeIn_White(float ra);
void sh2gfw_Set_FadeIn_Red(float ra);
void sh2gfw_Set_FilterBlur(int rt);
void sh2gfw_Set_PauseRetain(void);
void sh2gfw_Reset_PauseRetain(void);
void sh2gfw_Reset_FilterCommand(void);
int sh2gfw_Get_FilterCommand(void);
void *sh2gfw_Get_FilterCommandParams(void);
int sh2gfw_Set_CaptureNowFB(void);
void Exec_PostDraw_OVfunc(void);
int Check_Filter_Soft(void);
void DemoFadeDraw2(int a, int b, int c, int d);
void Make_Filter_Packet(void *pb, int mode);

/* GFW/sh2gfw_alltexman.c */
void sh2gfw_init_Trans(struct sh2gfw_ALLTEXSYNC_MAN *pATSM);

/* GFW/sh2gfw_GSCTL_man.c */
void sh2gfw_init_GSPACKMAN(struct sh2gfw_GSPACK_MAN *Gman);
void sh2gfw_setREF_gsctl(union Q_WORDDATA *gt);
void sh2gfw_setREF_tagchain(union Q_WORDDATA **pqwd, union Q_WORDDATA *gt);
union Q_WORDDATA *sh2gfw_setEND_gsctl(void);
void sh2gfw_setCALL_gsctl(union Q_WORDDATA *pf);
void sh2gfw_setREF_TEXFLUSH(void);

/* GFW/sh2gfw_Init_ModelDrawData.c */
void sh2gfw_srInit_ModelDrawWork(void);
struct sh2gfw_ModelDraw_MAN *sh2gfw_Get_pMD(int chara_id);
int sh2gfw_Check_ModelIsOnMemory(int cid);
int sh2gfw_LoadInit_CharaModelData(struct chr_mge_files *cdl);
int sh2gfw_LoadMemorySet_CharaModelData(struct chr_mge_files *cdl, u_long128 **ModelMemBuffer, u_long128 **AnimeMemBuffer, u_long128 **ClusterMemBuffer, u_long128 **Kg1MemBuffer);
int sh2gfw_LOAD_CharaModelData(void);
void sh2gfw_SyncInit_ChacterModelData(void);
int sh2gfw_Cancel_LOADCharaModelData(void);
void sh2gfw_ModelDrawInit_for_BackgroundLoad(int chara_id, void *memhead_model, void *memhead_anime, void *memhead_cluster, void *memhead_kg1);
void *sh2gfw_CreateSubCharacter(int chara_id);
int sh2gfw_Delete_Model_from_CharaID(int chara_id);
void sh2gfw_kari_clear_LM(void);
void sh2gfw_init_CharaModel_TextureData(struct sh2gfw_ModelDraw_MAN *pMD);

/* GFW/sh2gfw_LightSet.c */
void sh2gfw_Init_DemoLight_Work(void);
int sh2gfw_Set_DemoRefrectionHighLight(float *dir, float *col);
int sh2gfw_Get_DemoRefrectionHightLight(float *dir, float *col);
int sh2gfw_Check_DemoRefrectionHightLight(void);
int sh2gfw_Set_PallarelLight(float *dir, float *color, int n);
int sh2gfw_Check_ParallelDemoLight(int n);
int sh2gfw_Get_ParallelDemoLight(int n, float *dir, float *col);
void sh2gfw_Revive_ParallelDemoLight(int n);
void sh2gfw_Set_DemoPointLight(int n, float *pos, float *col, float falloff_start, float falloff_end);
int sh2gfw_Check_DemoPointLight(void);
int sh2gfw_Get_DemoPointLight(int n, float *pos, float *col, float *decay);
int sh2gfw_Check_DemoSpotLight(void);
void sh2gfw_Get_DemoSpotParm(float *svt);
void sh2gfw_Get_DemoSpotPosDirCol(float *pos, float *dir, float *col);
void sh2gfw_Set_SpotLight(float *dir, float *pos, float *color, int arg3, float falloff_start, float falloff_end, float spread_pi);
void sh2gfw_setparal3LGT_blk(void *pbman, float *light_dir0, float *light_dir1, float *light_dir2, float *col0, float *col1, float *col2, float *ambient);
void sh2gfw_LightSet_ForBG(void *pb_man);
void sh2gfw_Store_SpotLight(void);
void sh2gfw_setsp1para2LGT_blk(void *pbman, void *sm, float *light0, float *color0, float *light1, float *color1, float *amb);
int sh2gfw_Get_NightOrDay(void);
int SetLightMode(int nod);
void Get_DemoOrPresetLight(float *pl, float *pc, int g);
void Get_DemoOrPresetAmbient(float *ab);
void sh2gfw_Set_JmsSpot_OnOrOff(void);

/* GFW/sh2gfw_packetVU.c */
int sh2gfw_get_VuBase(int execaddr);
int sh2gfw_get_VuOffset(int execaddr);
void sh2gfw_Init_VuCounter(void);
int sh2gfw_Check_VuCounter(int vc);
int sh2gfw_GetVuKick_Addr(int execaddr);
int sh2gfw_GetVuKick_Addr2(int execaddr);
void sh2gfw_init_VU_PARAMS(struct sh2gfw_VU_PARMS *VU_PARMS);
void sh2gfw_allinit_lightenv(struct sh2gfw_LIGHT_ENV *slv);
void sh2gfw_set_GSREGS2Vu(struct sh2gfw_VU_PARMS *vupam);
int sh2gfw_set_VuSend(void *pT, struct sh2gfw_GIFTAG_HEAD *pGH, struct sh2gfw_VU_HEAD *vuh, int *exec, union Q_WORDDATA **ppqwd);
int sh2gfw_get_VUmode(int light_mode, int tfx, struct sh2gfw_GIFTAG_HEAD *pGIF_H, struct sh2gfw_VU_HEAD *pVU_H);
int sh2gfw_Change_VUmode(unsigned int light_mode, unsigned int vuid, unsigned int *baseaddr, unsigned int *offsetaddr);

/* GFW/sh2gfw_parse_and_packet.c */
union Q_WORDDATA *sh2gfw_Get_BTADDR(int bno);
union Q_WORDDATA *sh2gfw_Get_PKTADDR(int gno);
union Q_WORDDATA *sh2gfw_Get_BGAREABUF(void);
union Q_WORDDATA *sh2gfw_Get_TransLocalBuf(void);
union Q_WORDDATA *sh2gfw_Get_BLOCKmainPack(void);
union Q_WORDDATA *sh2gfw_Get_SemiTransPKADDR(int bno);
void sh2gfw_DBG_packsize(int pb, int pg);
int sh2gfw_parse_HEAD(union Q_WORDDATA *d_h, struct sh2gfw_BLOCK_MAN *pB_man, struct sh2gfw_AREA_MAN *pAMAN, struct sh2gfw_ALLTEXSYNC_MAN *pATSM);
int sh2gfw_parse_global(union Q_WORDDATA *d_h, struct sh2gfw_BLOCK_MAN *pB_man, struct sh2gfw_AREA_MAN *pA_MAN);
int sh2gfw_parse_SemiTransTex(union Q_WORDDATA *datahead, struct sh2gfw_BLOCK_MAN *pB_man);
int sh2gfw_parse_local(union Q_WORDDATA *d_h, struct sh2gfw_BLOCK_MAN *pB_man);
int sh2gfw_packet_Poly_GlobalTexUsing(struct sh2gfw_BLOCK_MAN *pB_man, struct sh2gfw_AREA_MAN *pAMAN, union Q_WORDDATA *b_p, union Q_WORDDATA *g_p, int *pb, int *pl);
int sh2gfw_packet_Poly_LocalTexUsing(struct sh2gfw_BLOCK_MAN *pB_man, struct sh2gfw_AREA_MAN *pAMAN, union Q_WORDDATA *b_p, union Q_WORDDATA *g_p);
int sh2gfw_packet_Poly_SemiTrans(struct sh2gfw_BLOCK_MAN *pB_man, union Q_WORDDATA *b_p);
void sh2gfw_Set_SpecularAlpha(void);
void sh2gfw_init_zeroQ_BMAN(struct sh2gfw_BLOCK_MAN *pB_man);

/* GFW/sh2gfw_read_process.c */
void sh2gfw_Set_TrTex(void *pT);
int sh2gfw_LoadSet_SemiTransTEX(int mapid, void *fl);
void sh2gfw_LOAD_AREADATA_ID(unsigned int stage);
int sh2gfw_Process_AREAtoMAN(union Q_WORDDATA *d_h, struct sh2gfw_AREA_MAN *pAMAN, struct sh2gfw_ALLTEXSYNC_MAN *pATSM);
unsigned int sh2gfw_process_AreaDATA(unsigned int map_id);
void sh2gfw_Free_BlockLocalTex(struct sh2gfw_ALLTEXSYNC_MAN *pATSM, struct sh2gfw_BLOCK_MAN *pB_man);
void sh2gfw_AllClear_TrMAN(void);
unsigned int sh2gfw_process_blockLOCAL_main(union Q_WORDDATA *datahead, struct sh2gfw_BLOCK_MAN *pB_man, struct sh2gfw_AREA_MAN *pA_man, union Q_WORDDATA *b_pack, union Q_WORDDATA *g_pack, union Q_WORDDATA *t_pack, int stid, int mapid);
void sh2gfw_Set_GB_Tex(void *addr);
void sh2gfw_Delete_GB_Tex(void);
void sh2gfw_Set_TR_Tex(void *addr);
void sh2gfw_Delete_TR_Tex(void);
void sh2gfw_Set_BlockLocal(int slot, void *addr, int mapid);
void sh2gfw_Delete_BlockLocal(int slot);

/* GFW/sh2gfw_SemiTrans_FrameWork.c */
void sh2gfw_Init_NoSortPkbuf(void);
int sh2gfw_Draw_SemiTransBG(void);

/* GFW/sh2gfw_Texpacket.c */
void sh2gfw_allinit_TexMANlist(struct sh2gfw_ALLTEXSYNC_MAN *pATSM);
void sh2gfw_clear_TexMAN_TransParm(struct sh2gfw_ALLTEXSYNC_MAN *pATSM);
struct sh2gfw_TexMAN *sh2gfw_set_TexToTrasMan(struct sh2gfw_ALLTEXSYNC_MAN *pATSM, struct sh2gfw_TEX_HEAD *pTexHead, struct sh2gfw_CLUTS_HEAD *pClutHead, void *pMAN, unsigned short mode);
struct sh2gfw_TexMAN *sh2gfw_del_TexMAN(struct sh2gfw_ALLTEXSYNC_MAN *pATSM, struct sh2gfw_TexMAN *pDel);
void sh2gfw_Change_TexBody(void *pT, void *texaddr);
void sh2gfw_Reset_TexBody(void *pT);
u_long128 *sh2gfw_Get_RegTEX0(struct sh2gfw_TexMAN *sTM, unsigned int clutid, unsigned int flg);
int sh2gfw_Get_TFX(void *sTMV, int clutid);
int sh2gfw_Thr_d2TextureSend(void *ptm, int mode, int *cid, int *slotid);
int sh2gfw_Thr_d1d2SyncKick(void *pkaddr, int cid, int slotid);
void sh2gfw_Lock_AllTexSlot_For_Shadow(void);
void sh2gfw_UnLock_AllTexSlot_For_Shadow(void);
void sh2gfw_init_TexTrans_Manage_Table(void);
int sh2gfw_EnQue_TexSlot(void *pTexMan);
int sh2gfw_SetSlot2Tex(struct sh2gfw_TexMAN *sTM, int slotno, int mode);

/* GFW/sh2gfw_Vertexpacket.c */
void sh2gfw_Geom_MakePacket(struct sh2gfw_VU_HEAD *pV, struct sh2gfw_GEOM_HEAD *sGE, int packsize, int xgkick, int execaddr, union Q_WORDDATA **ppqwd);
void sh2gfw_SemiTrans_GeomPacket(struct sh2gfw_TRANSGEOM_HEAD *sGE, int gid, union Q_WORDDATA *inf, union Q_WORDDATA **pkhead);

/* GFW/sh2gfw_viewclip.c */
int sh2gfw_viewclip_block(union Q_WORDDATA **qwd_tag);
void sh2gfw_set_objclip_matrix(void);
int sh2gfw_Set_DispOnOffObj(int mapid, int dispflg);
void sh2gfw_Init_DispOnOffObj(void);
int sh2gfw_FastSet_DispOnOffObj(int mapid, int dispflg);
int sh2gfw_Get_ChrClip_FLG(void);
void sh2gfw_Check_ChrClip_FLG(int mp);
int sh2gfw_Check_ClipOKChar(void *sp);

#endif
