/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Heap/, by unit, in the order of their code. */
#ifndef SH2_API_HEAP_H
#define SH2_API_HEAP_H

#include "sh2/types.h"

/* Heap/sh2_ch_malloc.c */
struct utilHeapCtrl *shCh_ASC_InitHead(void *bufhead, int size);
void *shCh_ASC_Malloc(unsigned int n);
void shCh_ASC_Free(void *p);
void kari_ChAlloc_Init(void);

/* Heap/utilheap.c */
struct utilHeapCtrl *utilHeapInit(void *buf, unsigned int bytesize);
void *utilHeapMalloc(struct utilHeapCtrl *heapctrl, unsigned int n);
void utilHeapFree(void *obj);

#endif
