/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Item/, by unit, in the order of their code. */
#ifndef SH2_API_ITEM_H
#define SH2_API_ITEM_H

#include "sh2/types.h"

/* Item/item_tgs_tmp.c */
void TgsItemPictureLoad(void);
void TgsItemPitureStart(void);
void TgsItemPitureDraw(int kind, int cx, int cy, int rgb, int otp, float size);

/* Item/otn_itemmain.c */
int itemmain(void);
void itemmainmain(void);
void cur_step(void);
void command_main(int command_step);
void weapon_command_main(int command_step);
void item_main_setup(void);
void set_position(int step);
void item_turn(void);
void item_position(float *f0, float *f1, int count, float *r0);
int move_near(float f0, float f1, float f2, float f3);
int command_kind(int kind);
void del_check(void);
int kind_no(int kind);
void event_item_use(int kind);
void combine_item_use(int kind);
void examine_main(void);
void examine_file_load(void);
void examine2_main(void);
/* SH2_common/result.c has a static font_print of its own. */
#ifndef SH2_LOCAL_font_print
void font_print(void);
#endif
void kage_font(unsigned short *str, unsigned short num, int x, int y);
void lookline(float (*box)[4]);
void item_allay(void);
void sprite(void);
void look_command(int gosa);
void look_volume(void);
void look_hp(void);
void stock_line(int leftx, int hoge);
void look_combine(void);
void look_zanzo(float *za0, float *za1, float *za2, float *za3);
void look_blackscr(int num);
void item_fade_in(void);
void item_fade_out(void);
void item_examine_fade_out(void);

/* Item/otn_option.c */
int option_main(void);
void option_mainmain(void);
void bright_main(void);
void print_config(int con, int *xx, int yy);
int key_check(void);
void key_type1(void);
void key_type2(void);
void key_type3(void);
void key_conf(int *key_a, int *key_b, unsigned char important);
void key_conf_check(int key_num, int *i);
void key_color(unsigned char col);
void config_main(void);
void position_main(void);
void look_bgm(void);
void look_se(void);
int option_near(float f0, float f1, float f2, float f3);
int fade_in(void);
int fade_out(int mode);
void look_board(void);
void look_cur(void);
void allow_u(int x, int y);
void allow_d(int x, int y);
void allow_l(int x, int y);
void allow_r(int x, int y);
void KeyConfigPictureLoad(void);
void KeyConfigPitureStart(void);
void key_draw(int key_kind, int xx, int yy);
void option_font(void);
void look_scr(void);
int zs(int hoge);

#endif
