/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Lens/, by unit, in the order of their code. */
#ifndef SH2_API_LENS_H
#define SH2_API_LENS_H

#include "sh2/types.h"

/* Lens/kari_lf_draw.c */
void kari_Thr_LFD2TextureSend(void);
void kari_Thr_LFD1D2SyncKick(void *pktop);
void *kari_shLensFlareDraw(void);
void Kari_LensFlare_DrawExec(void);

/* Lens/lens_flare.c */
int shLensFlareCameraIsSmooth(void);
int shLensFlareLightCenterIsVisible(struct shLensFlareWork *lf_info);
void shLensFlareInit(void);
void shLensFlareExec(struct SubCharacter *scp, float light_intensity, int type);

/* Lens/lens_th_draw.c */
int sh2gfw_GsSetDefStoreImage(struct sceGsStoreImage *sp, short sbp, short sbw, short spsm, short x, short y, short w, short h);
int sh2gfw_GsExecStoreImage(struct sceGsStoreImage *sp, u_long128 *dstaddr);

#endif
