/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/LoadBg/, by unit, in the order of their code. */
#ifndef SH2_API_LOADBG_H
#define SH2_API_LOADBG_H

#include "sh2/types.h"

/* LoadBg/loadbg_1x1.c */
int loadBg1x1_GetIdForDrawEnv(void);
void *loadBg1x1_GetTrTexFile(void);

/* LoadBg/loadbg_2x2.c */
void loadBg2x2_CheckCacheWork(void);
void loadBg2x2_CheckLoadWork(void);
void loadBg2x2_ClearRequest(void);
void loadBg2x2_SetRequest(void);
void loadBg2x2_CleanupNonRequest(void);
int loadBg2x2_GetOutdoorBlockSection(int bx, int bz);
int loadBg2x2_GetOutdoorBlockPhase(int bx, int bz);
int loadBg2x2_CheckLoadBufferOutdoor(int bx, int bz);
int loadBg2x2_SetRequestOutdoor(int prio, int reduceRate8, int bx, int bz, int mid);
int loadBg2x2_GetIndoorRoomSection(int roomid);
int loadBg2x2_CheckLoadBufferIndoor(int roomid);
int loadBg2x2_SetRequestIndoor(int roomid, int *mid4);
int loadBg2x2_CheckRequest(int *reqUnits);
int loadBg2x2_LoadRequest(void);
int loadBg2x2_ActivateRequestOutdoor(int slot, int mid, int *reqUnits);
int loadBg2x2_ActivateRequestIndoor(int *mid4, int *reqUnits);
int loadBg2x2_GetSlotOutdoor(int bx, int bz);
int loadBg2x2_GetFreeSlotIndoor(int roomid);
int loadBg2x2_GetUseSlotIndoor(int roomid);

/* LoadBg/loadbg_all.c */
void loadBgAll_Init(void);
int loadBgAll_PrepareAround(int *loading, int *require);

/* LoadBg/loadbg_cam.c */
int loadBgCAM_ReplaceG(int mapid, void *addr, int size);
int loadBgCAM_Replace(int slot, int mapid, void *addr, int size);
void **loadBgCAM_GetLoadedDataAddrList(void);
void loadBgCAM_vcReset(void);

/* LoadBg/loadbg_camdata.c */
void loadBgCAM_LoadData(int slot, union fsFileIndex *file, int mapid);

/* LoadBg/loadbg_chara.c */
void LoadBgCharaInit(void);
int LoadBgCharaIsLoad(void);
int LoadBgCharaIsLoadSlot(int no);
int LoadBgCharaIsMapEdge(void);
void LoadBgCharaLoadSync(void);
void LoadBgGetUraCharaSlot(void **slot0, void **slot1);

/* LoadBg/loadbg_cld.c */
int loadBgCLD_Replace(int slot, int mapid, void *addr, int size);
void **loadBgCLD_GetLoadedDataAddrList(void);

/* LoadBg/loadbg_common.c */
int _loadBgCommon_LoadData(void *loadbuf, union fsFileIndex *file, int limit);
int BPOSfromFPOS(float f);
float FPOSfromBPOS(int i);
int loadBgCommon_SetInfo(int glb_crd, float px, float pz);
int loadBgCommon_HideMapBlockOutdoor(int mapid);

/* LoadBg/loadbg_event.c */
void LoadBgEventInit(void *adr, unsigned int size);
void LoadBgEventFileLoad(union fsFileIndex *fileid, void *adr);
void LoadBgEventLoadSync(void);
int LoadBgEventListCnt(void);
int LoadBgEventLoadCnt(void);
int LoadBgEventIsLoad(void);
void LoadBgEventDispose(void);

/* LoadBg/loadbg_kg2.c */
int loadBgKG2_Replace(int slot, int mapid, void *addr, int size);
void **loadBgKG2_GetLoadedDataAddrList(void);

/* LoadBg/loadbg_map.c */
int loadBgTEX_Replace(int slot, int mapid, void *addr, int size);
int loadBgMAP_Replace(int slot, int mapid, void *addr, int size);
void loadBgMAP_AllClear(void);

/* LoadBg/loadbg_mem.c */
int _loadBgMem_CmpUnitLR(struct _loadBgMem_UnitL *UnitL, struct _loadBgMem_UnitR *UnitR);
int _loadBgMem_CheckUnitC(struct _loadBgMem_UnitC *UnitC, union fsFileIndex *file, unsigned short unitID);
int _loadBgMem_SyncUnitL(struct _loadBgMem_UnitL *UnitL);
int _loadBgMem_ClearUnitL(struct _loadBgMem_UnitL *UnitL);
int _loadBgMem_ClearUnitC(struct _loadBgMem_UnitC *UnitC);
int _loadBgMem_AddUnitC(struct _loadBgMem_UnitC *UnitC, struct _loadBgMem_UnitC *prevC);
void _loadBgMem_TakeoutUnitC(struct _loadBgMem_CacheCtrl *cache, struct _loadBgMem_UnitC *UnitC);
void _loadBgMem_ShiftUnitC(struct _loadBgMem_CacheCtrl *cache, struct _loadBgMem_UnitC *UnitC);
void _loadBgMem_PushUnitC(struct _loadBgMem_CacheCtrl *cache, struct _loadBgMem_UnitC *UnitC);
struct _loadBgMem_UnitC *_loadBgMem_SearchOldestUnitC(struct _loadBgMem_CacheCtrl *cache);
struct _loadBgMem_UnitC *_loadBgMem_SearchUnitC(struct _loadBgMem_CacheCtrl *cache, union fsFileIndex *file, unsigned short unitID);
struct _loadBgMem_UnitC *_loadBgMem_SearchUnitR2C(struct _loadBgMem_CacheCtrl *cache, struct _loadBgMem_UnitR *UnitR);
struct _loadBgMem_UnitC *_loadBgMem_SearchUnitL2C(struct _loadBgMem_CacheCtrl *cache, struct _loadBgMem_UnitL *UnitL);
void _loadBgMem_MoveMemC2L(struct _loadBgMem_LoadCtrl *ctrl, struct _loadBgMem_CacheCtrl *cache, struct _loadBgMem_UnitL *UnitL, struct _loadBgMem_UnitC *UnitC);
void _loadBgMem_MoveMemL2C(struct _loadBgMem_LoadCtrl *ctrl, struct _loadBgMem_CacheCtrl *cache, struct _loadBgMem_UnitL *UnitL, struct _loadBgMem_UnitC *UnitC);
void _loadBgMem_SwapMemLC(struct _loadBgMem_LoadCtrl *ctrl, struct _loadBgMem_CacheCtrl *cache, struct _loadBgMem_UnitL *UnitL, struct _loadBgMem_UnitC *UnitC);
int _loadBgMem_LoadMemR2L(struct _loadBgMem_LoadCtrl *ctrl, struct _loadBgMem_UnitL *UnitL, struct _loadBgMem_UnitR *UnitR);
int _loadBgMem_InitLoad(struct _loadBgMem_LoadCtrl *ctrl, int UnitSize, int Units, struct _loadBgMem_UnitL *UnitLArray, struct _loadBgMem_UnitR *UnitRArray, char *Buffer);
int _loadBgMem_InitCache(struct _loadBgMem_CacheCtrl *cache, int UnitSize, int Units, struct _loadBgMem_UnitC *UnitCArray, char *Buffer);
int _loadBgMem_ClearRequest(struct _loadBgMem_LoadCtrl *ctrl);
int loadBgMem_SetRequest(struct _loadBgMem_LoadCtrl *ctrl, struct loadBgMem_Sect **SectList);
int _loadBgMem_SyncLoadUnits(struct _loadBgMem_LoadCtrl *ctrl);
int loadBgMem_CheckRequest(struct _loadBgMem_LoadCtrl *ctrl, int *reqUnits);
int _loadBgMem_CleanupNonRequest(struct _loadBgMem_LoadCtrl *ctrl);
int loadBgMem_LoadRequest(struct _loadBgMem_LoadCtrl *ctrl, struct _loadBgMem_CacheCtrl *cache, int cache_access_limit, int file_access_limit, int *cache_in_access_count, int *cache_out_access_count, int *file_access_count, int *miss_access_count);

#endif
