/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/MC/, by unit, in the order of their code. */
#ifndef SH2_API_MC_H
#define SH2_API_MC_H

#include "sh2/types.h"

/* MC/mc.c */
struct MC_WORK *mcInit(void);
void mcExec(void);
void mcSetJob(char job, char port, short data);
void mcSetGetInfo(char port);
void mcSetGetInfo2(char port);
void mcCheckAll(void);
void mcStepInit(void);
int mcStartCheck(void);
int mcStartCheck2(void);
void mcCheckDir(char port);
void mcFormat(char port);
int mcCheckStatus(char port);
int mcCheckCanSave(char port);
void mcSaveIconSys(char port, char dn);
void mcSaveIcon(char port, char dn);
void mcSaveData(char port, char dn, char fn);
void mcLoadData(char port, char dn, char fn);
void mcDeleteData(char port, char dn, char fn);
void mcMakeSaveData(void);
void mcDecodeStart(void);
void mcCodecAll(void);
void mcMakeDirData(char port, char dn, char fn);
void mcMakeDirData2(char port, char dn, char fn);
void mcMakeDirData3(void);
int mcExtDirData(void);
void mcLoadIconData(void);
int mcCheckEndLoadIconData(void);

/* MC/mc_menu.c */
int mcSaveMenu(void);
int mcLoadMenu(void);
int mcAfterLoadMenu(void);
void mcDrawMenu(void);

/* MC/savedata.c */
void SetSavePointName(unsigned short msg_no);
void SetSaveData(void);
void ExtGameData(void);
int CheckSaveData(void);
void SetGameEnvironment(void);

#endif
