/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/movie/, by unit, in the order of their code. */
#ifndef SH2_API_MOVIE_H
#define SH2_API_MOVIE_H

#include "sh2/types.h"

/* movie/movie_main.c */
void MoviePreSet(union fsFileIndex *id);
void MovieTitlePreSet(union fsFileIndex *id);
void MovieInit(void);
int MovieMain(void);
int MovieWaitReady(void);
void MoviePlayFromReady(void);
int MovieCheckSleep(void);
int MoviePlayOPMovie(void);
int movieGetLastExitStatus(void);
void movieSetSubTitleData(unsigned short *msg_bufp, void *adr_msg_time, int msg_start);

/* movie/pss_audiodec.c */
void pssAudioColdInit(struct AudioDec *ad, int iopBuffSize);
int audioDecCreate(struct AudioDec *ad, unsigned char *buff, int buffSize, int iopBuffSize);
int audioDecDelete(struct AudioDec *ad);
void audioDecPause(struct AudioDec *ad);
void audioDecResume(struct AudioDec *ad);
void audioDecStart(struct AudioDec *ad);
void audioDecReset(struct AudioDec *ad);
void audioDecBeginPut(struct AudioDec *ad, unsigned char **ptr0, int *len0, unsigned char **ptr1, int *len1);
void audioDecEndPut(struct AudioDec *ad, int size);
int audioDecIsPreset(struct AudioDec *ad);
int audioDecSendToIOP(struct AudioDec *ad);

/* movie/pss_common.c */
void PssBreakPoint(void);
int WaitSemaPss(void);
int SignalSemaPss(void);

/* movie/pss_cscvu1.c */
void cscVu1Init(struct CscVu1 *csc);
void cscVu1Xyz2offset(struct CscVu1 *csc, int type, int isBottom, int xoff, int yoff);
void cscVu1Kick(unsigned int *tags);
void cscVu1SetTag_frfl(unsigned int *tags, void *image, int width, int height);
void cscVu1SetTag_prog(unsigned int *tags, void *image, int width, int height);
void cscVu1SetTag(unsigned int *tags, int type, void *image, int width, int height);

/* movie/pss_disp.c */
void pssInitDisplay(void);
void pssDispClear(void);
void clearFinish(void);
int vblankHandler(int val);
int pssDrawSubTitle(void);
int handler_endimage(int val);
void startDisplay(int waitEven);
void endDisplay(void);

/* movie/pss_main.c */
void pssSystemColdInit(void);
void pssSetWorkAddress(void *p0, void *p1, void *p2, void *p3, void *p4, void *p5);
void pssInit(void);
void pssExit(void);
int pssSetControlData(int ctrl, union fsFileIndex *id, int frame);
int pssMain(void);
void switchThread(void);
int pssGetPssStatus(void);
int pssGetPssAbortFlag(void);
int pssGetMaskSwitch(void);
void pssSetMaskSwitch(int flg);
void pssCheckMovieCancel(void);
void pssSetSubTitleData(unsigned short *msg_bufp, void *adr_msg_time, int msg_start);
void ErrMessage(char *message);
void proceedAudio(void);

/* movie/pss_read.c */
int videoCallback(struct sceMpeg *mp, struct sceMpegCbDataStr *str, void *data);
int pcmCallback(struct sceMpeg *mp, struct sceMpegCbDataStr *str, void *data);

/* movie/pss_readbuf.c */
void readBufCreate(struct ReadBuf *b);
void readBufDelete(struct ReadBuf *b);
int readBufBeginPut(struct ReadBuf *b, unsigned char **ptr);
int readBufEndPut(struct ReadBuf *b, int size);
int readBufBeginGet(struct ReadBuf *b, unsigned char **ptr);
int readBufEndGet(struct ReadBuf *b, int size);

/* movie/pss_strfile.c */
int strFileOpen(union fsFileIndex *id);
int strFileSize(void);
int strFileRead(void *buf, int size);
int strFileClose(void);

/* movie/pss_vibuf.c */
int getFIFOindex(struct ViBuf *f, void *addr);
void setD3_CHCR(unsigned int val);
void setD4_CHCR(unsigned int val);
void scTag2(union PssQword *q, void *addr, unsigned int id, unsigned int qwc);
int viBufCreate(struct ViBuf *f, u_long128 *data, u_long128 *tag, int size, struct ViBufTs *ts, int n_ts);
int viBufReset(struct ViBuf *f);
void viBufBeginPut(struct ViBuf *f, unsigned char **ptr0, int *len0, unsigned char **ptr1, int *len1);
void viBufEndPut(struct ViBuf *f, int size);
int viBufAddDMA(struct ViBuf *f);
int viBufStopDMA(struct ViBuf *f);
int viBufRestartDMA(struct ViBuf *f);
int viBufDelete(struct ViBuf *f);
void viBufFlush(struct ViBuf *f);
int viBufModifyPts(struct ViBuf *f, struct ViBufTs *new_ts);
int viBufPutTs(struct ViBuf *f, struct ViBufTs *ts);
int viBufGetTs(struct ViBuf *f, struct ViBufTs *ts);

/* movie/pss_videodec.c */
int videoDecCreate(struct VideoDec *vd, unsigned char *mpegWork, int mpegWorkSize, u_long128 *data, u_long128 *tag, int tagSize, struct ViBufTs *pts, int n_pts);
int videoDecSetStream(struct VideoDec *vd, int strType, int ch, int (*cb)(struct sceMpeg *, union sceMpegCbData *, void *), void *data);
void videoDecBeginPut(struct VideoDec *vd, unsigned char **ptr0, int *len0, unsigned char **ptr1, int *len1);
void videoDecEndPut(struct VideoDec *vd, int size);
int videoDecDelete(struct VideoDec *vd);
void videoDecAbort(struct VideoDec *vd);
unsigned int videoDecGetState(struct VideoDec *vd);
unsigned int videoDecSetState(struct VideoDec *vd, unsigned int state);
int videoDecPutTs(struct VideoDec *vd, long pts_val, long dts_val, unsigned char *start, int len);
int videoDecFlush(struct VideoDec *vd);
void videoDecMain(struct VideoDec *vd);
int decBs0(struct VideoDec *vd);
int mpegError(struct sceMpeg *mp, struct sceMpegCbDataError *cberror, void *anyData);
int mpegNodata(struct sceMpeg *mp, union sceMpegCbData *cbdata, void *anyData);
int mpegStopDMA(struct sceMpeg *mp, union sceMpegCbData *cbdata, void *anyData);
int mpegRestartDMA(struct sceMpeg *mp, union sceMpegCbData *cbdata, void *anyData);
int mpegTS(struct sceMpeg *mp, struct sceMpegCbDataTimeStamp *cbts, void *anyData);

/* movie/pss_vobuf.c */
void voBufCreate(struct VoBuf *f, struct VoBufData *data, struct VoBufTag *tag, struct VoBufTag *tagInter, int arg4, int arg5, int size);
void voBufDelete(struct VoBuf *f);
void voBufReset(struct VoBuf *f);
int voBufIsFull(struct VoBuf *f);
void voBufIncCount(struct VoBuf *f);
struct VoBufData *voBufGetData(struct VoBuf *f);
int voBufIsEmpty(struct VoBuf *f);
struct VoBufTag *voBufGetTag(struct VoBuf *f);
void voBufDecCount(struct VoBuf *f);

#endif
