/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in the Metrowerks runtime (not in src/), by unit, in the order of their code. */
#ifndef SH2_API_MWCC_RUNTIME_H
#define SH2_API_MWCC_RUNTIME_H

#include "sh2/types.h"

/* mwcc_runtime/gcc_wrapper.c */
float _f_ulltof(unsigned long long ul);
int _dpfne(double left, double right);
int _dpflt(double left, double right);
int _dpfle(double left, double right);
int _dpfgt(double left, double right);
int _dpfge(double left, double right);

/* mwcc_runtime/Runtime/Sources/CPP_Support/mwUtils_PS2.c */
void MWNotifyOverlayLoaded(void *ovl);

#endif
