/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in the sound driver's EE side (sd0712, not in src/), by unit, in the order of their code. */
#ifndef SH2_API_SD0712_H
#define SH2_API_SD0712_H

#include "sh2/types.h"

/* sd0712/ee/sd_call.c */
/* movie/pss_audiodec.c declares it itself: called without a prototype, with five arguments. */
#ifndef SH2_LOCAL_sd_call
int sd_call(int call, int direct, int dist, int pitch);
#endif
int sd_se_stop(int call);
int sd_se_change(int call, int direct, int dist, int pitch);
int sd_track(int track, int vol);
int sd_radio(int ch, int vol, int pan, int pitch);
int sd_stat(void);
void sd_setpath(char *dp);
void sd_vsync(void);
int sd_3d_call(int call, int arg1, int arg2, float arg3, float arg4);
int sd_3d_move(int no, int arg1, int arg2, float arg3, float arg4);
void sd_3d_allstop(void);
void sd_3d_stop(int no);
void *sd_3d_adrs(void);

#endif
