/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/SH2_common/, by unit, in the order of their code. */
#ifndef SH2_API_SH2_COMMON_H
#define SH2_API_SH2_COMMON_H

#include "sh2/types.h"

/* SH2_common/data_load.c */
int DataLoadMessage(int msg);
void shMemCopy(void *ds, void *sr, int datasize);

/* SH2_common/mem_share.c */
void MemShareAllocateTitleMovie(void);
void MemShareAllocateEventMovie(int slot);
void MemShareReleaseMovie(void);
void MemShareRecoverMovie(void);
void MemShareWaitRealloc(int mode);
void *MemShareGetBgLoadWorkAddr(void);
void *MemShareGetBgLoadSectionWorkAddr(int slot);
void *MemShareGetBgLoadCacheAddr(void);
void *MemShareGetBgCharaWorkAddr(void);
void *MemShareGetEffect2WorkAddr(void);
void *MemShareGetMovieTagWorkAddr(void);
void *MemShareGetMovieVoWorkAddr(void);
void *MemShareGetMovieViWorkAddr(void);
void *MemShareGetMovieMpegWorkAddr(void);
void *MemShareGetMovieReadWorkAddr(void);

/* SH2_common/pad.c */
void shPadInit(void);
void shPadSet(void);
int shPadGetPort(void);
int shPadPress(int port, int key);
int shPadTrigger(int port, int key);
int shPadRepeat(int port, int key);
void shPadSetGameKeyAssign(void);

/* SH2_common/result.c */
void ResultMain(void);

/* SH2_common/sh2dt.c */
void shSetDF(int fpi);
int shGetDF(void);
float shGetDT(void);
float shGetFPS(void);
void shResetDF(void);
void shSetDFZero(void);
void shSetDFreal(int fpi);
float shGetDTreal(void);

/* SH2_common/sh_vu0.c */
float shAngleRegulate(float angle);
float shAtanV(float *v);
float shAtan2(float y, float x);
void shAtan_asm(void);
float shSinF(float angle);
float shCosF(float angle);
void shSinCosV(float *v, float angle);
void shSinCosV_Scale(float *v, float angle, float scale);
void shRotVectorY(float *dst, float *src, float angle);
void shRotMatrixX(float (*dst)[4], float (*src)[4], float angle);
void shRotMatrixY(float (*dst)[4], float (*src)[4], float angle);
void shRotMatrixZ(float (*dst)[4], float (*src)[4], float angle);
void shSrand(int seed);
void shPushRandSeed(int seed);
int shPopRandSeed(void);
int shRandI(void);
float shRandF(void);
void shRandF_asm(void);
void shRandV_Scale(float *v, float scale);
void shRandV_asm(void);
float shSway1f(float min, float max);
void shSway1f_asm(void);
void shCreateNormal(float *n, float *v0, float *v1, float *v2);
void shSetMiniMaxN(float *min, float *max, float (*v)[4], int n);
char shScreenClipI(int *v0);
char shScreenClipF(float *v0);
void shQzero(void *adr, int size);
void shFill(void *adr, int data, int num);
void shMulMatrix(float (*m0)[4], float (*m1)[4], float (*m2)[4]);

#endif
