/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/sh2shd/, by unit, in the order of their code. */
#ifndef SH2_API_SH2SHD_H
#define SH2_API_SH2SHD_H

#include "sh2/types.h"

/* sh2shd/sh2shd_char_jms.c */
void sh2shd_init_char_man(struct SHADOW_CHAR_MAN *man, struct SubCharacter *scp, union Q_WORDDATA *raw_data, unsigned short kind, short id, int light_kind, float *light_pos, float *light_dir, float *light_param);
void sh2shd_make_reftag_pool_char(struct SHADOW_CHAR_MAN *man, struct SHADOW_PACKET_BUF *ref_packet, union Q_WORDDATA *rawdata);
void sh2shd_make_reftag_pool_char_p_maria(struct SHADOW_CHAR_MAN *man, struct SHADOW_PACKET_BUF *ref_packet, union Q_WORDDATA *rawdata);
void sh2shd_add_char_to_kick_packet(struct SHADOW_CHAR_MAN *man, struct SHADOW_PACKET_BUF *kick_packet);
void sh2shd_renew_char_man(struct SHADOW_CHAR_MAN *man, float *spot_pos, float leng, struct SHADOW_ENV *shadow_env);
void sh2shd_renew_char_man_for_spot(struct SHADOW_CHAR_MAN *man, float *spot_pos, float leng, struct SHADOW_ENV *shadow_env);
void sh2shd_renew_char_man_parallel(struct SHADOW_CHAR_MAN *man, float *virtual_light_position);
void sh2shd_calc_light_position_for_self(float *light_pos, unsigned short kind, short id, struct JMS_SHADOW_ENV *env, float *chara_pos, float height);
void sh2shd_calc_light_position_for_self_spot(float *light_pos, unsigned short kind, short id, struct JMS_SHADOW_ENV *env, float *chara_pos, float height);
void sh2shd_make_reftag_pool_char_for_drop_with_order(struct SHADOW_CHAR_MAN *man, struct SHADOW_PACKET_BUF *ref_packet, union Q_WORDDATA *rawdata);
void sh2shd_make_reftag_pool_char_for_drop_with_order_p_maria(struct SHADOW_CHAR_MAN *man, struct SHADOW_PACKET_BUF *ref_packet, union Q_WORDDATA *rawdata);
void sh2shd_renew_char_man_for_drop(struct SHADOW_CHAR_MAN *man, float *spot_pos, float alpha_decay);
void sh2shd_get_height_for_alpha(float *high, float *low, unsigned short kind, unsigned short id);
int sh2shd_get_shape_no(unsigned short kind, int skel_no);
int sh2shd_get_shape_no_jms(int skel_no);
int sh2shd_get_shape_no_mar(int skel_no);
int sh2shd_get_shape_no_p_mar(int skel_no);
int sh2shd_get_shape_no_scu(int skel_no);
int sh2shd_get_shape_no_mkn(int skel_no);
int sh2shd_get_shape_no_nse(int skel_no);
int sh2shd_get_shape_no_red(int skel_no);
int sh2shd_get_shape_no_oni(int skel_no);
int sh2shd_get_shape_no_edb(int skel_no);

/* sh2shd/sh2shd_outdoor.c */
void sh2shd_init_outdoor_man2(struct SHADOW_OUTDOOR_MAN *man, union Q_WORDDATA *raw_data, short arg2, short light_kind, float *light_pos, float *light_dir, float *light_param);
void sh2shd_make_reftag_pool_outdoor(struct SHADOW_OUTDOOR_MAN *man, struct SHADOW_PACKET_BUF *ref_packet, float spot_cam_angle);
void sh2shd_make_reftag_pool_outdoor_for_parallel(struct SHADOW_OUTDOOR_MAN *man, struct SHADOW_PACKET_BUF *ref_packet);
void sh2shd_add_outdoor_to_kick_packet(struct SHADOW_OUTDOOR_MAN *man, struct SHADOW_PACKET_BUF *kick_packet);
void sh2shd_renew_outdoor_man(struct SHADOW_OUTDOOR_MAN *man, float *spot_pos, struct SHADOW_ENV *shadow_env);
void sh2shd_renew_outdoor_man_for_parallel(struct SHADOW_OUTDOOR_MAN *man, float *spot_pos, struct SHADOW_ENV *shadow_env);

/* sh2shd/sh2shd_shadow_env.c */
void sh2shd_get_shadow_env_bg(struct SHADOW_ENV *env, struct SHADOW_OUTDOOR_HEAD *head);
void sh2shd_get_shadow_env_chr(struct SHADOW_ENV *env, struct SHADOW_CHAR_MAN *chr_man, int glb_coord, int map_id);
void sh2shd_get_demo_shadow_env_for_bg(struct SHADOW_ENV *env, int demo_no);
void sh2shd_get_demo_shadow_env_for_char(struct SHADOW_ENV *env, struct SHADOW_CHAR_MAN *man, int demo_no);
void sh2shd_get_jms_shadow_env(struct JMS_SHADOW_ENV *env, int light_kind, float *light_dir);
void sh2shd_get_demo_jms_shadow_env(struct JMS_SHADOW_ENV *env, int demo_no);
void sh2shd_get_drop_shadow_env(struct DROP_SHADOW_ENV *env, int glb_coord, int map_id, float x, float z);
void sh2shd_get_demo_drop_shadow_env(struct DROP_SHADOW_ENV *env, int demo_no);
void sh2shd_demo_shadow_off(int demo_no);
void sh2shd_shadow_off(int glb_coord, int map_id);
void get_map_id(int *glb_coord, int *map_id);
int check_bg_light_exist(void);

/* sh2shd/sh2shd_shadow_model.c */
void sh2shd_init_shadow(void);
void sh2shd_reset_shadow(void);
int sh2shd_add_char(struct SubCharacter *scp, union Q_WORDDATA *raw_data, short light_kind, float *light_pos, float *light_dir, float *light_param);
int sh2shd_Draw_ShadowChar(struct SubCharacter *scp, void *kg1, unsigned short kind, unsigned short id, short light_kind, float *light_pos, float *light_dir, float *light_param);
int sh2shd_add_map(unsigned short id, union Q_WORDDATA *raw_data, short light_kind, float *light_pos, float *light_dir, float *light_param);
union Q_WORDDATA *sh2shd_exe_shadow(struct sh2gfw_CAMERA *cam);
float get_distance_from_light_to_chara(struct SHADOW_CHAR_MAN *man, float *iv);
union Q_WORDDATA *sh2shd_exe_drop_shadow(struct sh2gfw_CAMERA *cam);
void sh2shd_renew_drop_shadow_man(struct SPOT_LIGHT *spot, struct sh2gfw_CAMERA *cam, int glb_coord, int map_id);
void sh2shd_make_stencil_drop_shadow_plane(float *plane, float *pos, float *normal);
void sh2shd_make_drop_shadow_plane(float *plane, float *pos, float *normal);
void sh2shd_reset_shadow_off_work(void);
int sh2shd_add_map_to_shadow_off_work(short map_id);
int sh2shd_off_obj(short map_id, short obj_id);
int sh2shd_add_char_to_shadow_off_work(unsigned short kind, short id);
int sh2shd_off_char_obj(unsigned short kind, short id, short obj_id);
int sh2shd_off_char_all_parts(unsigned short kind, short id);
void sh2shd_bg_shadow_off(void);
void sh2shd_del_jms_upper_body(unsigned short kind, short id);
void sh2shd_del_jms_head(unsigned short kind, short id);

/* sh2shd/sh2shd_shadow_vu1_packet.c */
void shadow_micro_init(struct SHADOW_MICRO_FRAME *mic, struct shGsAllEnv *env);
void shadow_set_micro_params(struct SHADOW_MICRO_FRAME *mic, struct sh2gfw_CAMERA *cam, float (*drop_shadow)[4], int spot_cam_flag);
void shadow_add_micro2kick_packet(struct SHADOW_MICRO_FRAME *mic, struct SHADOW_PACKET_BUF *packbuf, unsigned int *rawdata);
void drop_shadow_micro_init(struct DROP_SHADOW_MICRO_FRAME *mic, struct shGsAllEnv *env, struct DROP_SHADOW_ENV *ds_env);
void drop_shadow_set_micro_params(struct DROP_SHADOW_MICRO_FRAME *mic, struct sh2gfw_CAMERA *cam);
void drop_shadow_add_micro2kick_packet(struct DROP_SHADOW_MICRO_FRAME *mic, struct SHADOW_PACKET_BUF *packbuf, unsigned int *rawdata);

/* sh2shd/sh2shd_stencil_shadow_main.c */
union Q_WORDDATA *stencil_shadow_main(struct sh2gfw_CAMERA *cam);
union Q_WORDDATA *not_stencil_shadow_main(struct sh2gfw_CAMERA *cam);

/* sh2shd/sh2shd_structs.c */
void sh2shd_init_packet_buf(struct SHADOW_PACKET_BUF *packet, union Q_WORDDATA *buf);
void sh2shd_reset_packet_buf(struct SHADOW_PACKET_BUF *packet);

#endif
