/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/shGs/, by unit, in the order of their code. */
#ifndef SH2_API_SHGS_H
#define SH2_API_SHGS_H

#include "sh2/types.h"

/* shGs/sh2gfw_GS_NewLoopEnv.c */
int sh2gfw_RotateTBuff(struct shGsAllEnv *shGsEnv);
int sh2gfw_ReturnTBuff(struct shGsAllEnv *shGsEnv);
int sh2gfw_RotateNext2(struct shGsAllEnv *stdb);
void sh2gfw_set_LoopDrawEnv(struct shGsAllEnv *stdb);
u_long128 *sh2gfw_Get_FrameNormalRegAddr(void);
u_long128 *sh2gfw_Get_FrameAlphaRegAddr(void);
void sh2gfw_StartShadowEnv(struct shGsAllEnv *stdb);
unsigned int sh2gfw_GetStencilFBP(struct shGsAllEnv *stdb);
unsigned int sh2gfw_GetFilterFBP(struct shGsAllEnv *stdb, unsigned int page);
void sh2gfw_StartShadowFilter(struct shGsAllEnv *stdb, unsigned int page);
void sh2gfw_ChangeMask_ShadowFilter(struct shGsAllEnv *stdb, int mode, int pageno);
void sh2gfw_ChangeClear_StencilBuf(struct shGsAllEnv *stdb, unsigned int r, unsigned int g, unsigned int b, unsigned int a);
unsigned int sh2gfw_InclimentLoopCounter(struct shGsAllEnv *stdb);
unsigned int sh2gfw_DeclimentLoopCounter(struct shGsAllEnv *stdb);
int sh2gfw_ForceSet_MovieDrawLoopCounter(void);
unsigned int sh2gfw_GetNowDispFBP(struct shGsAllEnv *stdb);
unsigned int sh2gfw_GetTexTBP0(struct shGsAllEnv *stdb, unsigned int page);
unsigned int sh2gfw_GetSendingClutTBP0(struct shGsAllEnv *stdb, unsigned int page);
unsigned int sh2gfw_Get_BaseTBP0for2D(void);

/* shGs/sh2gfw_GsInit.c */
void shGs_InitDefTBuff(struct shGsAllEnv *shGsEnv, short draw_psm, short disp_psm, short w, short h, short ztest, short zpsm);
void shGs_TrimDispArea(int xx, int yy);
void shGs_SetDefaultDispArea(void);
void shGsSetDefTBuffDispEnv(struct sceGsDispEnv *disp, short psm, short w, short h, short dx, short dy);
int shGsSetDefTBuffDrawEnv(struct sceGsDrawEnv1 *draw, short psm, short w, short h, short ztest, short zpsm);
void shGs_InitGsStencilBuff(struct shGsAllEnv *shGsEnv, short w, short h, short ztest, short zpsm);
int shGs_InitStencilDrawEnv(struct shGsStencilDrawEnv *ssb, short w, short h, short ztest, short zpsm);
void shGs_InitGsTinyStencilBuff(struct shGsAllEnv *shGsEnv, short w, short h);
void shGs_InitDefaultRegsEnv(struct shGsAllEnv *shGsEnv);

#endif
