/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/sound/, by unit, in the order of their code. */
#ifndef SH2_API_SOUND_H
#define SH2_API_SOUND_H

#include "sh2/types.h"

/* sound/sh_sd_call.c */
int shSdInit(void);
void shSdVSync(void);
int shSdCall(int i0, int i1, int i2, int i3);
int shSdSeStop(int i0);
int shSdStat(void);
int shSd3dCall(int i0, int i1, int i2, float f0, float f1);
int shSd3dMove(int i0, int i1, int i2, float f0, float f1);
void shSd3dStop(int i0);
void shSd3dAllStop(void);
int shSdSeChange(int i0, int i1, int i2, int i3);
int shSdTrack(int i0, int i1);
int shSdRadio(int i0, int i1, int i2, int i3);
void *shSd3dAdrs(void);

/* sound/sh_sound.c */
void SeWait(int wait);
void SeForceWait(void);
void SeCallInit(int sect, int mmode, char *path);
void SeCallReset(void);
int SeCall(int sd_no, float volume, int stereo);
int SeCallPos(int sd_no, float volume, float *pos, int status);
int SeCallPosChange(int sd_no, float volume, float *pos, int status);
int SeCallPosDirection(float *pos);
int SeCallPosDistance(float volume, float *pos);
float SeCallPosDistanceF(float *pos);
int Se3dPlayCheck(int sd_no);
void SeSoundLoad(void);
void SeSoundEffectLoad(int data);
void SeSoundEffect3dLoad(int data);
void SeSoundManager(void);
void Se2dManager(void);
void Se2dManageDataVolumeChange(int sd, float vol);
float Se2dManageDataTimer(int sd, int clear);
void Se3dManager(void);
int Se3dControl(int sd_no, float volume, float *pos);
void SeStop(int sd_no);
void SeBgmChange(void);
void SeBgmCall(int bgm_no);
void SeBgmManager(void);
int BgmPageSet(void);
void SeMasterVolumeChange(void);

/* sound/snd_select.c */
void sndVolumeMain(void);
void sndGetSoundAryByCharaPos(struct _SOUND_WORK *w_p);

#endif
