/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/taskman/, by unit, in the order of their code. */
#ifndef SH2_API_TASKMAN_H
#define SH2_API_TASKMAN_H

#include "sh2/types.h"

/* taskman/shtskman.c */
void shTSKInitTaskList(unsigned char *buffer, unsigned int size);
struct _shTskTASK *shTSKSetTask(void (*func)(void *), unsigned char num);
struct _shTskTASK *shTSKSetTaskPrev(struct _shTskTASK *task, void (*func)(void *));
void shTSKDelTask(struct _shTskTASK *task);
struct _shTskTASK *shTSKCutTask(struct _shTskTASK *task);
void shTSKExecuteTask(unsigned char num);
struct _shTskTASK *shTSKSearchTaskWithAtr(int atr, struct _shTskTASK *start, unsigned char num);
void shTSKFreeTaskLine(unsigned char num);

#endif
