/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined directly in src/, by unit, in the order of their code. */
#ifndef SH2_API_TOP_H
#define SH2_API_TOP_H

#include "sh2/types.h"

/* connect.c */
int connectMain(void);

/* gamemain.c */
char *get_gp_data_buf_addr(void);
int GameMain(void);
int PlayableMain(void);

/* jump_menu.c */
void JumpMenuPosNormal(void);
void CheckModeJumpDataSet(void);

/* logo.c */
void logoCheckingMemcard(void);
void logoDrawWarningCESA(void);
void logoDrawWarningSCE(void);
void logoDrawKonamiLogo(void);

/* main.c */
int main(int argc, char **argv);
void GameKeyCheck(void);

/* now_loading.c */
void NowLoadingEnable(void);
void NowLoadingCheck(void);
void NowLoadingDraw(void);

/* pause.c */
int PauseSetType(int type);
int PauseDisp(void);

/* sh2_init.c */
void systemColdInit(void);
int systemHotInit(void);

/* sh2gfw_all_sysinit.c */
int Vcallback_test(int ca);
void init_PS2(void);
void step_init_ONE(void);
void step_init_STAGE(void);
void map_DATA_LOAD(void);

/* sh2gfw_drawloop_main.c */
void all_Frame_Buffer_Clear(void);
void DrawLopp_Pre(void);
void kari_drawloop_main_2dSYNC(void);
void draw_main_3dSYNC(void);
void DrawLopp_Post(void);
unsigned int Get_FrameRate(void);
void draw_main(void);

#endif
