/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/view/, by unit, in the order of their code. */
#ifndef SH2_API_VIEW_H
#define SH2_API_VIEW_H

#include "sh2/types.h"

/* view/vb_main.c */
void vbCalcViewScreenMatrix(void);
void vbInitCoordinate(struct _VbCOORDINATE *super, struct _VbCOORDINATE *coord);
void vbSetWorldScreenMatrix(void);
void vbGetLw(struct _VbCOORDINATE *coord, int fflip);
int vbSetRefView(struct _VbRVIEW *rview);
float vbNormalizeRadianAngle(float ang);
void vbTransposeMatrixWithoutTr(float (*m0)[4], float (*m1)[4]);
void vbApplyMatrixWithoutTr(float *v0, float (*m0)[4], float *v1);

/* view/vc_calc.c */
float vcRetNearRatioSwitchAreaInXZPos(struct _VC_NEAR_ROAD_DATA cur_near_road, float *chr_pos, float *cam_tgt_pos);
/* view/vc_calc.c declares it itself: declared with a 16-byte aligned by-value struct (the DWARF drops the alignment). */
#ifndef SH2_LOCAL_vcRetNearRatioSwitchAreaForCircleCam
float vcRetNearRatioSwitchAreaForCircleCam(struct _VC_NEAR_ROAD_DATA cur_near_road, struct _VC_CIR_CAM_MANAGER cir_man, float *chr_pos);
#endif
void vcTransRotRoadArea(float *v0, float (*m)[4], float *v1);
void vcRotTransRoadArea(float *v0, float (*m)[4], float *v1);
float vcGetMinInRoadDist(void);
void vcConvertCamFile(struct _VC_ROAD_DATA *road_ary);

/* view/vc_main.c */
void vcInitVCSystem(struct _VC_ROAD_DATA **vc_road_ary_list);
void vcStartCameraSystem(void);
void vcSetFirstCamWork(float *cam_pos, float chara_eye_ang_y, int use_through_door_cam_f);
void vcUserWatchTarget(float *watch_tgt_pos, struct _VC_WATCH_MV_PARAM *watch_prm_p, float rot_z, int warp_watch_f);
void vcUserCamTarget(float *cam_tgt_pos, struct _VC_CAM_MV_PARAM *cam_prm_p, int warp_cam_f);
void vcGetNowWatchPos(float *watch_pos);
void vcGetNowCamPos(float *cam_pos);
void vcReturnPreAutoCamWork(int warp_f);
void vcSetSubjChara(float *chara_pos, float chara_bottom_y, float chara_top_y, float chara_grnd_y, float *chara_head_pos, float chara_mv_spd, float chara_mv_ang_y, float chara_ang_spd_y, float chara_eye_ang_y, float chara_eye_ang_wy, float chara_watch_xz_r);
int vcExecCamera(void);
void vcSetAllNpcDeadTimer(void);
void vcSetEventCamParamRefView(float *vp, struct _VC_CAM_MV_PARAM *cam_prm_p, float *vr, struct _VC_WATCH_MV_PARAM *watch_prm_p, float rot_z, int warp_flg);
void vcSetProjectionValue(float new, int framecnt);
void vcChangeProjectionValue(struct _VC_WORK *w_p);

/* view/vc_newest.c */
void vcEndProcessingVC_WORK(void);
void vcEndProcessingOldNearRoad(struct _VC_NEAR_ROAD_DATA *old_cur_p, struct _VC_WORK *w_p);
void vcCorrectCamMatAngForcibly(float *ofs_cam_ang, struct _VC_ROAD_DATA rd_data);
void vcWarpForFixAngCam(struct _VC_WORK *w_p);
float vcRetCirRadiusReduction(struct _VC_WORK *w_p);
void vcChangeProjByDist(struct _VC_NEAR_ROAD_DATA *near_rd_p, float mv_vec_y);

/* view/vc_play.c */
void vcPreSetCharaDataForCamera(void);

/* view/vc_prio.c */
int vcRetPrioStgEvnt(int glb_crd);

/* view/vc_util.c */
void vcInitCamera(struct _VC_ROAD_DATA **roadarray_list);
void vcSetCameraUseWarp(float *chr_pos, float chr_ang_y);
int vcRetCamMvSmoothF(void);
void vcMoveAndSetCamera(int in_connect_f, int arg1, int for_f, int back_f, int right_f, int left_f, int up_f, int down_f);
void vcMakeHeroHeadPos(float *head_pos);
void vcAddOfsToPos(float *out_pos, float *in_pos, float ofs_xz_r, float ang_y, float ofs_y);
void vcSetRefPosAndSysRef2CamParam(float *ref_pos, struct _SYS_W *sys_p, int for_f, int back_f, int right_f, int left_f, int up_f, int down_f);
void vcSetRefPosAndCamPosAngByPad(void);

/* view/vw_calc.c */
void vwRenewalXZVelocityToTargetPos(float *velo_xz, float *now_pos, float *tgt_pos, float tgt_r, float accel, float total_max_spd, float dec_forwd_lim_spd, float dec_accel_side);
void vwLimitOverLimVector(float *vec_xz, float lim_vec_len, float lim_vec_ang_y);
void vwDecreaseSideOfVector(float *vec_xz, float dec_val, float max_side_vec_len, float dir_ang_y);
float vwRetNewVelocityToTargetVal(float now_spd, float mv_pos, float tgt_pos, float accel, float total_max_spd, float dec_val_lim_spd);
float vwRetNewAngSpdToTargetAng(float now_ang_spd, float now_ang, float tgt_ang, float accel_spd, float total_max_ang_spd, float dec_val_lim_spd);
void vwAngleToVector(float *vec, float *ang, float r);
float vwVectorToAngle(float *ang, float *vec);
int vwOresenHokan(int *y_ary, int y_suu, int input_x, int min_x, int max_x);
void vwRotMatrixYXZ(float *rot, float (*mat)[4]);
void vwMatrixToAngleYXZ(float *ang, float (*mat)[4]);
float vwRet3DLength(float x, float y, float z);

/* view/vw_main.c */
void vwInitViewInfo(void);
void vwGetViewPosition(float *pos);
void vwGetViewAngle(float *ang);
void vwSetCoordRefAndEntou(struct _VbCOORDINATE *parent_p, float *ref, float cam_ang_y, float cam_ang_z, float cam_y, float cam_xz_r);
void vwSetViewInfo(void);
void vwSetViewInfoDirectMatrix(struct _VbCOORDINATE *pcoord, float (*cammat)[4]);

#endif
