#!/usr/bin/env python3
"""Extract the matching targets from the user's disc files into build/orig/.

- build/orig/main.bin: contents of the ELF's `main` section (loaded at 0x100000).
- build/orig/gx_<name>.bin: each overlay binary on the disc (GX/<NAME>.BIN, loaded at 0x1F01E00).
- include/assets/**.inc (gitignored): game data files that the original linked into its code as
  initialized arrays (ASSETS), as C initializer lists that the source #includes. They are the
  game's data, so they come from the user's disc and are never committed.
"""
import hashlib
import shutil
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DISC = ROOT / "baserom" / "disc"
ELF = DISC / "SLUS_202.28"
ELF_SHA1 = "888eff71606ff4c1c610e30111b3ca5da647edcc"
OUT = ROOT / "build" / "orig"
MAIN_VRAM = 0x100000

# (address in main, size, output under include/): data files embedded in the original's .data.
ASSETS = [
    (0x0034FFE0, 24091, "assets/Event/stage/stg_tgs_trial/dds_tsuri.inc"),  # drama-demo script ("dds")
]


def write_assets(main_bin):
    """Write each ASSETS range of main.bin as a C initializer list."""
    for addr, size, rel in ASSETS:
        blob = main_bin[addr - MAIN_VRAM:addr - MAIN_VRAM + size]
        lines = [", ".join(f"0x{b:02X}" for b in blob[i:i + 16]) + "," for i in range(0, len(blob), 16)]
        out = ROOT / "include" / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text("/* Generated by tools/extract.py from the user's disc. */\n" + "\n".join(lines) + "\n",
                       encoding="utf-8", newline="\n")
    print(f"{len(ASSETS)} embedded data files")


def assets_present():
    return all((ROOT / "include" / rel).exists() for _, _, rel in ASSETS)

OVERLAY_SHA1 = {
    "AEE": "3bfa8ef006f02c616262327a9ff3f8b6c9d97192",
    "AEW": "c867cbccef33b2f4541a3a3ffced05eb0934bf05",
    "AEX": "261d15bdc6b929ddd776c4c3841fdf1fdbc2b5c4",
    "AEY": "e5c4abaea73e3e19f4d22fa1bb5f93818b0dd46a",
    "AOT": "5c4942e4276abb1d10cc28e750682ab65aedd8dc",
    "AST": "4054ca0d501328bd595a28384603b34257004c8f",
    "AWX": "4c1f71ff4519f701202f251fa7233a51c176c7c1",
    "AWY": "5d7853013882a9cc610c32f13c2bf93f986ac993",
    "FST": "f2dddb6a7e3b86a9ec4bcdd0d91ab240ea188697",
    "OBS": "f132348a6257cb2bf54fcd3b47764aa7185c8ce0",
    "TOI": "52ff0a97c6b240db7ca01575826b64ceddfd314a",
    "TWE": "981fc444233e9c601a8c7e07bb7645ed19813b5d",
}


def main():
    data = ELF.read_bytes()
    if hashlib.sha1(data).hexdigest() != ELF_SHA1:
        sys.exit(f"{ELF}: unexpected SHA1; this project targets the 2001-07-13 prototype")
    OUT.mkdir(parents=True, exist_ok=True)

    (_, _, _, _, _, _, shoff, _, _, _, _, shentsize, shnum, shstrndx) = \
        struct.unpack_from("<16sHHIIIIIHHHHHH", data, 0)
    secs = [struct.unpack_from("<10I", data, shoff + i * shentsize) for i in range(shnum)]
    st = secs[shstrndx][4]
    for s in secs:
        if data[st + s[0]:data.index(b"\0", st + s[0])] == b"main":
            main_bin = data[s[4]:s[4] + s[5]]
            (OUT / "main.bin").write_bytes(main_bin)
            print(f"main.bin: {s[5]:#x} bytes")
            write_assets(main_bin)

    for name, sha1 in OVERLAY_SHA1.items():
        src = DISC / "GX" / f"{name}.BIN"
        if hashlib.sha1(src.read_bytes()).hexdigest() != sha1:
            sys.exit(f"{src}: unexpected SHA1")
        shutil.copyfile(src, OUT / f"gx_{name.lower()}.bin")
    print(f"{len(OVERLAY_SHA1)} overlays")
    return 0


if __name__ == "__main__":
    sys.exit(main())
