#!/usr/bin/env python3
"""Which matched functions each stand-in for stripped code is needed by (config/standin_deps.txt).

A stand-in is any `__stripped_*` function in src/ (tools/standins.py's STANDIN): the fitted
constant-count stand-ins (`static float __stripped_float_code_*`, `STRIPPED_DOUBLE_CODE()`) and
the guessed reconstructions of config/stripped_functions.txt. All of them leave compiler state
(docs/toolchain.md, "Root cause"): the float-constant order or the software-double register mode
of later functions, pooled literals, the .bss layout. Which functions need one is measured, not
assumed: for every stand-in, the unit is compiled once more with that stand-in's text removed
(its lines kept, and the preprocessor lines inside it such as `#line`, so `__LINE__` doesn't
move) and compared with the original, with the fallback to original code off
(ASM_FALLBACK_LIST=/dev/null, so the C is compared, not the original code). The functions that
match with the stand-in and don't without it are its dependents. Functions linked from the
original code (config/asm_functions.txt) don't count.

A unit with several stand-ins is also compiled with all of them removed at once, so that a
function two redundant stand-ins both support (it still matches without either one alone) isn't
missed: the functions that fail then and in no single removal are recorded for the unit as a
whole (`together`). The unit's dependents are the union of both.

tools/progress.py counts the dependents as fitted, and those of stand-ins at a place where the
original's line table shows no code stood (tools/standins.py) as fake. A stand-in with no
dependents, in a unit with no `together` dependents, is dead code.

Each unit's result is stored with a hash of what decides it (the source, the headers it includes,
its compiler flags, config/stripped_functions.txt, its config/asm_functions.txt entries), so a
rerun only compiles units that changed. Run in the build environment (WSL), after `ninja`:

    .venv/bin/python tools/standin_deps.py            # update config/standin_deps.txt (changed units)
    .venv/bin/python tools/standin_deps.py --all      # recompute every unit
    .venv/bin/python tools/standin_deps.py --check    # measure everything again, write nothing;
                                                      # exit 1 if the file is out of date
    .venv/bin/python tools/standin_deps.py Enemy/en_mkn   # recompute these units
"""
import argparse
import hashlib
import os
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tools"))
import lint  # noqa: E402
from standins import STANDIN  # noqa: E402
OUT = ROOT / "config" / "standin_deps.txt"
WORK = ROOT / "build" / "standin_deps"
VERSION = "2"  # bump when the measurement changes, to invalidate every stored hash

HEADER = """\
# Generated by tools/standin_deps.py: do not edit. The matched functions each stand-in for stripped
# code (`__stripped_*`) is needed by (its dependents): they match with the stand-in and stop
# matching when its text alone is removed (fallback to original code off; config/asm_functions.txt
# functions don't count).
# Regenerate after changing a unit with stand-ins (only changed units are recompiled):
#     .venv/bin/python tools/standin_deps.py
# `hash <unit> <sha1>`: what the unit's rows were measured from (source, headers, flags,
# config/stripped_functions.txt, its asm_functions entries); tools/check_all.sh checks it's current.
# `<unit> <stand-in> <line> <dependent>...`: `-` when it has none. Where no function fails,
# `!<kind>` records a compile error or a new layout problem (a section, a relocation).
# `together <unit> <dependent>...`: functions that fail only when all the unit's stand-ins are
# removed at once (more than one supports them); written when there are any.
"""


def standins(text):
    """[(name, first line, start offset, end offset)] of every stand-in in a C file's text.

    The extent is the stand-in's own text: `STRIPPED_DOUBLE_CODE()`, or the function's definition
    up to its closing brace (not a comment after it; braces in comments and literals don't count)."""
    out = []
    code = lint.strip_c(text, keep_pp=True)  # the same offsets, comments and literals blanked
    for m in STANDIN.finditer(text):
        name = m.group(1) or m.group(2)
        end = m.end()
        if m.group(1):
            depth, i = 0, m.end() - 1  # the definition's `{`
            while True:
                c = code[i]
                depth += c == "{"
                depth -= c == "}"
                i += 1
                if c == "}" and depth == 0:
                    break
            end = i
        out.append((name, text.count("\n", 0, m.start()) + 1, m.start(), end))
    return out


def blank(text, start, end):
    """text with [start, end) removed except its newlines and its preprocessor lines (a `#line`
    inside a stand-in numbers the lines after it), so no later line moves."""
    kept = [ln if ln.lstrip().startswith("#") else "" for ln in text[start:end].split("\n")]
    return text[:start] + "\n".join(kept) + text[end:]


def unit_targets():
    import linkable
    return linkable.unit_targets()


def asm_listed(target, unit):
    """The unit's functions in config/asm_functions.txt (read directly: the compiles here set
    ASM_FALLBACK_LIST=/dev/null, but these still don't count as dependents)."""
    out = set()
    for line in (ROOT / "config" / "asm_functions.txt").read_text(encoding="utf-8").splitlines():
        p = line.split("#")[0].split()
        if len(p) == 2:
            t, _, u = p[0].rpartition(":")
            if (t or "main") == target and u == unit:
                out.add(p[1])
    return out


def unit_hash(unit, target):
    """Hash of everything that decides a unit's stand-in dependents."""
    import cdeps
    import configure
    src = ROOT / "src" / f"{unit}.c"
    h = hashlib.sha1(VERSION.encode())
    h.update(" ".join(configure.unit_cflags(unit if target == "main" else f"{target}:{unit}")).encode())
    h.update(src.read_bytes())
    for dep in sorted(cdeps.scan(src.resolve(), set())):
        h.update(dep.relative_to(ROOT).as_posix().encode())
        h.update(dep.read_bytes())
    h.update((ROOT / "config" / "stripped_functions.txt").read_bytes())
    h.update(" ".join(sorted(asm_listed(target, unit))).encode())
    return h.hexdigest()


def run_variant(unit, target, text, tag):
    """(matched functions, problem lines) of one version of a unit's source, fallback off.

    The file keeps the unit's base name (MWCC's __FILE__ is the bare name); None on a compile error."""
    d = WORK / unit / tag
    d.mkdir(parents=True, exist_ok=True)
    path = d / (Path(unit).name + ".c")
    path.write_text(text, encoding="utf-8", newline="\n")
    arg = unit if target == "main" else f"{target}:{unit}"
    env = dict(os.environ, ASM_FALLBACK_LIST="/dev/null")
    r = subprocess.run([sys.executable, str(ROOT / "tools" / "diff_unit.py"), arg, "--src", str(path)],
                       cwd=ROOT, capture_output=True, text=True, env=env)
    lines = r.stdout.splitlines()
    if not any(" functions match" in ln for ln in lines):
        return None, [(r.stdout + r.stderr).strip()[-300:]]
    ok = {ln.split()[1] for ln in lines if ln.startswith("  OK ")}
    problems = [ln.strip()[3:] for ln in lines if ln.startswith("  !! ")]
    return ok, problems


def measure(unit, target, jobs):
    """([(stand-in, line, [dependents])], [together dependents]) for one unit: each stand-in's
    dependents when it alone is removed, and the functions that fail only when all are removed."""
    text = (ROOT / "src" / f"{unit}.c").read_text(encoding="utf-8")
    found = standins(text)
    skip = asm_listed(target, unit)
    variants = [("base", text)] + [(f"no_{i}", blank(text, s, e)) for i, (_, _, s, e) in enumerate(found)]
    if len(found) > 1:
        none = text
        for _, _, s, e in reversed(found):  # from the last, so the earlier offsets stay valid
            none = blank(none, s, e)
        variants.append(("none", none))
    with ThreadPoolExecutor(max_workers=jobs) as pool:
        results = list(pool.map(lambda v: run_variant(unit, target, v[1], v[0]), variants))
    base_ok, base_problems = results[0]
    if base_ok is None:
        sys.exit(f"{unit}: the unit doesn't compile: {base_problems[0]}")
    rows = []
    for (name, line, _, _), (ok, problems) in zip(found, results[1:1 + len(found)]):
        if ok is None:
            deps = ["!compile-error"]
        else:
            deps = sorted(base_ok - ok - skip)
            if not deps:
                # Without failing functions, a new layout problem (a section, a relocation) still
                # means the stand-in is needed: record the problem's kind, so it isn't called dead.
                deps = sorted({"!" + p.split()[0].rstrip(":") for p in problems if p not in base_problems})
        rows.append((name, line, deps))
    together_deps = []
    if len(found) > 1:
        ok, _ = results[-1]
        alone = {d for _, _, deps in rows for d in deps}
        together_deps = ["!compile-error"] if ok is None else sorted(base_ok - ok - skip - alone)
    return rows, together_deps


def load():
    """({unit: hash}, {unit: ([(stand-in, line, [dependents])], [together dependents])}) from
    config/standin_deps.txt."""
    hashes, rows = {}, {}
    if not OUT.exists():
        return hashes, rows
    for line in OUT.read_text(encoding="utf-8").splitlines():
        p = line.split("#")[0].split()
        if not p:
            continue
        if p[0] == "hash":
            hashes[p[1]] = p[2]
            rows.setdefault(p[1], ([], []))
        elif p[0] == "together":
            rows.setdefault(p[1], ([], []))[1].extend(p[2:])
        else:
            rows.setdefault(p[0], ([], []))[0].append((p[1], int(p[2]), [d for d in p[3:] if d != "-"]))
    return hashes, rows


def dependents():
    """{(unit, stand-in): [dependents]} from config/standin_deps.txt (for tools/progress.py and
    tools/standins.py; names starting with `!` are problems, not functions)."""
    _, rows = load()
    return {(u, name): deps for u, (rs, _) in rows.items() for name, _, deps in rs}


def together():
    """{unit: [dependents]}: a unit's functions that fail only when all its stand-ins are removed
    at once (the `together` lines of config/standin_deps.txt)."""
    _, rows = load()
    return {u: t for u, (_, t) in rows.items() if t}


def save(hashes, rows):
    out = [HEADER]
    for unit in sorted(rows):
        out.append(f"hash {unit} {hashes[unit]}\n")
        standin_rows, together_deps = rows[unit]
        for name, line, deps in standin_rows:
            out.append(f"{unit} {name} {line} {' '.join(deps) or '-'}\n")
        if together_deps:
            out.append(f"together {unit} {' '.join(together_deps)}\n")
    OUT.write_text("".join(out), encoding="utf-8", newline="\n")


def units_with_standins():
    out = []
    for path in sorted((ROOT / "src").rglob("*.c")):
        if STANDIN.search(path.read_text(encoding="utf-8")):
            out.append(path.relative_to(ROOT / "src").with_suffix("").as_posix())
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("units", nargs="*", help="recompute only these units")
    ap.add_argument("--all", action="store_true", help="recompute every unit, even unchanged ones")
    ap.add_argument("--check", action="store_true", help="measure every unit again and compare, without writing")
    ap.add_argument("-j", type=int, default=4, help="compiler processes at once (default 4)")
    args = ap.parse_args()
    targets = unit_targets()
    hashes, rows = load()
    units = units_with_standins()
    now = {u: unit_hash(u, targets[u]) for u in units}
    stale = [u for u in units if hashes.get(u) != now[u]]
    gone = sorted(set(rows) - set(units))
    if args.check:
        # Measure every unit again (under a minute) rather than trusting the hashes, so a change
        # the hash doesn't cover (the compare tools, the compiler) is caught too.
        bad = [f"{u}: changed since it was measured" for u in stale]
        bad += [f"{u}: has no stand-ins any more" for u in gone]
        for u in units:
            if u not in stale and measure(u, targets[u], args.j) != rows.get(u):
                bad.append(f"{u}: measured dependents differ from the file")
        for b in bad:
            print(f"config/standin_deps.txt: {b}")
        if bad:
            print("run: .venv/bin/python tools/standin_deps.py --all")
            return 1
        print(f"config/standin_deps.txt is current ({len(units)} units)")
        return 0
    todo = args.units or (units if args.all else stale)
    for u in gone:
        del rows[u]
        hashes.pop(u, None)
    for u in todo:
        if u not in now:
            sys.exit(f"{u}: no stand-ins in src/{u}.c")
        rows[u] = measure(u, targets[u], args.j)
        hashes[u] = now[u]
        for name, line, deps in rows[u][0]:
            print(f"{u} {name}:{line} -> {' '.join(deps) or '(none)'}")
        if rows[u][1]:
            print(f"{u} together -> {' '.join(rows[u][1])}")
        save(hashes, rows)  # after every unit, so an interrupted run keeps what it measured
    save(hashes, rows)
    print(f"{len(todo)} units measured, {len(units) - len(todo)} unchanged")
    return 0


if __name__ == "__main__":
    sys.exit(main())
