/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Multi_thr/boot/, by unit, in the order of their code. */
#ifndef SH2_API_MULTI_THR_BOOT_H
#define SH2_API_MULTI_THR_BOOT_H

#include "sh2/types.h"

/* Multi_thr/boot/bootopt.c */
void BootOptGet(int argc, char **argv);

#endif
