/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Multi_thr/dma/, by unit, in the order of their code. */
#ifndef SH2_API_MULTI_THR_DMA_H
#define SH2_API_MULTI_THR_DMA_H

#include "sh2/types.h"

/* Multi_thr/dma/dma1cmd.c */
void d1cSubCmdUpdataLastRegistCid(int cid);
int d1cSubSubCmdCheckFlushCache(void);
void d1cSubCmdFlushCache(void);
int d1cInit(void);
int d1cCmdSend(void *tag);
int d1cSend(void *tag);

/* Multi_thr/dma/dma1serv.c */
int d1sInit(int th_prio, void *stack, int stackSize, void *queue, int queueSize);
int d1sSync(int mode, int cid);
int d1sGetCurCmdId(void);
int d1sCmpCID(int cid0, int cid1);
int d1sPutCmd0(int (*f0)(void));
int d1sPutCmd1(int (*f1)(void), u_long128 a1);

/* Multi_thr/dma/dma1tscmd.c */
int d1tscCmdSync(int d2cid);
int d1tscSync(int d2cid);
int d1tscCmdFinishToUseSlot(int slot);
int d1tscFinishToUseSlot(int slot);

/* Multi_thr/dma/dma2cmd.c */
void d2cSubCmdUpdataLastRegistCid(int cid);
int d2cSubSubCmdCheckFlushCache(void);
void d2cSubCmdFlushCache(void);
int d2cInit(void);
int d2cCmdSend(void *tag);

/* Multi_thr/dma/dma2serv.c */
int d2sInit(int th_prio, void *stack, int stackSize, void *queue, int queueSize);
int d2sSync(int mode, int cid);
int d2sGetCurCmdId(void);
int d2sCmpCID(int cid0, int cid1);
int d2sPutCmd0(int (*f0)(void));
int d2sPutCmd1(int (*f1)(void), u_long128 a1);
int d2sPutCmd3(int (*f3)(void), u_long128 a1, u_long128 a2, u_long128 a3);

/* Multi_thr/dma/dma2tscmd.c */
int d2tscCmdBeginToUseSlot(int slot);
int d2tscBeginToUseSlot(int slot);
int d2tscCmdSend(int slot, int texid, void *tag);
int d2tscSend(int slot, int texid, void *tag);
int d2tscCmdClearSlots(void);
int d2tscClearSlots(void);

/* Multi_thr/dma/sh_dma1.c */
int shDmaVif1Init(void);
int shDmaVif1Send(void *packet);

/* Multi_thr/dma/sh_dma2.c */
int shDmaGifInit(void);
int shDmaGifSend(void *packet);

/* Multi_thr/dma/texslot.c */
int texSlotInit(void);
int texSlotBeginToUse(int slot);
int texSlotFinishToUse(int slot);
int texSlotGetCurTexID(int slot);
int texSlotSetCurTexID(int slot, int texid);
int texSlotClearAll(void);

#endif
