/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Multi_thr/filesys/, by unit, in the order of their code. */
#ifndef SH2_API_MULTI_THR_FILESYS_H
#define SH2_API_MULTI_THR_FILESYS_H

#include "sh2/types.h"

/* Multi_thr/filesys/fcread.c */
int FcFixFile(union fsFileIndex *id);
int fcGetFileSize(union fsFile *file);
int FcGetFileSize(union fsFileIndex *id);
int FcRead(union fsFileIndex *id, void *databuf);
int FcReadPart(union fsFileIndex *id, void *databuf, int offset, int size);

/* Multi_thr/filesys/filecmd.c */
union fsFile *fsCmdCheckFixFile(union fsFile *fp);
int fsCmdCheckExistFile(union fsFile *fp);
int fsCmdSetRealFile(union fsFile *realfp, union fsFile *fp);
int fsCmdDiskSelectC(void);
int fsCmdDiskSelectCH(void);
int fsCmdDiskSelectHC(void);
int fsCmdExecDevSelect(int mode);
int fsCmdFixFile(union fsFile *fp);
int fsCmdHdInit(int enable);
int fsCmdRead(union fsFile *fp, void *buf);
int fsCmdReadPart(union fsFile *fp, void *buf, int offset, int size);
int fsCmdSetParamForCheckDisk(int media_permission, union fsFile **fplist, void **buflist, int (*check_func)(union fsFile **, void **));
int fsCmdCdCheckDisk(int force_check);
int fsCmdCdCheckDisk2(int force_check, int media_permission, union fsFile **fplist, void **buflist, int (*check_func)(union fsFile **, void **));
int fsCmdGetTrayStat(void);

/* Multi_thr/filesys/filepath.c */
int shPathCheckExecRoot(char *filename);
int shPathMakeIop(char *fullpath, char *filename);
int shPathMakeCdData(char *fullpath, char *filename);
int shPathMakeHdData(char *fullpath, char *filename);
int shPathMakeCdDataBase(char *fullpath, char *filename);
int shPathMakeHdDataBase(char *fullpath, char *filename);
int ___shPathMakeCdDataBase(char *fullpath, char *filename);
int ___shPathMakeCdData(char *fullpath, char *filename);
int ___shPathMakeHdDataBase(char *fullpath, char *filename);
int ___shPathMakeHdData(char *fullpath, char *filename);

/* Multi_thr/filesys/fileserv.c */
int fsInit(int th_prio, void *stack, int stackSize, void *queue, int queueSize);
int fsSync(int mode, int fid);
int fsGetStat(struct CmdServStat *stat);
int fsGetTrayStat(void);
int fcSifInit(void);
int fcCdInitW(int cb_prio, void *stack, int stackSize);
int fcIopLoadMod(char *module);
int fcDiskSelectC(void);
int fcDiskSelectCH(void);
int fcDiskSelectHC(void);
int fcHdInit(int mode);
int fcDiskSelect(int mode);
int fcExecDevSelect(int mode);
int fcSetParamForCheckDisk(int media_permission, union fsFile **fplist, void **buflist, int (*check_func)(union fsFile **, void **));
int fcCdCheckDisk(int force_check);
int fcRead(union fsFile *fp, void *buf);
int fcReadPart(union fsFile *fp, void *buf, int offset, int size);
int fcFixFile(union fsFile *fp);

/* Multi_thr/filesys/iopload.c */
int shIopReplaceMod(char *imgfile);
int shIopLoadMod(char *module);

/* Multi_thr/filesys/sh_cdvd.c */
int shCdInit(int initmode, int mmode);
int shCdMmode(int mmode);
int shCdInitR(int initmode, int mmode);
int shCdInitW(int cb_prio, void *stack, int stack_size);
int shSifInit(void);
int shSdSifInit(void);
int shSifSyncIop(void);
int shSifLoadModule(char *module, int args, char *argp);
int shSifLoadModuleR(char *module, int args, char *argp);
int shSifRebootIop(char *imgfile);
int shSifRebootIopR(char *imgfile);
int shCdRead(int lsn, int sectors, void *buf, struct sceCdRMode *mode);
int shCdSeek(int lsn);
int shCdReadW(int lsn, int sectors, void *buf, struct sceCdRMode *mode);
int shCdSeekW(int lsn);
int shCdReadClock(struct sceCdCLOCK *rtc);
int shCdSearchFile(struct sceCdlFILE *file, char *fullpath);
int ___shCdSearchFile(struct sceCdlFILE *fp, char *name);
int shCdDiskReady(int mode);
int shCdGetDiskType(void);
int shCdTrayReq(int mode, unsigned int *traycnt);
int shCdGetError(void);
int shCdStatus(void);
int shCdSync(int mode);
void shCdSdStart(void);
void shCdSdEnd(void);
int shHdInit(void);
int shHdOpen(char *name, int mode);
int shHdRead(int fd, void *buffer, int size);
int shHdClose(int fd);
int shHdLseek(int fd, int offset, int where);
int ___shHdGetFileSize(char *name);

/* Multi_thr/filesys/sh_chk_syscnf.c */
int fcSetParamForSystemCnf(int debug);

#endif
