/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Multi_thr/intc/, by unit, in the order of their code. */
#ifndef SH2_API_MULTI_THR_INTC_H
#define SH2_API_MULTI_THR_INTC_H

#include "sh2/types.h"

/* Multi_thr/intc/syncv.c */
int shSyncVStartInit(void);
int shSyncVEndInit(void);
int shSyncVStart(int mode);
int shSyncVEnd(int mode);

/* Multi_thr/intc/th_vbe.c */
int ThreadVbeStart(void *stack, int stackSize, int prio, int option, int wait_sid);

/* Multi_thr/intc/th_vbs.c */
int ThreadVbsStart(void *stack, int stackSize, int prio, int option, int wait_sid);

#endif
