/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Multi_thr/kernel/, by unit, in the order of their code. */
#ifndef SH2_API_MULTI_THR_KERNEL_H
#define SH2_API_MULTI_THR_KERNEL_H

#include "sh2/types.h"

/* Multi_thr/kernel/wrap_printf.c */
void wrap_printf_init(void);

#endif
