/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Multi_thr/loadinit/, by unit, in the order of their code. */
#ifndef SH2_API_MULTI_THR_LOADINIT_H
#define SH2_API_MULTI_THR_LOADINIT_H

#include "sh2/types.h"

/* Multi_thr/loadinit/loadinit.c */
int lisInit(int th_prio, void *stack, int stackSize, void *queue, int queueSize);
int lisSync(int mode, int cid);
int lisGetStat(struct CmdServStat *stat);
int lisPutCmd0(int (*f0)(void));

#endif
