/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Multi_thr/pad/, by unit, in the order of their code. */
#ifndef SH2_API_MULTI_THR_PAD_H
#define SH2_API_MULTI_THR_PAD_H

#include "sh2/types.h"

/* Multi_thr/pad/keydata.c */
int shSysKeyNormalize(char *paddata);
int shSysKeyAdjust(char *paddata);
int shGameKeyConvert(union shGameKeyData *key, char *paddata);
void shGameKeyGetAssign(struct shGameKeyAssign *assign);
void shGameKeySetAssign(struct shGameKeyAssign *assign);

/* Multi_thr/pad/th_pad.c */
int ThreadPadStart(void *stack, int stackSize, int prio, int option, int wait_sid);

#endif
