/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Multi_thr/scf/, by unit, in the order of their code. */
#ifndef SH2_API_MULTI_THR_SCF_H
#define SH2_API_MULTI_THR_SCF_H

#include "sh2/types.h"

/* Multi_thr/scf/ps2_scf.c */
void ps2ScfInit(void);
int ps2ScfGetLanguage(void);
int ps2ScfGetAspect(void);
int ps2ScfGetSpdif(void);
int ps2ScfGetTimeZone(void);
int ps2ScfGetDateNotation(void);
int ps2ScfGetSummerTime(void);
int ps2ScfGetTimeNotation(void);
void ps2ScfGetLocalTimefromRTC(struct sceCdCLOCK *rtc);

/* Multi_thr/scf/sh2_scf.c */
void sh2ScfInit(void);
enum SPEC_LANG_O sh2ScfGetDefaultLanguage(void);
unsigned int UtilBCDToDecimal(unsigned int bcd);
int sh2ScfMakeDateStr(char *datestr, unsigned int year, unsigned int month, unsigned int day);
int sh2ScfMakeDateStrByLocalTimeFromJST(char *datestr, struct sceCdCLOCK *jst);
int sh2ScfMakeTimeStr(char *timestr, unsigned int hour24, unsigned int minute, unsigned int second);
int sh2ScfMakeTimeStrFromRTC(char *timestr, struct sceCdCLOCK *rtc);
int sh2ScfMakeTimeStrByLocalTimeFromJST(char *datestr, struct sceCdCLOCK *jst);

#endif
