/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Multi_thr/sys/, by unit, in the order of their code. */
#ifndef SH2_API_MULTI_THR_SYS_H
#define SH2_API_MULTI_THR_SYS_H

#include "sh2/types.h"

/* Multi_thr/sys/init_mt_sys.c */
void check_build_environment(char *bootfilename);
int init_sh2_filesys(void);
void init_sh2_dmac(void);
int init_sh2_devsys(void);

#endif
