/* Generated by tools/gen_headers.py from the prototype's DWARF. Do not edit. */
/* The global functions defined in src/Multi_thr/util/, by unit, in the order of their code. */
#ifndef SH2_API_MULTI_THR_UTIL_H
#define SH2_API_MULTI_THR_UTIL_H

#include "sh2/types.h"

/* Multi_thr/util/cmd_serv.c */
int CmdServInit(u_long128 *work, int workSize, void *stack, int stackSize, int prio);
int CmdQueuePut0(u_long128 *work, int (*func)(void));
int CmdQueuePut1(u_long128 *work, int (*func)(void), u_long128 a0);
int CmdQueuePut2(u_long128 *work, int (*func)(void), u_long128 a0, u_long128 a1);
int CmdQueuePut3(u_long128 *work, int (*func)(void), u_long128 a0, u_long128 a1, u_long128 a2);
int CmdQueuePut4(u_long128 *work, int (*func)(void), u_long128 a0, u_long128 a1, u_long128 a2, u_long128 a3);
int CmdQueueSync(u_long128 *work, int mode, int id);
int CmdQueueGetCurrentCommandId(u_long128 *work);
int CmdQueueCmpCmdId(int cid0, int cid1);
int CmdServGetStat(u_long128 *work, struct CmdServStat *stat);

/* Multi_thr/util/utilexcl.c */
int utilExclInit(void);
int utilExclLockOtherThread(void);
int utilExclUnlockOtherThread(void);

/* Multi_thr/util/utilstr.c */
int UtilStrCpyL(char *dst, char *src, int limit);
int UtilStrCatL(char *dst, char *s1, char *s2, int limit);
int UtilStrCat3L(char *dst, char *s1, char *s2, char *s3, int limit);
int UtilStrPathCatL(char *dst, char *path1, char *path2, int limit);
int UtilStrConvertCdPath(char *path);
int UtilStrConvertHdPath(char *path);
int UtilMemCpy(char *dst, char *src, int n);
int UtilMemSet(char *dst, char ch, int n);
int UtilMemSwap(char *dst, char *src, int n);

#endif
